export default {
  TrafficSignal: "Phasenfunktion wählen",
  ModDefault: "Standard",
  Vanilla: "Vanilla",
  SplitPhasing: "Aufgeteilte Phase",
  ProtectedRightTurns: "Geschütztes rechts abbiegen",
  ProtectedLeftTurns: "Geschütztes links abbiegen",
  Options: "Optionen",
  ExclusivePedestrianPhase: "Exklusive Fußgängerphase",
  LaneDirectionTool: "Fahrspurausrichtung (Experimentell)",
  
  // Buttons
  Add: "Phase hinzufügen",
  Back: "Zurück",
  ManualControl: "Manuelle Steuerung",
  CustomPhase: "Eigene Phase",
  CustomPhaseEditor: "Eigene Phasen programmieren",
  SelectFunction: "Funktion wählen",
  SelectFunctionDescription: "Wähle eine Funktion, um dein Verkehrsnetzwerk zu konfigurieren.",
  EditIntersectionPhases: "Kreuzungsphasen bearbeiten",
  IntersectionMonitor: "Kreuzungsüberwachung",
  DashboardComingSoon: "Kommt bald...",
  
  Close: "Schließen",
  Open: "Öffnen",
  Reset: "Zurücksetzen",
  Save: "Speichern",
  PleaseSave: "Bitte speichere die Einstellungen, bevor du eine andere Kreuzung bearbeitest.",
  PleaseSelectJunction: "Bitte wähle eine Kreuzung aus",
  GiveWayToOncomingVehicles: "Vorfahrt für entgegenkommende Fahrzeuge",
  CustomPedestrianDurationMultiplier: "Dauer der Fußgängerphase",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Erlaube abbiegen bei Rot",
  CanaryBuildWarning: "Bitte beachte, dass du ein Canary-Build verwenden, das mit größerer Wahrscheinlichkeit spiel- oder speicherschädigende Bugs enthält und nur zum Testen gedacht ist. Verwenden Sie diesen Build NICHT für den normalen Spielbetrieb.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  
  // Custom Phase Optionen
  PrioritiseTrack: "Individualverkehr priorisieren",
  PrioritisePublicCar: "ÖPNV priorisieren",
  PrioritisePedestrian: "Fußgänger priorisieren",
  PrioritiseBicycle: "Radfahrer priorisieren",
  
  // Custom Phase Optionen - Tooltips
  PrioritiseTrackTooltip: "Gibt Fahrspuren für normale Fahrzeuge (Autos, LKW) während dieser Ampelphase Vorrang",
  PrioritisePublicCarTooltip: "Gibt ÖPNV-Fahrspuren (Busse, Straßenbahnen) während dieser Ampelphase Vorrang",
  PrioritisePedestrianTooltip: "Gibt Fußgängerüberwegen während dieser Ampelphase Vorrang",
  PrioritiseBicycleTooltip: "Gibt Radwegen während dieser Ampelphase Vorrang",
  
  // Custom Phase Anpassungen
  Adjustments: "Anpassungen",
  MinimumDuration: "Min. Dauer",
  MaximumDuration: "Max. Dauer",
  TargetDurationMultiplier: "Zieldauer",
  LaneOccupiedMultiplier: "Fahrspurbelegung",
  IntervalExponent: "Intervall-Exponent",
  
  // Custom Phase Anpassungen - Tooltips
  MinimumDurationTooltip: "Mindestdauer der Grünphase. Die Ampel bleibt mindestens so lange grün, auch wenn wenig Verkehr ist.",
  MaximumDurationTooltip: "Maximale Grünphase. Nach dieser Zeit wechselt die Ampel, auch wenn noch Verkehr wartet.",
  TargetDurationMultiplierTooltip: "Beeinflusst die Länge der Grünphase. 1x = Normal, 2x = Doppelt so lange bei Verkehr, 0.5x = Kürzer.",
  LaneOccupiedMultiplierTooltip: "Steuert, wie stark volle Fahrspuren die Priorität erhöhen. Höher = Staus werden schneller aufgelöst.",
  IntervalExponentTooltip: "Fairness-Einstellung. Höher = Phasen die lange warten mussten werden stärker bevorzugt.",
  
  // Custom Phase Statistiken
  Statistics: "Statistiken",
  Timer: "Timer",
  Priority: "Priorität",
  LastRun: "Letzter Durchlauf",
  CarFlow: "Fahrzeugfluss",
  LanesOccupied: "Belegte Fahrspuren",
  WeightedWaiting: "Gewichtete Wartezeit",
  
  // Custom Phase Statistiken - Tooltips
  TimerTooltip: "Aktueller Phasen-Timer / Zieldauer",
  PriorityTooltip: "Aktuelle Priorität dieser Phase",
  LastRunTooltip: "Anzahl der Durchgänge seit diese Phase zuletzt lief",
  CarFlowTooltip: "Aktueller Fahrzeugfluss durch diese Phase",
  LanesOccupiedTooltip: "Anzahl belegter Fahrspuren (Fahrzeuge, ÖPNV, Schiene, Fußgänger)",
  WeightedWaitingTooltip: "Gewichtete Wartezeit der Fahrzeuge an dieser Phase",
  
  // Custom Phase Buttons
  EndPhasePrematurely: "Phase jetzt beenden",
  PhaseEndRequested: "Phasenende angefordert",
  // Phase Copy/Paste Feature
  SelectAll: "Alle auswählen",
  DeselectAll: "Auswahl aufheben",
  CopyPhases: "Phasen kopieren",
  PastePhases: "Phasen einfügen",
  DeleteSelectedPhases: "Ausgewählte löschen",
  ClearClipboard: "Zwischenspeicher leeren",
  
  // Phase Copy/Paste Tooltips
  SelectAllTooltip: "Alle Phasen für Kopieren oder Löschen auswählen",
  CopyPhasesTooltip: "Ausgewählte Phasen in den Zwischenspeicher kopieren",
  PastePhasesTooltip: "Phasen aus dem Zwischenspeicher einfügen",
  DeleteSelectedPhasesTooltip: "Ausgewählte Phasen unwiderruflich löschen",
  ClearClipboardTooltip: "Zwischenspeicher leeren, um versehentliches Einfügen zu vermeiden",

  // Green Wave / Sync Groups
  GreenWave: "Grüne Welle",
  GreenWaveButton: "Grüne Welle",
  SyncGroup: "Sync-Gruppe",
  NoSyncGroup: "Keine Gruppe",
  CreateNewGroup: "Neue Gruppe erstellen",
  CycleOffset: "Zyklus-Offset",
  UseSyncedCycle: "Sync aktivieren",
  TotalCycleDuration: "Gesamte Zyklusdauer",
  BaseCycleDuration: "Basis-Zyklus",
  IntersectionsInGroup: "Kreuzungen",
  NewGroupName: "Neue Gruppe",
  DeleteGroup: "Gruppe löschen",
  RenameGroup: "Umbenennen",
  OpenGreenWavePanel: "Grüne Welle öffnen",
  GreenWavePanelActive: "Grüne Welle aktiv",
  
  // Phase Mode
  PhaseMode: "Phasen-Modus",
  LegacyMode: "Standard (Priorität)",
  LegacyModeHint: "Nächste Phase nach Verkehrsaufkommen",
  LegacyModeTooltip: "Phasen werden nach Priorität geschaltet - basierend auf wartenden Fahrzeugen und Fußgängern. Standard-Spielverhalten.",
  SequentialMode: "Sequentiell (Reihenfolge)",
  SequentialModeHint: "Phasen 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Phasen laufen der Reihe nach: 1 → 2 → 3 → 4 → 1... Feste, vorhersagbare Reihenfolge. Erforderlich für Grüne Welle.",
  GreenWaveForcesSequential: "Grüne Welle erfordert sequentiellen Modus",
  
  SyncSettings: "Sync-Einstellungen",
  SyncPhase: "Sync-Phase",
  SyncPhaseTooltip: "Wähle die Phase, die synchronisiert werden soll. Nützlich für Abbiegerspuren.",
  OffsetCalculator: "Offset-Rechner",
  Distance: "Entfernung",
  Speed: "Tempo",
  RecommendedOffset: "Empfohlen",
  Apply: "Übernehmen",
  OwnCycle: "Eigener Zyklus",
  GroupBase: "Gruppen-Basis",
  AutoFactor: "Auto-Faktor",
  AutoFactorTooltip: "Verhältnis zwischen eigenem Zyklus und Gruppen-Basis. Bei unterschiedlichen Zykluslängen wird automatisch skaliert.",
  Intersections: "Kreuzungen",
  NoGroupsYet: "Noch keine Gruppen erstellt",
  Information: "Information",
  
  // Green Wave Tooltips
  GreenWaveTooltip: "Synchronisiere mehrere Kreuzungen für eine grüne Welle",
  GreenWaveTooltipActive: "Synchronisiere mehrere Kreuzungen entlang einer Straße, damit Fahrzeuge bei grüner Welle ohne Halt durchfahren können.",
  GreenWaveTooltipDisabled: "Grüne Welle ist nur verfügbar, wenn 'Eigene Phasen' für diese Kreuzung aktiviert ist. Wähle zuerst 'Eigene Phasen' aus.",
  SyncGroupTooltip: "Wähle eine Sync-Gruppe für diese Kreuzung",
  CycleOffsetTooltip: "Zeitversatz in Sekunden zum Gruppen-Timer. Verschiedene Offsets erzeugen die grüne Welle.",
  UseSyncedCycleTooltip: "Aktiviert die Synchronisation mit der gewählten Gruppe",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Kreuzung",
  GWP_TabGroups: "Gruppen",
  GWP_TabDashboard: "Dashboard",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Synchronisation aktiv",
  GWP_NotSynced: "Nicht synchronisiert",

  // Green Wave Panel - Labels
  GWP_NodeId: "Node ID (Kreuzung)",
  GWP_Group: "Gruppe",
  GWP_Offset: "Offset",
  GWP_AssignSyncGroup: "Sync-Gruppe zuweisen",
  GWP_NoGroupSelected: "Keine Gruppe ausgewählt",
  GWP_NoGroup: "Keine Gruppe",
  GWP_NewGroup: "+ Neue Gruppe",
  GWP_Rename: "Umbenennen",
  GWP_EnableSync: "Sync aktivieren",
  GWP_CycleOffset: "Zyklus-Offset",
  GWP_Tempo: "Tempo",
  GWP_Recommended: "Empfohlen:",
  GWP_GameTime: "Spiel",
  GWP_RealTime: "Echt",
  GWP_PhaseHint: "Phase #1 sollte die Hauptrichtung für die Grüne Welle sein!",
  GWP_AutoSave: "Änderungen werden automatisch gespeichert",
  GWP_SelectIntersection: "Bitte wähle eine Kreuzung aus.",
  GWP_SearchGroups: "Gruppe suchen...",
  GWP_NoMatches: "Keine Treffer für",
  GWP_RemoveFromGroup: "Aus Gruppe entfernen",
  GWP_DeleteGroup: "Gruppe löschen",
  GWP_NoIntersections: "Keine Kreuzungen",
  GWP_GroupsHint: "Gruppen ohne Kreuzungen können gelöscht werden. Kreuzungen hinzufügen im 'Kreuzung'-Tab.",
  GWP_SelectGroupHint: "Wähle eine Gruppe im 'Kreuzung'-Tab um Details zu sehen.",
  GWP_AddIntersectionsHint: "Diese Gruppe hat noch keine Kreuzungen. Gehe zum 'Kreuzung'-Tab und füge Kreuzungen hinzu!",
  GWP_RemovedFromGroup: "Aus Gruppe entfernt",
  GWP_AddedToGroup: "Hinzugefügt zu",
  GWP_SyncEnabled: "Sync aktiviert!",
  GWP_SyncDisabled: "Sync deaktiviert",
  GWP_NewGroupCreated: "Neue Gruppe erstellt!",
  GWP_GroupRenamed: "Gruppe umbenannt zu",
  GWP_GroupDeleted: "Gruppe gelöscht",
  GWP_IntersectionRemoved: "Kreuzung aus Gruppe entfernt",
  GWP_OffsetSet: "Offset gesetzt auf",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Aktiviert die Synchronisation dieser Kreuzung mit der Gruppe.",
  GWP_TT_SyncPhase: "Wähle die Phase die synchronisiert werden soll. Phase #1 sollte die Hauptrichtung (Grüne Welle) sein.",
  GWP_TT_CycleOffset: "Zeitversatz in Sekunden zum Gruppen-Basiszyklus.",
  GWP_TT_Distance: "Entfernung zur vorherigen Kreuzung in Metern.",
  GWP_TT_Speed: "Geschwindigkeit des Verkehrs auf der Straße.",
  GWP_TT_OwnCycle: "Die Gesamtdauer eines Ampelzyklus dieser Kreuzung in Spielzeit.",
  GWP_TT_GroupBase: "Der Basiszyklus der Gruppe in Spielzeit.",
  GWP_TT_Intersections: "Anzahl der Kreuzungen in dieser Gruppe.",
  GWP_MoveUp: "Nach oben",
  GWP_MoveDown: "Nach unten",
  GWP_ManageGroups: "Sync-Gruppen verwalten",
  GWP_CreateNewGroup: "+ Neue Gruppe erstellen",
  
  // V183: Dashboard Tab Lokalisierung
  GWP_DB_Intersection: "Kreuzung",
  GWP_DB_Reference: "REFERENZ",
  GWP_DB_Phases: "Phasen",
  GWP_DB_Green: "GRÜN",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "AUS",
  GWP_DB_SyncWaiting: "Sync aktiv - wartend",
  GWP_DB_GreenWaveActive: "Grüne Welle aktiv!",
  GWP_DB_ReadyToSwitch: "Wechselbereit",
  GWP_DB_Offset: "OFFSET",
  GWP_DB_Cycle: "ZYKLUS",
  GWP_DB_Roads: "STRAẞEN",
  GWP_DB_Lanes: "SPUREN",
  GWP_DB_Pedestrians: "FUẞG.",
  GWP_DB_OffsetDelta: "Versatz",
  GWP_DB_BaseCycle: "Basis-Zyklus",
  GWP_DB_GreenWaveLabel: "Grüne Welle",
  GWP_DB_SyncActiveLabel: "Sync aktiv",
  GWP_DB_ReorderHint: "Nutze die Pfeiltasten um die Reihenfolge anzupassen. Die erste Kreuzung ist die Referenz (Offset 0).",
  GWP_DB_PhaseProgressTooltip: "Links: Mindestdauer (Phase muss mindestens so lange laufen). Blinkend: Phase ist bereit zum Wechseln und wartet auf günstigen Moment.",
  GWP_DB_MinDurationTooltip: "Bei 50% ist die Mindestdauer erreicht. Die Phase kann ab hier jederzeit wechseln. Der blinkende Bereich zeigt, dass auf einen günstigen Wechselzeitpunkt gewartet wird.",
  GWP_DB_PhaseXofY: "Phase {0} von {1}",

  // V147: Traffic Summary
  TrafficSummary: "Verkehrsübersicht",
  VehiclesPerHour: "Ø Durchsatz",
  VehiclesPerMinute: "Fahrzeuge/Min",
  Approaches: "Zufahrten",
  IncomingLanes: "Einfahrtsspuren",
  IncomingLanesTooltip: "Physische Fahrspuren die in die Kreuzung führen. Basis für Belegungsberechnung.",
  OccupiedLanes: "Belegte Spuren",
  OccupiedLanesTooltip: "Anzahl belegter Einfahrtsspuren mit wartenden Fahrzeugen. Basis für Verkehrsstatus.",
  OccupiedPedestrianLanes: "Bel. Fußg.-Spuren",
  TrafficFlowLow: "Wenig Verkehr",
  TrafficFlowMedium: "Mäßiger Verkehr",
  TrafficFlowHigh: "Viel Verkehr",
  
  // V179: Neue Statistiken
  WaitingVehicles: "Wartende Fz.",
  WaitingVehiclesTooltip: "Aktuelle Anzahl wartender Fahrzeuge an dieser Kreuzung (geglätteter Durchschnitt).",
  PeakHour: "Spitze (24h)",
  PeakHourTooltip: "Uhrzeit mit dem höchsten Verkehrsaufkommen der letzten 24 Stunden.",
  MaxVPH: "Max Fz/h (24h)",
  MaxVPHTooltip: "Höchster gemessener Durchsatz der letzten 24 Stunden.",
  
  // V147: Info-Tooltips
  VPH_InfoEstimate: "Schätzung basierend auf Spuranzahl und Belegung. Aktiviere 'Eigene Phase' für echte Messung.",
  VPH_InfoRealData: "Gleitender Durchschnitt der echten Fahrzeugzählung (Fz/h). Auf 10er gerundet.",
  
  // V147: Chart Tooltips
  ChartDisabledTooltip: "Aktiviere 'Eigene Phase' um Verkehrsdaten zu sammeln",
  ChartCollectingTooltip: "Sammle Daten... Erste Werte nach ~30 Spielminuten",
  ChartActiveTooltip: "24-Stunden Verkehrsverlauf",
  CustomPhaseRequiredTooltip: "Erfordert, dass 'Eigene Phasen' für diese Kreuzung aktiviert ist.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Phase löschen?",
};
