export default {
  TrafficSignal: "Traffic Signal",
  ModDefault: "Default",
  Vanilla: "Vanilla",
  SplitPhasing: "Split Phasing",
  ProtectedRightTurns: "Protected Right-Turns",
  ProtectedLeftTurns: "Protected Left-Turns",
  Options: "Options",
  ExclusivePedestrianPhase: "Exclusive Pedestrian Phase",
  LaneDirectionTool: "Lane Direction Tool (Experimental)",
  
  // Buttons
  Add: "Add Phase",
  Back: "Back",
  ManualControl: "Manual Control",
  CustomPhase: "Custom Phase",
  CustomPhaseEditor: "Edit Custom Phases",
  SelectFunction: "Select Function",
  SelectFunctionDescription: "Choose a function to configure your traffic network.",
  EditIntersectionPhases: "Edit Intersection Phases",
  IntersectionMonitor: "Intersection Monitor",
  DashboardComingSoon: "Coming soon...",
  
  Close: "Close",
  Open: "Open",
  Reset: "Reset",
  Save: "Save",
  PleaseSave: "Please save changes before selecting another junction.",
  PleaseSelectJunction: "Please Select a Junction",
  GiveWayToOncomingVehicles: "Give Way to Oncoming Vehicles",
  CustomPedestrianDurationMultiplier: "Pedestrian Phase Duration",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Allow Turning on Red",
  CanaryBuildWarning: "Please note that you are using a canary build, which is more likely to contain game-breaking or save-breaking bugs and is strictly for playtesting only. DO NOT use this build for normal gameplay.",
  LdtMigrationNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Please install the Traffic mod, and it will automatically transfer your current lane settings to it. Click for more details (Open in a web browser).",
  LdtRetirementNotice: "Lane Direction Tool has now been retired and succeeded by Traffic mod from krzychu124. Thank you for using LDT.",
  
  // Custom Phase Options
  PrioritiseTrack: "Prioritize Vehicles",
  PrioritisePublicCar: "Prioritize Public Transit",
  PrioritisePedestrian: "Prioritize Pedestrians",
  PrioritiseBicycle: "Prioritize Cyclists",
  
  // Custom Phase Options - Tooltips
  PrioritiseTrackTooltip: "Gives priority to regular vehicle lanes (cars, trucks) during this traffic light phase",
  PrioritisePublicCarTooltip: "Gives priority to public transit lanes (buses, trams) during this traffic light phase",
  PrioritisePedestrianTooltip: "Gives priority to pedestrian crossings during this traffic light phase",
  PrioritiseBicycleTooltip: "Gives priority to bicycle lanes during this traffic light phase",
  
  // Custom Phase Adjustments
  Adjustments: "Adjustments",
  MinimumDuration: "Min. Duration",
  MaximumDuration: "Max. Duration",
  TargetDurationMultiplier: "Target Duration",
  LaneOccupiedMultiplier: "Lane Occupancy",
  IntervalExponent: "Interval Exponent",
  
  // Custom Phase Adjustments - Tooltips
  MinimumDurationTooltip: "Minimum green light duration. The signal stays green at least this long, even with little traffic.",
  MaximumDurationTooltip: "Maximum green light duration. After this time, the signal switches even if traffic is still waiting.",
  TargetDurationMultiplierTooltip: "Affects green phase length. 1x = Normal, 2x = Double length when busy, 0.5x = Shorter.",
  LaneOccupiedMultiplierTooltip: "Controls how much full lanes increase priority. Higher = Traffic jams clear faster.",
  IntervalExponentTooltip: "Fairness setting. Higher = Phases that waited longer get more priority.",
  
  // Custom Phase Statistics
  Statistics: "Statistics",
  Timer: "Timer",
  Priority: "Priority",
  LastRun: "Last Run",
  CarFlow: "Car Flow",
  LanesOccupied: "Lanes Occupied",
  WeightedWaiting: "Weighted Waiting",
  
  // Custom Phase Statistics - Tooltips
  TimerTooltip: "Current phase timer / Target duration",
  PriorityTooltip: "Current priority value of this phase",
  LastRunTooltip: "Number of turns since this phase last ran",
  CarFlowTooltip: "Current vehicle flow through this phase",
  LanesOccupiedTooltip: "Number of occupied lanes (vehicles, transit, track, pedestrians)",
  WeightedWaitingTooltip: "Weighted waiting time for vehicles at this phase",
  
  // Custom Phase Buttons
  EndPhasePrematurely: "End Phase Now",
  PhaseEndRequested: "End Phase Requested",
  // Phase Copy/Paste Feature
  SelectAll: "Select All",
  DeselectAll: "Deselect All",
  CopyPhases: "Copy Phases",
  PastePhases: "Paste Phases",
  DeleteSelectedPhases: "Delete Selected",
  ClearClipboard: "Clear Clipboard",
  
  // Phase Copy/Paste Tooltips
  SelectAllTooltip: "Select all phases for copying or deleting",
  CopyPhasesTooltip: "Copy selected phases to clipboard",
  PastePhasesTooltip: "Paste phases from clipboard",
  DeleteSelectedPhasesTooltip: "Permanently delete selected phases",
  ClearClipboardTooltip: "Clear clipboard to prevent accidental pasting",

  // Green Wave / Sync Groups
  GreenWave: "Green Wave",
  GreenWaveButton: "Green Wave",
  SyncGroup: "Sync Group",
  NoSyncGroup: "No Group",
  CreateNewGroup: "Create New Group",
  CycleOffset: "Cycle Offset",
  UseSyncedCycle: "Enable Sync",
  TotalCycleDuration: "Total Cycle",
  BaseCycleDuration: "Base Cycle",
  IntersectionsInGroup: "Intersections",
  NewGroupName: "New Group",
  DeleteGroup: "Delete Group",
  RenameGroup: "Rename",
  OpenGreenWavePanel: "Open Green Wave",
  GreenWavePanelActive: "Green Wave Active",
  
  // Phase Mode
  PhaseMode: "Phase Mode",
  LegacyMode: "Standard (Priority)",
  LegacyModeHint: "Next phase based on traffic demand",
  LegacyModeTooltip: "Phases switch based on priority - waiting vehicles and pedestrians determine the next phase. Default game behavior.",
  SequentialMode: "Sequential (Order)",
  SequentialModeHint: "Phases 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Phases run in order: 1 → 2 → 3 → 4 → 1... Fixed, predictable sequence. Required for Green Wave.",
  GreenWaveForcesSequential: "Green Wave requires sequential mode",
  
  SyncSettings: "Sync Settings",
  SyncPhase: "Sync Phase",
  SyncPhaseTooltip: "Select which phase to synchronize. Useful for turn lanes.",
  OffsetCalculator: "Offset Calculator",
  Distance: "Distance",
  Speed: "Speed",
  RecommendedOffset: "Recommended",
  Apply: "Apply",
  OwnCycle: "Own Cycle",
  GroupBase: "Group Base",
  AutoFactor: "Auto Factor",
  AutoFactorTooltip: "Ratio between own cycle and group base. Different cycle lengths are automatically scaled.",
  Intersections: "Intersections",
  NoGroupsYet: "No groups created yet",
  Information: "Information",
  
  // Green Wave Tooltips
  GreenWaveTooltip: "Synchronize multiple intersections for a green wave effect",
  GreenWaveTooltipActive: "Synchronize multiple intersections along a road so vehicles can pass through without stopping during a green wave.",
  GreenWaveTooltipDisabled: "Green Wave is only available when 'Custom Phases' is enabled for this intersection. Select 'Custom Phases' first.",
  SyncGroupTooltip: "Select a sync group for this intersection",
  CycleOffsetTooltip: "Time offset in seconds from the group timer. Different offsets create the green wave.",
  UseSyncedCycleTooltip: "Enables synchronization with the selected group",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Intersection",
  GWP_TabGroups: "Groups",
  GWP_TabDashboard: "Dashboard",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Synchronization active",
  GWP_NotSynced: "Not synchronized",

  // Green Wave Panel - Labels
  GWP_NodeId: "Node ID (Intersection)",
  GWP_Group: "Group",
  GWP_Offset: "Offset",
  GWP_AssignSyncGroup: "Assign Sync Group",
  GWP_NoGroupSelected: "No group selected",
  GWP_NoGroup: "No Group",
  GWP_NewGroup: "+ New Group",
  GWP_Rename: "Rename",
  GWP_EnableSync: "Enable Sync",
  GWP_CycleOffset: "Cycle Offset",
  GWP_Tempo: "Speed",
  GWP_Recommended: "Recommended:",
  GWP_GameTime: "Game",
  GWP_RealTime: "Real",
  GWP_PhaseHint: "Phase #1 should be the main direction for the Green Wave!",
  GWP_AutoSave: "Changes are saved automatically",
  GWP_SelectIntersection: "Please select an intersection.",
  GWP_SearchGroups: "Search groups...",
  GWP_NoMatches: "No matches for",
  GWP_RemoveFromGroup: "Remove from Group",
  GWP_DeleteGroup: "Delete Group",
  GWP_NoIntersections: "No intersections",
  GWP_GroupsHint: "Groups without intersections can be deleted. Add intersections in the 'Intersection' tab.",
  GWP_SelectGroupHint: "Select a group in the 'Intersection' tab to see details.",
  GWP_AddIntersectionsHint: "This group has no intersections yet. Go to the 'Intersection' tab and add intersections!",
  GWP_RemovedFromGroup: "Removed from group",
  GWP_AddedToGroup: "Added to",
  GWP_SyncEnabled: "Sync enabled!",
  GWP_SyncDisabled: "Sync disabled",
  GWP_NewGroupCreated: "New group created!",
  GWP_GroupRenamed: "Group renamed to",
  GWP_GroupDeleted: "Group deleted",
  GWP_IntersectionRemoved: "Intersection removed from group",
  GWP_OffsetSet: "Offset set to",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Enables synchronization of this intersection with the group.",
  GWP_TT_SyncPhase: "Select which phase to synchronize. Phase #1 should be the main direction (Green Wave).",
  GWP_TT_CycleOffset: "Time offset in seconds from the group base cycle.",
  GWP_TT_Distance: "Distance to the previous intersection in meters.",
  GWP_TT_Speed: "Traffic speed on the road.",
  GWP_TT_OwnCycle: "Total duration of a traffic light cycle for this intersection in game time.",
  GWP_TT_GroupBase: "Base cycle of the group in game time.",
  GWP_TT_Intersections: "Number of intersections in this group.",
  GWP_MoveUp: "Move up",
  GWP_MoveDown: "Move down",
  GWP_ManageGroups: "Manage Sync Groups",
};
