export default {
  TrafficSignal: "Semáforo",
  ModDefault: "Por defecto",
  Vanilla: "Vanilla",
  SplitPhasing: "Fase dividida",
  ProtectedRightTurns: "Giros a la derecha protegidos",
  ProtectedLeftTurns: "Giros a la izquierda protegidos",
  Options: "Opciones",
  ExclusivePedestrianPhase: "Fase peatonal exclusiva",
  LaneDirectionTool: "Herramienta de dirección de carril (Experimental)",
  
  // Buttons
  Add: "Añadir fase",
  Back: "Volver",
  ManualControl: "Control manual",
  CustomPhase: "Fase personalizada",
  CustomPhaseEditor: "Editar fases personalizadas",
  SelectFunction: "Seleccionar función",
  SelectFunctionDescription: "Elige una función para configurar tu red de tráfico.",
  EditIntersectionPhases: "Editar fases de intersección",
  IntersectionMonitor: "Monitor de intersección",
  DashboardComingSoon: "Próximamente...",
  
  Close: "Cerrar",
  Open: "Abrir",
  Reset: "Reiniciar",
  Save: "Guardar",
  PleaseSave: "Por favor guarda los cambios antes de seleccionar otra intersección.",
  PleaseSelectJunction: "Por favor selecciona una intersección",
  GiveWayToOncomingVehicles: "Ceder el paso a vehículos en sentido contrario",
  CustomPedestrianDurationMultiplier: "Duración de fase peatonal",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Permitir girar en rojo",
  CanaryBuildWarning: "Atención: estás usando una versión canary que puede contener errores. Esta versión es solo para pruebas. NO usar para juego normal.",
  LdtMigrationNotice: "Lane Direction Tool ha sido reemplazado por el mod Traffic de krzychu124. Por favor instala el mod Traffic para transferir tu configuración automáticamente.",
  LdtRetirementNotice: "Lane Direction Tool ha sido reemplazado por el mod Traffic de krzychu124. Gracias por usar LDT.",
  
  // Custom Phase Options
  PrioritiseTrack: "Priorizar vehículos",
  PrioritisePublicCar: "Priorizar transporte público",
  PrioritisePedestrian: "Priorizar peatones",
  PrioritiseBicycle: "Priorizar ciclistas",
  
  // Custom Phase Options - Tooltips
  PrioritiseTrackTooltip: "Da prioridad a los carriles de vehículos normales (coches, camiones) durante esta fase",
  PrioritisePublicCarTooltip: "Da prioridad a los carriles de transporte público (autobuses, tranvías) durante esta fase",
  PrioritisePedestrianTooltip: "Da prioridad a los pasos de peatones durante esta fase",
  PrioritiseBicycleTooltip: "Da prioridad a los carriles bici durante esta fase",
  
  // Custom Phase Adjustments
  Adjustments: "Ajustes",
  MinimumDuration: "Duración mín.",
  MaximumDuration: "Duración máx.",
  TargetDurationMultiplier: "Duración objetivo",
  LaneOccupiedMultiplier: "Ocupación de carriles",
  IntervalExponent: "Exponente de intervalo",
  
  // Custom Phase Adjustments - Tooltips
  MinimumDurationTooltip: "Duración mínima del verde. El semáforo permanece verde al menos este tiempo, aunque haya poco tráfico.",
  MaximumDurationTooltip: "Duración máxima del verde. Después de este tiempo, el semáforo cambia aunque haya tráfico esperando.",
  TargetDurationMultiplierTooltip: "Afecta la duración de la fase verde. 1x = Normal, 2x = Doble duración con tráfico, 0.5x = Más corto.",
  LaneOccupiedMultiplierTooltip: "Controla cuánto aumentan la prioridad los carriles llenos. Mayor = Los atascos se resuelven más rápido.",
  IntervalExponentTooltip: "Configuración de equidad. Mayor = Las fases que esperaron más tiempo tienen más prioridad.",
  
  // Custom Phase Statistics
  Statistics: "Estadísticas",
  Timer: "Temporizador",
  Priority: "Prioridad",
  LastRun: "Último ciclo",
  CarFlow: "Flujo de vehículos",
  LanesOccupied: "Carriles ocupados",
  WeightedWaiting: "Espera ponderada",
  
  // Custom Phase Statistics - Tooltips
  TimerTooltip: "Temporizador actual / Duración objetivo",
  PriorityTooltip: "Valor de prioridad actual de esta fase",
  LastRunTooltip: "Número de turnos desde que esta fase se ejecutó por última vez",
  CarFlowTooltip: "Flujo actual de vehículos en esta fase",
  LanesOccupiedTooltip: "Número de carriles ocupados (vehículos, transporte, vías, peatones)",
  WeightedWaitingTooltip: "Tiempo de espera ponderado de vehículos en esta fase",
  
  // Custom Phase Buttons
  EndPhasePrematurely: "Terminar fase ahora",
  PhaseEndRequested: "Fin de fase solicitado",
  // Phase Copy/Paste Feature
  SelectAll: "Seleccionar todo",
  DeselectAll: "Deseleccionar todo",
  CopyPhases: "Copiar fases",
  PastePhases: "Pegar fases",
  DeleteSelectedPhases: "Eliminar seleccionadas",
  ClearClipboard: "Vaciar portapapeles",
  
  // Phase Copy/Paste Tooltips
  SelectAllTooltip: "Seleccionar todas las fases para copiar o eliminar",
  CopyPhasesTooltip: "Copiar fases seleccionadas al portapapeles",
  PastePhasesTooltip: "Pegar fases desde el portapapeles",
  DeleteSelectedPhasesTooltip: "Eliminar permanentemente las fases seleccionadas",
  ClearClipboardTooltip: "Vaciar portapapeles para evitar pegados accidentales",

  // Green Wave / Sync Groups
  GreenWave: "Ola Verde",
  GreenWaveButton: "Ola Verde",
  SyncGroup: "Grupo de Sincronización",
  NoSyncGroup: "Sin Grupo",
  CreateNewGroup: "Crear Nuevo Grupo",
  CycleOffset: "Desfase de Ciclo",
  UseSyncedCycle: "Activar Sincronización",
  TotalCycleDuration: "Duración Total del Ciclo",
  BaseCycleDuration: "Ciclo Base",
  IntersectionsInGroup: "Intersecciones",
  NewGroupName: "Nuevo Grupo",
  DeleteGroup: "Eliminar Grupo",
  RenameGroup: "Renombrar",
  OpenGreenWavePanel: "Abrir Ola Verde",
  GreenWavePanelActive: "Ola Verde Activa",
  
  // Phase Mode
  PhaseMode: "Modo de Fase",
  LegacyMode: "Estándar (Prioridad)",
  LegacyModeHint: "Siguiente fase según demanda de tráfico",
  LegacyModeTooltip: "Las fases cambian según prioridad - vehículos y peatones esperando determinan la siguiente fase. Comportamiento predeterminado del juego.",
  SequentialMode: "Secuencial (Orden)",
  SequentialModeHint: "Fases 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Las fases se ejecutan en orden: 1 → 2 → 3 → 4 → 1... Secuencia fija y predecible. Requerido para Ola Verde.",
  GreenWaveForcesSequential: "La Ola Verde requiere modo secuencial",
  
  SyncSettings: "Config. de Sincr.",
  SyncPhase: "Fase de Sincr.",
  SyncPhaseTooltip: "Seleccione qué fase sincronizar. Útil para carriles de giro.",
  OffsetCalculator: "Calculadora de Desfase",
  Distance: "Distancia",
  Speed: "Velocidad",
  RecommendedOffset: "Recomendado",
  Apply: "Aplicar",
  OwnCycle: "Ciclo Propio",
  GroupBase: "Base del Grupo",
  AutoFactor: "Factor Automático",
  AutoFactorTooltip: "Proporción entre el ciclo propio y la base del grupo. Los diferentes ciclos se escalan automáticamente.",
  Intersections: "Intersecciones",
  NoGroupsYet: "Aún no se han creado grupos",
  Information: "Información",
  
  // Green Wave Tooltips
  GreenWaveTooltip: "Sincroniza múltiples intersecciones para un efecto de ola verde",
  GreenWaveTooltipActive: "Sincroniza múltiples intersecciones a lo largo de una carretera para que los vehículos puedan pasar sin detenerse durante una ola verde.",
  GreenWaveTooltipDisabled: "La Ola Verde solo está disponible cuando 'Fases Personalizadas' está habilitado para esta intersección. Selecciona primero 'Fases Personalizadas'.",
  SyncGroupTooltip: "Selecciona un grupo de sincronización para esta intersección",
  CycleOffsetTooltip: "Desfase en segundos del temporizador del grupo. Diferentes desfases crean la ola verde.",
  UseSyncedCycleTooltip: "Activa la sincronización con el grupo seleccionado",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Intersección",
  GWP_TabGroups: "Grupos",
  GWP_TabDashboard: "Panel",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Sincronización activa",
  GWP_NotSynced: "No sincronizado",

  // Green Wave Panel - Labels
  GWP_NodeId: "ID de Nodo (Intersección)",
  GWP_Group: "Grupo",
  GWP_Offset: "Desfase",
  GWP_AssignSyncGroup: "Asignar Grupo de Sinc.",
  GWP_NoGroupSelected: "Sin grupo seleccionado",
  GWP_NoGroup: "Sin Grupo",
  GWP_NewGroup: "+ Nuevo Grupo",
  GWP_Rename: "Renombrar",
  GWP_EnableSync: "Activar Sincr.",
  GWP_CycleOffset: "Desfase de Ciclo",
  GWP_Tempo: "Velocidad",
  GWP_Recommended: "Recomendado:",
  GWP_GameTime: "Juego",
  GWP_RealTime: "Real",
  GWP_PhaseHint: "¡La Fase #1 debe ser la dirección principal de la Ola Verde!",
  GWP_AutoSave: "Los cambios se guardan automáticamente",
  GWP_SelectIntersection: "Por favor seleccione una intersección.",
  GWP_SearchGroups: "Buscar grupos...",
  GWP_NoMatches: "Sin coincidencias para",
  GWP_RemoveFromGroup: "Eliminar del Grupo",
  GWP_DeleteGroup: "Eliminar Grupo",
  GWP_NoIntersections: "Intersecciones",
  GWP_GroupsHint: "Los grupos sin intersecciones pueden eliminarse. Añada intersecciones en la pestaña 'Intersección'.",
  GWP_SelectGroupHint: "Seleccione un grupo en la pestaña 'Intersección' para ver detalles.",
  GWP_AddIntersectionsHint: "Este grupo aún no tiene intersecciones. ¡Vaya a la pestaña 'Intersección' y añada intersecciones!",
  GWP_RemovedFromGroup: "Eliminado del grupo",
  GWP_AddedToGroup: "Añadido a",
  GWP_SyncEnabled: "¡Sincronización activada!",
  GWP_SyncDisabled: "Sincronización desactivada",
  GWP_NewGroupCreated: "¡Nuevo grupo creado!",
  GWP_GroupRenamed: "Grupo renombrado a",
  GWP_GroupDeleted: "Grupo eliminado",
  GWP_IntersectionRemoved: "Intersección eliminada del grupo",
  GWP_OffsetSet: "Desfase establecido en",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Activa la sincronización de esta intersección con el grupo.",
  GWP_TT_SyncPhase: "Fase de Sincr.",
  GWP_TT_CycleOffset: "Desfase temporal en segundos desde el ciclo base del grupo.",
  GWP_TT_Distance: "Distancia",
  GWP_TT_Speed: "Velocidad",
  GWP_TT_OwnCycle: "Ciclo Propio",
  GWP_TT_GroupBase: "Ciclo base del grupo (tiempo de juego).",
  GWP_TT_Intersections: "Intersecciones",
  GWP_MoveUp: "Mover arriba",
  GWP_MoveDown: "Mover abajo",
  GWP_ManageGroups: "Gestionar Grupos de Sinc.",
  GWP_CreateNewGroup: "+ Crear Nuevo Grupo",
  GWP_DB_Intersection: "Intersección",
  GWP_DB_Reference: "REFERENCIA",
  GWP_DB_Phases: "Fases",
  GWP_DB_Green: "VERDE",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "OFF",
  GWP_DB_SyncWaiting: "Sync activo - esperando",
  GWP_DB_GreenWaveActive: "¡Ola Verde activa!",
  GWP_DB_ReadyToSwitch: "Listo para cambiar",
  GWP_DB_Offset: "DESFASE",
  GWP_DB_Cycle: "CICLO",
  GWP_DB_Roads: "CALLES",
  GWP_DB_Lanes: "CARRILES",
  GWP_DB_Pedestrians: "PEAT.",
  GWP_DB_OffsetDelta: "Desfase",
  GWP_DB_BaseCycle: "Ciclo Base",
  GWP_DB_GreenWaveLabel: "Ola Verde",
  GWP_DB_SyncActiveLabel: "Sync Activo",
  GWP_DB_ReorderHint: "Usa las flechas para ajustar el orden. La primera intersección es la referencia (Desfase 0).",
  GWP_DB_PhaseProgressTooltip: "Izquierda: Duración mínima. Parpadeando: Fase lista para cambiar.",
  GWP_DB_MinDurationTooltip: "Al 50% se alcanza la duración mínima. La fase puede cambiar en cualquier momento.",
  GWP_DB_PhaseXofY: "Fase {0} de {1}",

  // V147: Traffic Summary
  TrafficSummary: "Resumen de Tráfico",
  VehiclesPerHour: "Ø Flujo",
  VehiclesPerMinute: "Vehículos/Min",
  Approaches: "Accesos",
  IncomingLanes: "Carriles Entrantes",
  IncomingLanesTooltip: "Carriles físicos que entran en la intersección.",
  OccupiedLanes: "Carriles Ocupados",
  OccupiedLanesTooltip: "Número de carriles ocupados con vehículos esperando.",
  OccupiedPedestrianLanes: "Carriles Peat. Ocup.",
  TrafficFlowLow: "Tráfico Ligero",
  TrafficFlowMedium: "Tráfico Moderado",
  TrafficFlowHigh: "Tráfico Intenso",
  WaitingVehicles: "Vehículos Esperando",
  WaitingVehiclesTooltip: "Número actual de vehículos esperando (promedio).",
  PeakHour: "Pico (24h)",
  PeakHourTooltip: "Hora con mayor volumen en las últimas 24 horas.",
  MaxVPH: "Máx V/h (24h)",
  MaxVPHTooltip: "Mayor vehículos/hora en las últimas 24 horas.",
  VPH_InfoEstimate: "Estimación basada en carriles y ocupación.",
  VPH_InfoRealData: "Promedio móvil del conteo real de vehículos.",
  ChartDisabledTooltip: "Activa 'Fase Personalizada' para recopilar datos",
  ChartCollectingTooltip: "Recopilando datos... Primeros valores en ~30 min",
  ChartActiveTooltip: "Historial de tráfico de 24 horas",
  CustomPhaseRequiredTooltip: "Requiere que 'Fases Personalizadas' esté activado para esta intersección.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "¿Eliminar fase?",
};
