export default {
  TrafficSignal: "Feu de circulation",
  ModDefault: "Par défaut",
  Vanilla: "Vanilla",
  SplitPhasing: "Phase séparée",
  ProtectedRightTurns: "Virages à droite protégés",
  ProtectedLeftTurns: "Virages à gauche protégés",
  Options: "Options",
  ExclusivePedestrianPhase: "Phase piétonne exclusive",
  LaneDirectionTool: "Outil de direction de voie (Expérimental)",
  
  Add: "Ajouter une phase",
  Back: "Retour",
  ManualControl: "Contrôle manuel",
  CustomPhase: "Phase personnalisée",
  CustomPhaseEditor: "Éditer les phases personnalisées",
  SelectFunction: "Sélectionner une fonction",
  SelectFunctionDescription: "Choisissez une fonction pour configurer votre réseau de trafic.",
  EditIntersectionPhases: "Éditer les phases d'intersection",
  IntersectionMonitor: "Moniteur d'intersection",
  DashboardComingSoon: "Bientôt disponible...",
  
  Close: "Fermer",
  Open: "Ouvrir",
  Reset: "Réinitialiser",
  Save: "Sauvegarder",
  PleaseSave: "Veuillez sauvegarder les modifications avant de sélectionner une autre intersection.",
  PleaseSelectJunction: "Veuillez sélectionner une intersection",
  GiveWayToOncomingVehicles: "Céder le passage aux véhicules venant en face",
  CustomPedestrianDurationMultiplier: "Durée de la phase piétonne",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Autoriser le virage au rouge",
  CanaryBuildWarning: "Attention: vous utilisez une version canary qui peut contenir des bugs. Cette version est uniquement pour les tests. NE PAS utiliser pour le jeu normal.",
  LdtMigrationNotice: "Lane Direction Tool a été remplacé par le mod Traffic de krzychu124. Veuillez installer le mod Traffic pour transférer automatiquement vos paramètres.",
  LdtRetirementNotice: "Lane Direction Tool a été remplacé par le mod Traffic de krzychu124. Merci d'avoir utilisé LDT.",
  
  PrioritiseTrack: "Prioriser les véhicules",
  PrioritisePublicCar: "Prioriser les transports publics",
  PrioritisePedestrian: "Prioriser les piétons",
  PrioritiseBicycle: "Prioriser les cyclistes",
  
  PrioritiseTrackTooltip: "Donne la priorité aux voies de véhicules normaux (voitures, camions) pendant cette phase",
  PrioritisePublicCarTooltip: "Donne la priorité aux voies de transport public (bus, tramways) pendant cette phase",
  PrioritisePedestrianTooltip: "Donne la priorité aux passages piétons pendant cette phase",
  PrioritiseBicycleTooltip: "Donne la priorité aux pistes cyclables pendant cette phase",
  
  Adjustments: "Ajustements",
  MinimumDuration: "Durée min.",
  MaximumDuration: "Durée max.",
  TargetDurationMultiplier: "Durée cible",
  LaneOccupiedMultiplier: "Occupation des voies",
  IntervalExponent: "Exposant d'intervalle",
  
  MinimumDurationTooltip: "Durée minimale du feu vert. Le feu reste vert au moins ce temps, même avec peu de trafic.",
  MaximumDurationTooltip: "Durée maximale du feu vert. Après ce temps, le feu change même si du trafic attend.",
  TargetDurationMultiplierTooltip: "Affecte la durée de la phase verte. 1x = Normal, 2x = Double durée avec trafic, 0.5x = Plus court.",
  LaneOccupiedMultiplierTooltip: "Contrôle l'augmentation de priorité des voies pleines. Plus élevé = Les embouteillages se résolvent plus vite.",
  IntervalExponentTooltip: "Réglage d'équité. Plus élevé = Les phases qui ont attendu plus longtemps ont plus de priorité.",
  
  Statistics: "Statistiques",
  Timer: "Minuteur",
  Priority: "Priorité",
  LastRun: "Dernier cycle",
  CarFlow: "Flux de véhicules",
  LanesOccupied: "Voies occupées",
  WeightedWaiting: "Attente pondérée",
  
  TimerTooltip: "Minuteur actuel / Durée cible",
  PriorityTooltip: "Valeur de priorité actuelle de cette phase",
  LastRunTooltip: "Nombre de tours depuis la dernière exécution de cette phase",
  CarFlowTooltip: "Flux actuel de véhicules dans cette phase",
  LanesOccupiedTooltip: "Nombre de voies occupées (véhicules, transports, rails, piétons)",
  WeightedWaitingTooltip: "Temps d'attente pondéré des véhicules à cette phase",
  
  EndPhasePrematurely: "Terminer la phase maintenant",
  PhaseEndRequested: "Fin de phase demandée",
  SelectAll: "Tout sélectionner",
  DeselectAll: "Tout désélectionner",
  CopyPhases: "Copier les phases",
  PastePhases: "Coller les phases",
  DeleteSelectedPhases: "Supprimer les sélectionnées",
  ClearClipboard: "Vider le presse-papiers",
  
  SelectAllTooltip: "Sélectionner toutes les phases pour copier ou supprimer",
  CopyPhasesTooltip: "Copier les phases sélectionnées dans le presse-papiers",
  PastePhasesTooltip: "Coller les phases depuis le presse-papiers",
  DeleteSelectedPhasesTooltip: "Supprimer définitivement les phases sélectionnées",
  ClearClipboardTooltip: "Vider le presse-papiers pour éviter les collages accidentels",

  GreenWave: "Onde Verte",
  GreenWaveButton: "Onde Verte",
  SyncGroup: "Groupe de Synchronisation",
  NoSyncGroup: "Aucun Groupe",
  CreateNewGroup: "Créer un Nouveau Groupe",
  CycleOffset: "Décalage de Cycle",
  UseSyncedCycle: "Activer la Synchronisation",
  TotalCycleDuration: "Durée Totale du Cycle",
  BaseCycleDuration: "Cycle de Base",
  IntersectionsInGroup: "Intersections",
  NewGroupName: "Nouveau Groupe",
  DeleteGroup: "Supprimer le Groupe",
  RenameGroup: "Renommer",
  OpenGreenWavePanel: "Ouvrir l'Onde Verte",
  GreenWavePanelActive: "Onde Verte Active",
  
  PhaseMode: "Mode de Phase",
  LegacyMode: "Standard (Priorité)",
  LegacyModeHint: "Phase suivante selon la demande de trafic",
  LegacyModeTooltip: "Les phases changent selon la priorité - les véhicules et piétons en attente déterminent la phase suivante. Comportement par défaut du jeu.",
  SequentialMode: "Séquentiel (Ordre)",
  SequentialModeHint: "Phases 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Les phases s'exécutent dans l'ordre: 1 → 2 → 3 → 4 → 1... Séquence fixe et prévisible. Requis pour l'Onde Verte.",
  GreenWaveForcesSequential: "L'Onde Verte nécessite le mode séquentiel",
  
  SyncSettings: "Param. de Sync.",
  SyncPhase: "Phase de Sync.",
  SyncPhaseTooltip: "Sélectionnez quelle phase synchroniser. Utile pour les voies de virage.",
  OffsetCalculator: "Calculateur de Décalage",
  Distance: "Distance",
  Speed: "Vitesse",
  RecommendedOffset: "Recommandé",
  Apply: "Appliquer",
  OwnCycle: "Cycle Propre",
  GroupBase: "Base du Groupe",
  AutoFactor: "Facteur Auto",
  AutoFactorTooltip: "Rapport entre le cycle propre et la base du groupe. Les différents cycles sont automatiquement mis à l'échelle.",
  Intersections: "Intersections",
  NoGroupsYet: "Aucun groupe créé pour l'instant",
  Information: "Information",
  
  GreenWaveTooltip: "Synchroniser plusieurs intersections pour un effet d'onde verte",
  GreenWaveTooltipActive: "Synchroniser plusieurs intersections le long d'une route pour que les véhicules puissent passer sans s'arrêter pendant une onde verte.",
  GreenWaveTooltipDisabled: "L'Onde Verte n'est disponible que lorsque 'Phases Personnalisées' est activé pour cette intersection. Sélectionnez d'abord 'Phases Personnalisées'.",
  SyncGroupTooltip: "Sélectionner un groupe de synchronisation pour cette intersection",
  CycleOffsetTooltip: "Décalage en secondes par rapport au minuteur du groupe. Différents décalages créent l'onde verte.",
  UseSyncedCycleTooltip: "Active la synchronisation avec le groupe sélectionné",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Intersection",
  GWP_TabGroups: "Groupes",
  GWP_TabDashboard: "Tableau",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Synchronisation active",
  GWP_NotSynced: "Non synchronisé",

  // Green Wave Panel - Labels
  GWP_NodeId: "ID du Nœud (Intersection)",
  GWP_Group: "Groupe",
  GWP_Offset: "Décalage",
  GWP_AssignSyncGroup: "Assigner Groupe de Sync.",
  GWP_NoGroupSelected: "Aucun groupe sélectionné",
  GWP_NoGroup: "Pas de Groupe",
  GWP_NewGroup: "+ Nouveau Groupe",
  GWP_Rename: "Renommer",
  GWP_EnableSync: "Activer Sync.",
  GWP_CycleOffset: "Décalage de Cycle",
  GWP_Tempo: "Vitesse",
  GWP_Recommended: "Recommandé :",
  GWP_GameTime: "Jeu",
  GWP_RealTime: "Réel",
  GWP_PhaseHint: "La Phase #1 doit être la direction principale de l'Onde Verte !",
  GWP_AutoSave: "Les modifications sont enregistrées automatiquement",
  GWP_SelectIntersection: "Veuillez sélectionner une intersection.",
  GWP_SearchGroups: "Rechercher groupes...",
  GWP_NoMatches: "Aucune correspondance pour",
  GWP_RemoveFromGroup: "Retirer du Groupe",
  GWP_DeleteGroup: "Supprimer Groupe",
  GWP_NoIntersections: "Intersections",
  GWP_GroupsHint: "Les groupes sans intersections peuvent être supprimés. Ajoutez des intersections dans l'onglet 'Intersection'.",
  GWP_SelectGroupHint: "Sélectionnez un groupe dans l'onglet 'Intersection' pour voir les détails.",
  GWP_AddIntersectionsHint: "Ce groupe n'a pas encore d'intersections. Allez dans l'onglet 'Intersection' et ajoutez-en !",
  GWP_RemovedFromGroup: "Retiré du groupe",
  GWP_AddedToGroup: "Ajouté à",
  GWP_SyncEnabled: "Synchronisation activée !",
  GWP_SyncDisabled: "Synchronisation désactivée",
  GWP_NewGroupCreated: "Nouveau groupe créé !",
  GWP_GroupRenamed: "Groupe renommé en",
  GWP_GroupDeleted: "Groupe supprimé",
  GWP_IntersectionRemoved: "Intersection retirée du groupe",
  GWP_OffsetSet: "Décalage défini à",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Active la synchronisation de cette intersection avec le groupe.",
  GWP_TT_SyncPhase: "Phase de Sync.",
  GWP_TT_CycleOffset: "Décalage temporel en secondes par rapport au cycle de base du groupe.",
  GWP_TT_Distance: "Distance",
  GWP_TT_Speed: "Vitesse",
  GWP_TT_OwnCycle: "Cycle Propre",
  GWP_TT_GroupBase: "Cycle de base du groupe (temps de jeu).",
  GWP_TT_Intersections: "Intersections",
  GWP_MoveUp: "Monter",
  GWP_MoveDown: "Descendre",
  GWP_ManageGroups: "Gérer Groupes de Sync.",
  GWP_CreateNewGroup: "+ Créer Nouveau Groupe",
  GWP_DB_Intersection: "Intersection",
  GWP_DB_Reference: "RÉFÉRENCE",
  GWP_DB_Phases: "Phases",
  GWP_DB_Green: "VERT",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "OFF",
  GWP_DB_SyncWaiting: "Sync actif - en attente",
  GWP_DB_GreenWaveActive: "Onde Verte active!",
  GWP_DB_ReadyToSwitch: "Prêt à changer",
  GWP_DB_Offset: "DÉCALAGE",
  GWP_DB_Cycle: "CYCLE",
  GWP_DB_Roads: "ROUTES",
  GWP_DB_Lanes: "VOIES",
  GWP_DB_Pedestrians: "PIÉT.",
  GWP_DB_OffsetDelta: "Décalage",
  GWP_DB_BaseCycle: "Cycle de Base",
  GWP_DB_GreenWaveLabel: "Onde Verte",
  GWP_DB_SyncActiveLabel: "Sync Actif",
  GWP_DB_ReorderHint: "Utilisez les flèches pour ajuster l'ordre. La première intersection est la référence (Décalage 0).",
  GWP_DB_PhaseProgressTooltip: "Gauche: Durée minimum. Clignotant: Phase prête à changer.",
  GWP_DB_MinDurationTooltip: "À 50% la durée minimum est atteinte. La phase peut changer à tout moment.",
  GWP_DB_PhaseXofY: "Phase {0} sur {1}",

  // V147: Traffic Summary
  TrafficSummary: "Aperçu du Trafic",
  VehiclesPerHour: "Ø Débit",
  VehiclesPerMinute: "Véhicules/Min",
  Approaches: "Approches",
  IncomingLanes: "Voies Entrantes",
  IncomingLanesTooltip: "Voies physiques entrant dans l'intersection.",
  OccupiedLanes: "Voies Occupées",
  OccupiedLanesTooltip: "Nombre de voies occupées avec des véhicules en attente.",
  OccupiedPedestrianLanes: "Voies Piét. Occ.",
  TrafficFlowLow: "Trafic Faible",
  TrafficFlowMedium: "Trafic Modéré",
  TrafficFlowHigh: "Trafic Dense",
  WaitingVehicles: "Véhicules en Attente",
  WaitingVehiclesTooltip: "Nombre actuel de véhicules en attente (moyenne).",
  PeakHour: "Pointe (24h)",
  PeakHourTooltip: "Heure avec le plus grand volume dans les 24 dernières heures.",
  MaxVPH: "Max V/h (24h)",
  MaxVPHTooltip: "Plus grand véhicules/heure dans les 24 dernières heures.",
  VPH_InfoEstimate: "Estimation basée sur les voies et l'occupation.",
  VPH_InfoRealData: "Moyenne mobile du comptage réel de véhicules.",
  ChartDisabledTooltip: "Activez 'Phase Personnalisée' pour collecter des données",
  ChartCollectingTooltip: "Collecte de données... Premières valeurs dans ~30 min",
  ChartActiveTooltip: "Historique du trafic sur 24 heures",
  CustomPhaseRequiredTooltip: "Nécessite que 'Phases Personnalisées' soit activé pour cette intersection.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Supprimer la phase ?",
};
