export default {
  TrafficSignal: "Semaforo",
  ModDefault: "Predefinito",
  Vanilla: "Vanilla",
  SplitPhasing: "Fase divisa",
  ProtectedRightTurns: "Svolte a destra protette",
  ProtectedLeftTurns: "Svolte a sinistra protette",
  Options: "Opzioni",
  ExclusivePedestrianPhase: "Fase pedonale esclusiva",
  LaneDirectionTool: "Strumento direzione corsia (Sperimentale)",
  
  Add: "Aggiungi fase",
  Back: "Indietro",
  ManualControl: "Controllo manuale",
  CustomPhase: "Fase personalizzata",
  CustomPhaseEditor: "Modifica fasi personalizzate",
  SelectFunction: "Seleziona funzione",
  SelectFunctionDescription: "Scegli una funzione per configurare la tua rete di traffico.",
  EditIntersectionPhases: "Modifica fasi incrocio",
  IntersectionMonitor: "Monitor incrocio",
  DashboardComingSoon: "Prossimamente...",
  
  Close: "Chiudi",
  Open: "Apri",
  Reset: "Reimposta",
  Save: "Salva",
  PleaseSave: "Salva le modifiche prima di selezionare un altro incrocio.",
  PleaseSelectJunction: "Seleziona un incrocio",
  GiveWayToOncomingVehicles: "Dare la precedenza ai veicoli in arrivo",
  CustomPedestrianDurationMultiplier: "Durata fase pedonale",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Consenti svolta con rosso",
  CanaryBuildWarning: "Attenzione: stai usando una versione canary che potrebbe contenere bug. Questa versione è solo per test. NON usare per il gioco normale.",
  LdtMigrationNotice: "Lane Direction Tool è stato sostituito dal mod Traffic di krzychu124. Installa il mod Traffic per trasferire automaticamente le tue impostazioni.",
  LdtRetirementNotice: "Lane Direction Tool è stato sostituito dal mod Traffic di krzychu124. Grazie per aver usato LDT.",
  
  PrioritiseTrack: "Priorità veicoli",
  PrioritisePublicCar: "Priorità trasporto pubblico",
  PrioritisePedestrian: "Priorità pedoni",
  PrioritiseBicycle: "Priorità ciclisti",
  
  PrioritiseTrackTooltip: "Dà priorità alle corsie dei veicoli normali (auto, camion) durante questa fase",
  PrioritisePublicCarTooltip: "Dà priorità alle corsie del trasporto pubblico (autobus, tram) durante questa fase",
  PrioritisePedestrianTooltip: "Dà priorità ai passaggi pedonali durante questa fase",
  PrioritiseBicycleTooltip: "Dà priorità alle piste ciclabili durante questa fase",
  
  Adjustments: "Regolazioni",
  MinimumDuration: "Durata min.",
  MaximumDuration: "Durata max.",
  TargetDurationMultiplier: "Durata obiettivo",
  LaneOccupiedMultiplier: "Occupazione corsie",
  IntervalExponent: "Esponente intervallo",
  
  MinimumDurationTooltip: "Durata minima del verde. Il semaforo resta verde almeno questo tempo, anche con poco traffico.",
  MaximumDurationTooltip: "Durata massima del verde. Dopo questo tempo, il semaforo cambia anche se c'è traffico in attesa.",
  TargetDurationMultiplierTooltip: "Influenza la durata della fase verde. 1x = Normale, 2x = Doppia durata con traffico, 0.5x = Più corto.",
  LaneOccupiedMultiplierTooltip: "Controlla quanto le corsie piene aumentano la priorità. Più alto = Gli ingorghi si risolvono più velocemente.",
  IntervalExponentTooltip: "Impostazione di equità. Più alto = Le fasi che hanno aspettato di più hanno più priorità.",
  
  Statistics: "Statistiche",
  Timer: "Timer",
  Priority: "Priorità",
  LastRun: "Ultimo ciclo",
  CarFlow: "Flusso veicoli",
  LanesOccupied: "Corsie occupate",
  WeightedWaiting: "Attesa ponderata",
  
  TimerTooltip: "Timer attuale / Durata obiettivo",
  PriorityTooltip: "Valore di priorità attuale di questa fase",
  LastRunTooltip: "Numero di turni dall'ultima esecuzione di questa fase",
  CarFlowTooltip: "Flusso attuale di veicoli in questa fase",
  LanesOccupiedTooltip: "Numero di corsie occupate (veicoli, trasporti, binari, pedoni)",
  WeightedWaitingTooltip: "Tempo di attesa ponderato dei veicoli in questa fase",
  
  EndPhasePrematurely: "Termina fase ora",
  PhaseEndRequested: "Fine fase richiesta",
  SelectAll: "Seleziona tutto",
  DeselectAll: "Deseleziona tutto",
  CopyPhases: "Copia fasi",
  PastePhases: "Incolla fasi",
  DeleteSelectedPhases: "Elimina selezionate",
  ClearClipboard: "Svuota appunti",
  
  SelectAllTooltip: "Seleziona tutte le fasi per copiare o eliminare",
  CopyPhasesTooltip: "Copia le fasi selezionate negli appunti",
  PastePhasesTooltip: "Incolla le fasi dagli appunti",
  DeleteSelectedPhasesTooltip: "Elimina definitivamente le fasi selezionate",
  ClearClipboardTooltip: "Svuota gli appunti per evitare incollaggi accidentali",

  GreenWave: "Onda Verde",
  GreenWaveButton: "Onda Verde",
  SyncGroup: "Gruppo di Sincronizzazione",
  NoSyncGroup: "Nessun Gruppo",
  CreateNewGroup: "Crea Nuovo Gruppo",
  CycleOffset: "Offset del Ciclo",
  UseSyncedCycle: "Attiva Sincronizzazione",
  TotalCycleDuration: "Durata Totale del Ciclo",
  BaseCycleDuration: "Ciclo Base",
  IntersectionsInGroup: "Incroci",
  NewGroupName: "Nuovo Gruppo",
  DeleteGroup: "Elimina Gruppo",
  RenameGroup: "Rinomina",
  OpenGreenWavePanel: "Apri Onda Verde",
  GreenWavePanelActive: "Onda Verde Attiva",
  
  PhaseMode: "Modalità Fase",
  LegacyMode: "Standard (Priorità)",
  LegacyModeHint: "Prossima fase in base alla domanda di traffico",
  LegacyModeTooltip: "Le fasi cambiano in base alla priorità - veicoli e pedoni in attesa determinano la prossima fase. Comportamento predefinito del gioco.",
  SequentialMode: "Sequenziale (Ordine)",
  SequentialModeHint: "Fasi 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Le fasi si eseguono in ordine: 1 → 2 → 3 → 4 → 1... Sequenza fissa e prevedibile. Richiesto per l'Onda Verde.",
  GreenWaveForcesSequential: "L'Onda Verde richiede la modalità sequenziale",
  
  SyncSettings: "Impost. di Sincr.",
  SyncPhase: "Fase di Sincr.",
  SyncPhaseTooltip: "Seleziona quale fase sincronizzare. Utile per le corsie di svolta.",
  OffsetCalculator: "Calcolatore di Offset",
  Distance: "Distanza",
  Speed: "Velocità",
  RecommendedOffset: "Raccomandato",
  Apply: "Applica",
  OwnCycle: "Ciclo Proprio",
  GroupBase: "Base del Gruppo",
  AutoFactor: "Fattore Auto",
  AutoFactorTooltip: "Rapporto tra il ciclo proprio e la base del gruppo. I diversi cicli vengono scalati automaticamente.",
  Intersections: "Intersezioni",
  NoGroupsYet: "Nessun gruppo creato ancora",
  Information: "Informazioni",
  
  GreenWaveTooltip: "Sincronizza più incroci per un effetto onda verde",
  GreenWaveTooltipActive: "Sincronizza più incroci lungo una strada in modo che i veicoli possano passare senza fermarsi durante un'onda verde.",
  GreenWaveTooltipDisabled: "L'Onda Verde è disponibile solo quando 'Fasi Personalizzate' è abilitato per questo incrocio. Seleziona prima 'Fasi Personalizzate'.",
  SyncGroupTooltip: "Seleziona un gruppo di sincronizzazione per questo incrocio",
  CycleOffsetTooltip: "Offset in secondi dal timer del gruppo. Diversi offset creano l'onda verde.",
  UseSyncedCycleTooltip: "Attiva la sincronizzazione con il gruppo selezionato",


  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Intersezione",
  GWP_TabGroups: "Gruppi",
  GWP_TabDashboard: "Pannello",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Sincronizzazione attiva",
  GWP_NotSynced: "Non sincronizzato",

  // Green Wave Panel - Labels
  GWP_NodeId: "ID Nodo (Intersezione)",
  GWP_Group: "Gruppo",
  GWP_Offset: "Offset",
  GWP_AssignSyncGroup: "Assegna Gruppo di Sinc.",
  GWP_NoGroupSelected: "Nessun gruppo selezionato",
  GWP_NoGroup: "Nessun Gruppo",
  GWP_NewGroup: "+ Nuovo Gruppo",
  GWP_Rename: "Rinomina",
  GWP_EnableSync: "Attiva Sincr.",
  GWP_CycleOffset: "Offset di Ciclo",
  GWP_Tempo: "Velocità",
  GWP_Recommended: "Consigliato:",
  GWP_GameTime: "Gioco",
  GWP_RealTime: "Reale",
  GWP_PhaseHint: "La Fase #1 dovrebbe essere la direzione principale dell'Onda Verde!",
  GWP_AutoSave: "Le modifiche vengono salvate automaticamente",
  GWP_SelectIntersection: "Selezionare un'intersezione.",
  GWP_SearchGroups: "Cerca gruppi...",
  GWP_NoMatches: "Nessuna corrispondenza per",
  GWP_RemoveFromGroup: "Rimuovi dal Gruppo",
  GWP_DeleteGroup: "Elimina Gruppo",
  GWP_NoIntersections: "Intersezioni",
  GWP_GroupsHint: "I gruppi senza intersezioni possono essere eliminati. Aggiungi intersezioni nella scheda 'Intersezione'.",
  GWP_SelectGroupHint: "Seleziona un gruppo nella scheda 'Intersezione' per vedere i dettagli.",
  GWP_AddIntersectionsHint: "Questo gruppo non ha ancora intersezioni. Vai nella scheda 'Intersezione' e aggiungine!",
  GWP_RemovedFromGroup: "Rimosso dal gruppo",
  GWP_AddedToGroup: "Aggiunto a",
  GWP_SyncEnabled: "Sincronizzazione attivata!",
  GWP_SyncDisabled: "Sincronizzazione disattivata",
  GWP_NewGroupCreated: "Nuovo gruppo creato!",
  GWP_GroupRenamed: "Gruppo rinominato in",
  GWP_GroupDeleted: "Gruppo eliminato",
  GWP_IntersectionRemoved: "Intersezione rimossa dal gruppo",
  GWP_OffsetSet: "Offset impostato a",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Attiva la sincronizzazione di questa intersezione con il gruppo.",
  GWP_TT_SyncPhase: "Fase di Sincr.",
  GWP_TT_CycleOffset: "Offset temporale in secondi dal ciclo base del gruppo.",
  GWP_TT_Distance: "Distanza",
  GWP_TT_Speed: "Velocità",
  GWP_TT_OwnCycle: "Ciclo Proprio",
  GWP_TT_GroupBase: "Ciclo base del gruppo (tempo di gioco).",
  GWP_TT_Intersections: "Intersezioni",
  GWP_MoveUp: "Sposta su",
  GWP_MoveDown: "Sposta giù",
  GWP_ManageGroups: "Gestisci Gruppi di Sinc.",
  GWP_CreateNewGroup: "+ Crea Nuovo Gruppo",
  GWP_DB_Intersection: "Intersezione",
  GWP_DB_Reference: "RIFERIMENTO",
  GWP_DB_Phases: "Fasi",
  GWP_DB_Green: "VERDE",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "OFF",
  GWP_DB_SyncWaiting: "Sync attivo - in attesa",
  GWP_DB_GreenWaveActive: "Onda Verde attiva!",
  GWP_DB_ReadyToSwitch: "Pronto al cambio",
  GWP_DB_Offset: "OFFSET",
  GWP_DB_Cycle: "CICLO",
  GWP_DB_Roads: "STRADE",
  GWP_DB_Lanes: "CORSIE",
  GWP_DB_Pedestrians: "PED.",
  GWP_DB_OffsetDelta: "Offset",
  GWP_DB_BaseCycle: "Ciclo Base",
  GWP_DB_GreenWaveLabel: "Onda Verde",
  GWP_DB_SyncActiveLabel: "Sync Attivo",
  GWP_DB_ReorderHint: "Usa le frecce per regolare l'ordine. La prima intersezione è il riferimento (Offset 0).",
  GWP_DB_PhaseProgressTooltip: "Sinistra: Durata minima. Lampeggiante: Fase pronta al cambio.",
  GWP_DB_MinDurationTooltip: "Al 50% si raggiunge la durata minima. La fase può cambiare in qualsiasi momento.",
  GWP_DB_PhaseXofY: "Fase {0} di {1}",

  // V147: Traffic Summary
  TrafficSummary: "Panoramica Traffico",
  VehiclesPerHour: "Ø Flusso",
  VehiclesPerMinute: "Veicoli/Min",
  Approaches: "Accessi",
  IncomingLanes: "Corsie in Entrata",
  IncomingLanesTooltip: "Corsie fisiche che entrano nell'intersezione.",
  OccupiedLanes: "Corsie Occupate",
  OccupiedLanesTooltip: "Numero di corsie occupate con veicoli in attesa.",
  OccupiedPedestrianLanes: "Corsie Ped. Occ.",
  TrafficFlowLow: "Traffico Leggero",
  TrafficFlowMedium: "Traffico Moderato",
  TrafficFlowHigh: "Traffico Intenso",
  WaitingVehicles: "Veicoli in Attesa",
  WaitingVehiclesTooltip: "Numero attuale di veicoli in attesa (media).",
  PeakHour: "Picco (24h)",
  PeakHourTooltip: "Ora con il maggior volume nelle ultime 24 ore.",
  MaxVPH: "Max V/h (24h)",
  MaxVPHTooltip: "Maggior veicoli/ora nelle ultime 24 ore.",
  VPH_InfoEstimate: "Stima basata su corsie e occupazione.",
  VPH_InfoRealData: "Media mobile del conteggio reale dei veicoli.",
  ChartDisabledTooltip: "Attiva 'Fase Personalizzata' per raccogliere dati",
  ChartCollectingTooltip: "Raccolta dati... Primi valori in ~30 min",
  ChartActiveTooltip: "Storico traffico 24 ore",
  CustomPhaseRequiredTooltip: "Richiede che 'Fasi Personalizzate' sia attivato per questa intersezione.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Eliminare fase?",
};
