export default {
  TrafficSignal: "Semaforo",
  ModDefault: "Predefinito",
  Vanilla: "Vanilla",
  SplitPhasing: "Fase divisa",
  ProtectedRightTurns: "Svolte a destra protette",
  ProtectedLeftTurns: "Svolte a sinistra protette",
  Options: "Opzioni",
  ExclusivePedestrianPhase: "Fase pedonale esclusiva",
  LaneDirectionTool: "Strumento direzione corsia (Sperimentale)",
  
  Add: "Aggiungi fase",
  Back: "Indietro",
  ManualControl: "Controllo manuale",
  CustomPhase: "Fase personalizzata",
  CustomPhaseEditor: "Modifica fasi personalizzate",
  SelectFunction: "Seleziona funzione",
  SelectFunctionDescription: "Scegli una funzione per configurare la tua rete di traffico.",
  EditIntersectionPhases: "Modifica fasi incrocio",
  IntersectionMonitor: "Monitor incrocio",
  DashboardComingSoon: "Prossimamente...",
  
  Close: "Chiudi",
  Open: "Apri",
  Reset: "Reimposta",
  Save: "Salva",
  PleaseSave: "Salva le modifiche prima di selezionare un altro incrocio.",
  PleaseSelectJunction: "Seleziona un incrocio",
  GiveWayToOncomingVehicles: "Dare la precedenza ai veicoli in arrivo",
  CustomPedestrianDurationMultiplier: "Durata fase pedonale",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Consenti svolta con rosso",
  CanaryBuildWarning: "Attenzione: stai usando una versione canary che potrebbe contenere bug. Questa versione è solo per test. NON usare per il gioco normale.",
  LdtMigrationNotice: "Lane Direction Tool è stato sostituito dal mod Traffic di krzychu124. Installa il mod Traffic per trasferire automaticamente le tue impostazioni.",
  LdtRetirementNotice: "Lane Direction Tool è stato sostituito dal mod Traffic di krzychu124. Grazie per aver usato LDT.",
  
  PrioritiseTrack: "Priorità veicoli",
  PrioritisePublicCar: "Priorità trasporto pubblico",
  PrioritisePedestrian: "Priorità pedoni",
  PrioritiseBicycle: "Priorità ciclisti",
  
  PrioritiseTrackTooltip: "Dà priorità alle corsie dei veicoli normali (auto, camion) durante questa fase",
  PrioritisePublicCarTooltip: "Dà priorità alle corsie del trasporto pubblico (autobus, tram) durante questa fase",
  PrioritisePedestrianTooltip: "Dà priorità ai passaggi pedonali durante questa fase",
  PrioritiseBicycleTooltip: "Dà priorità alle piste ciclabili durante questa fase",
  
  Adjustments: "Regolazioni",
  MinimumDuration: "Durata min.",
  MaximumDuration: "Durata max.",
  TargetDurationMultiplier: "Durata obiettivo",
  LaneOccupiedMultiplier: "Occupazione corsie",
  IntervalExponent: "Esponente intervallo",
  
  MinimumDurationTooltip: "Durata minima del verde. Il semaforo resta verde almeno questo tempo, anche con poco traffico.",
  MaximumDurationTooltip: "Durata massima del verde. Dopo questo tempo, il semaforo cambia anche se c'è traffico in attesa.",
  TargetDurationMultiplierTooltip: "Influenza la durata della fase verde. 1x = Normale, 2x = Doppia durata con traffico, 0.5x = Più corto.",
  LaneOccupiedMultiplierTooltip: "Controlla quanto le corsie piene aumentano la priorità. Più alto = Gli ingorghi si risolvono più velocemente.",
  IntervalExponentTooltip: "Impostazione di equità. Più alto = Le fasi che hanno aspettato di più hanno più priorità.",
  
  Statistics: "Statistiche",
  Timer: "Timer",
  Priority: "Priorità",
  LastRun: "Ultimo ciclo",
  CarFlow: "Flusso veicoli",
  LanesOccupied: "Corsie occupate",
  WeightedWaiting: "Attesa ponderata",
  
  TimerTooltip: "Timer attuale / Durata obiettivo",
  PriorityTooltip: "Valore di priorità attuale di questa fase",
  LastRunTooltip: "Numero di turni dall'ultima esecuzione di questa fase",
  CarFlowTooltip: "Flusso attuale di veicoli in questa fase",
  LanesOccupiedTooltip: "Numero di corsie occupate (veicoli, trasporti, binari, pedoni)",
  WeightedWaitingTooltip: "Tempo di attesa ponderato dei veicoli in questa fase",
  
  EndPhasePrematurely: "Termina fase ora",
  PhaseEndRequested: "Fine fase richiesta",
  SelectAll: "Seleziona tutto",
  DeselectAll: "Deseleziona tutto",
  CopyPhases: "Copia fasi",
  PastePhases: "Incolla fasi",
  DeleteSelectedPhases: "Elimina selezionate",
  ClearClipboard: "Svuota appunti",
  
  SelectAllTooltip: "Seleziona tutte le fasi per copiare o eliminare",
  CopyPhasesTooltip: "Copia le fasi selezionate negli appunti",
  PastePhasesTooltip: "Incolla le fasi dagli appunti",
  DeleteSelectedPhasesTooltip: "Elimina definitivamente le fasi selezionate",
  ClearClipboardTooltip: "Svuota gli appunti per evitare incollaggi accidentali",

  GreenWave: "Onda Verde",
  GreenWaveButton: "Onda Verde",
  SyncGroup: "Gruppo di Sincronizzazione",
  NoSyncGroup: "Nessun Gruppo",
  CreateNewGroup: "Crea Nuovo Gruppo",
  CycleOffset: "Offset del Ciclo",
  UseSyncedCycle: "Attiva Sincronizzazione",
  TotalCycleDuration: "Durata Totale del Ciclo",
  BaseCycleDuration: "Ciclo Base",
  IntersectionsInGroup: "Incroci",
  NewGroupName: "Nuovo Gruppo",
  DeleteGroup: "Elimina Gruppo",
  RenameGroup: "Rinomina",
  OpenGreenWavePanel: "Apri Onda Verde",
  GreenWavePanelActive: "Onda Verde Attiva",
  
  PhaseMode: "Modalità Fase",
  LegacyMode: "Standard (Priorità)",
  LegacyModeHint: "Prossima fase in base alla domanda di traffico",
  LegacyModeTooltip: "Le fasi cambiano in base alla priorità - veicoli e pedoni in attesa determinano la prossima fase. Comportamento predefinito del gioco.",
  SequentialMode: "Sequenziale (Ordine)",
  SequentialModeHint: "Fasi 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Le fasi si eseguono in ordine: 1 → 2 → 3 → 4 → 1... Sequenza fissa e prevedibile. Richiesto per l'Onda Verde.",
  GreenWaveForcesSequential: "L'Onda Verde richiede la modalità sequenziale",
  
  SyncSettings: "Impostazioni di Sincronizzazione",
  SyncPhase: "Fase di Sincronizzazione",
  SyncPhaseTooltip: "Seleziona quale fase sincronizzare. Utile per le corsie di svolta.",
  OffsetCalculator: "Calcolatore di Offset",
  Distance: "Distanza",
  Speed: "Velocità",
  RecommendedOffset: "Raccomandato",
  Apply: "Applica",
  OwnCycle: "Ciclo Proprio",
  GroupBase: "Base del Gruppo",
  AutoFactor: "Fattore Auto",
  AutoFactorTooltip: "Rapporto tra il ciclo proprio e la base del gruppo. I diversi cicli vengono scalati automaticamente.",
  Intersections: "Incroci",
  NoGroupsYet: "Nessun gruppo creato ancora",
  Information: "Informazione",
  
  GreenWaveTooltip: "Sincronizza più incroci per un effetto onda verde",
  GreenWaveTooltipActive: "Sincronizza più incroci lungo una strada in modo che i veicoli possano passare senza fermarsi durante un'onda verde.",
  GreenWaveTooltipDisabled: "L'Onda Verde è disponibile solo quando 'Fasi Personalizzate' è abilitato per questo incrocio. Seleziona prima 'Fasi Personalizzate'.",
  SyncGroupTooltip: "Seleziona un gruppo di sincronizzazione per questo incrocio",
  CycleOffsetTooltip: "Offset in secondi dal timer del gruppo. Diversi offset creano l'onda verde.",
  UseSyncedCycleTooltip: "Attiva la sincronizzazione con il gruppo selezionato",


  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Incrocio",
  GWP_TabGroups: "Gruppi",
  GWP_TabDashboard: "Dashboard",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Sincronizzazione attiva",
  GWP_NotSynced: "Non sincronizzato",

  // Green Wave Panel - Labels
  GWP_NodeId: "Node ID (Incrocio)",
  GWP_Group: "Gruppo",
  GWP_Offset: "Offset",
  GWP_AssignSyncGroup: "Assegna Gruppo Sync",
  GWP_NoGroupSelected: "Nessun gruppo selezionato",
  GWP_NoGroup: "Nessun Gruppo",
  GWP_NewGroup: "+ Nuovo Gruppo",
  GWP_Rename: "Rinomina",
  GWP_EnableSync: "Abilita Sync",
  GWP_CycleOffset: "Offset Ciclo",
  GWP_Tempo: "Velocità",
  GWP_Recommended: "Consigliato:",
  GWP_GameTime: "Gioco",
  GWP_RealTime: "Reale",
  GWP_PhaseHint: "La Fase #1 dovrebbe essere la direzione principale per l'Onda Verde!",
  GWP_AutoSave: "Le modifiche vengono salvate automaticamente",
  GWP_SelectIntersection: "Seleziona un incrocio.",
  GWP_SearchGroups: "Cerca gruppi...",
  GWP_NoMatches: "Nessun risultato per",
  GWP_RemoveFromGroup: "Rimuovi dal Gruppo",
  GWP_DeleteGroup: "Elimina Gruppo",
  GWP_NoIntersections: "Nessun incrocio",
  GWP_GroupsHint: "I gruppi senza incroci possono essere eliminati. Aggiungi incroci nella scheda 'Incrocio'.",
  GWP_SelectGroupHint: "Seleziona un gruppo nella scheda 'Incrocio' per vedere i dettagli.",
  GWP_AddIntersectionsHint: "Questo gruppo non ha ancora incroci. Vai alla scheda 'Incrocio' e aggiungi incroci!",
  GWP_RemovedFromGroup: "Rimosso dal gruppo",
  GWP_AddedToGroup: "Aggiunto a",
  GWP_SyncEnabled: "Sync abilitato!",
  GWP_SyncDisabled: "Sync disabilitato",
  GWP_NewGroupCreated: "Nuovo gruppo creato!",
  GWP_GroupRenamed: "Gruppo rinominato in",
  GWP_GroupDeleted: "Gruppo eliminato",
  GWP_IntersectionRemoved: "Incrocio rimosso dal gruppo",
  GWP_OffsetSet: "Offset impostato a",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Abilita la sincronizzazione di questo incrocio con il gruppo.",
  GWP_TT_SyncPhase: "Seleziona quale fase sincronizzare. La Fase #1 dovrebbe essere la direzione principale (Onda Verde).",
  GWP_TT_CycleOffset: "Offset in secondi rispetto al ciclo base del gruppo.",
  GWP_TT_Distance: "Distanza dall'incrocio precedente in metri.",
  GWP_TT_Speed: "Velocità del traffico sulla strada.",
  GWP_TT_OwnCycle: "Durata totale di un ciclo semaforico per questo incrocio in tempo di gioco.",
  GWP_TT_GroupBase: "Ciclo base del gruppo in tempo di gioco.",
  GWP_TT_Intersections: "Numero di incroci in questo gruppo.",
};
