export default {
  TrafficSignal: "信号機",
  ModDefault: "デフォルト",
  Vanilla: "バニラ",
  SplitPhasing: "分割フェーズ",
  ProtectedRightTurns: "保護右折",
  ProtectedLeftTurns: "保護左折",
  Options: "オプション",
  ExclusivePedestrianPhase: "歩行者専用フェーズ",
  LaneDirectionTool: "車線方向ツール（実験的）",
  
  Add: "フェーズを追加",
  Back: "戻る",
  ManualControl: "手動制御",
  CustomPhase: "カスタムフェーズ",
  CustomPhaseEditor: "カスタムフェーズを編集",
  SelectFunction: "機能を選択",
  SelectFunctionDescription: "交通ネットワークを設定する機能を選択してください。",
  EditIntersectionPhases: "交差点フェーズを編集",
  IntersectionMonitor: "交差点モニター",
  DashboardComingSoon: "近日公開...",
  
  Close: "閉じる",
  Open: "開く",
  Reset: "リセット",
  Save: "保存",
  PleaseSave: "別の交差点を選択する前に変更を保存してください。",
  PleaseSelectJunction: "交差点を選択してください",
  GiveWayToOncomingVehicles: "対向車に道を譲る",
  CustomPedestrianDurationMultiplier: "歩行者フェーズ時間",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "赤信号での右左折を許可",
  CanaryBuildWarning: "注意：バグを含む可能性のあるカナリービルドを使用しています。このビルドはテスト専用です。通常のゲームプレイには使用しないでください。",
  LdtMigrationNotice: "Lane Direction Toolはkrzychu124のTrafficモッドに置き換えられました。Trafficモッドをインストールして設定を自動転送してください。",
  LdtRetirementNotice: "Lane Direction Toolはkrzychu124のTrafficモッドに置き換えられました。LDTをご利用いただきありがとうございました。",
  
  PrioritiseTrack: "車両を優先",
  PrioritisePublicCar: "公共交通を優先",
  PrioritisePedestrian: "歩行者を優先",
  PrioritiseBicycle: "自転車を優先",
  
  PrioritiseTrackTooltip: "このフェーズ中、通常の車両レーン（車、トラック）を優先します",
  PrioritisePublicCarTooltip: "このフェーズ中、公共交通レーン（バス、路面電車）を優先します",
  PrioritisePedestrianTooltip: "このフェーズ中、横断歩道を優先します",
  PrioritiseBicycleTooltip: "このフェーズ中、自転車レーンを優先します",
  
  Adjustments: "調整",
  MinimumDuration: "最小時間",
  MaximumDuration: "最大時間",
  TargetDurationMultiplier: "目標時間",
  LaneOccupiedMultiplier: "車線占有率",
  IntervalExponent: "間隔指数",
  
  MinimumDurationTooltip: "最小青信号時間。交通量が少なくても、信号は少なくともこの時間は青のままです。",
  MaximumDurationTooltip: "最大青信号時間。この時間が経過すると、まだ交通が待っていても信号が切り替わります。",
  TargetDurationMultiplierTooltip: "青フェーズの長さに影響します。1x = 通常、2x = 混雑時は2倍、0.5x = 短縮。",
  LaneOccupiedMultiplierTooltip: "満杯のレーンが優先度をどれだけ上げるかを制御します。高い = 渋滞がより早く解消されます。",
  IntervalExponentTooltip: "公平性の設定。高い = 長く待ったフェーズがより優先されます。",
  
  Statistics: "統計",
  Timer: "タイマー",
  Priority: "優先度",
  LastRun: "前回の実行",
  CarFlow: "車両フロー",
  LanesOccupied: "占有レーン",
  WeightedWaiting: "加重待ち時間",
  
  TimerTooltip: "現在のタイマー / 目標時間",
  PriorityTooltip: "このフェーズの現在の優先度値",
  LastRunTooltip: "このフェーズが最後に実行されてからのターン数",
  CarFlowTooltip: "このフェーズの現在の車両フロー",
  LanesOccupiedTooltip: "占有レーン数（車両、公共交通、軌道、歩行者）",
  WeightedWaitingTooltip: "このフェーズでの車両の加重待ち時間",
  
  EndPhasePrematurely: "今すぐフェーズを終了",
  PhaseEndRequested: "フェーズ終了リクエスト済み",
  SelectAll: "すべて選択",
  DeselectAll: "選択解除",
  CopyPhases: "フェーズをコピー",
  PastePhases: "フェーズを貼り付け",
  DeleteSelectedPhases: "選択したものを削除",
  ClearClipboard: "クリップボードをクリア",
  
  SelectAllTooltip: "コピーまたは削除するすべてのフェーズを選択",
  CopyPhasesTooltip: "選択したフェーズをクリップボードにコピー",
  PastePhasesTooltip: "クリップボードからフェーズを貼り付け",
  DeleteSelectedPhasesTooltip: "選択したフェーズを完全に削除",
  ClearClipboardTooltip: "誤った貼り付けを防ぐためにクリップボードをクリア",

  GreenWave: "グリーンウェーブ",
  GreenWaveButton: "グリーンウェーブ",
  SyncGroup: "同期グループ",
  NoSyncGroup: "グループなし",
  CreateNewGroup: "新しいグループを作成",
  CycleOffset: "サイクルオフセット",
  UseSyncedCycle: "同期を有効化",
  TotalCycleDuration: "合計サイクル時間",
  BaseCycleDuration: "基本サイクル",
  IntersectionsInGroup: "交差点",
  NewGroupName: "新しいグループ",
  DeleteGroup: "グループを削除",
  RenameGroup: "名前を変更",
  OpenGreenWavePanel: "グリーンウェーブを開く",
  GreenWavePanelActive: "グリーンウェーブ有効",
  
  PhaseMode: "フェーズモード",
  LegacyMode: "標準（優先度）",
  LegacyModeHint: "交通需要に基づく次のフェーズ",
  LegacyModeTooltip: "フェーズは優先度に基づいて切り替わります - 待機中の車両と歩行者が次のフェーズを決定します。デフォルトのゲーム動作。",
  SequentialMode: "順次（順序）",
  SequentialModeHint: "フェーズ 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "フェーズは順番に実行されます: 1 → 2 → 3 → 4 → 1... 固定された予測可能な順序。グリーンウェーブに必要。",
  GreenWaveForcesSequential: "グリーンウェーブには順次モードが必要です",
  
  SyncSettings: "同期設定",
  SyncPhase: "同期フェーズ",
  SyncPhaseTooltip: "同期するフェーズを選択します。ターンレーンに便利です。",
  OffsetCalculator: "オフセット計算機",
  Distance: "距離",
  Speed: "速度",
  RecommendedOffset: "推奨",
  Apply: "適用",
  OwnCycle: "独自サイクル",
  GroupBase: "グループベース",
  AutoFactor: "自動係数",
  AutoFactorTooltip: "独自サイクルとグループベースの比率。異なるサイクル長は自動的にスケーリングされます。",
  Intersections: "交差点",
  NoGroupsYet: "まだグループが作成されていません",
  Information: "情報",
  
  GreenWaveTooltip: "グリーンウェーブ効果のために複数の交差点を同期",
  GreenWaveTooltipActive: "道路沿いの複数の交差点を同期して、グリーンウェーブ中に車両が停止せずに通過できるようにします。",
  GreenWaveTooltipDisabled: "グリーンウェーブは、この交差点で「カスタムフェーズ」が有効になっている場合にのみ使用できます。最初に「カスタムフェーズ」を選択してください。",
  SyncGroupTooltip: "この交差点の同期グループを選択",
  CycleOffsetTooltip: "グループタイマーからの秒単位のオフセット。異なるオフセットがグリーンウェーブを作成します。",
  UseSyncedCycleTooltip: "選択したグループとの同期を有効にします",
};
