export default {
  TrafficSignal: "信号機",
  ModDefault: "デフォルト",
  Vanilla: "バニラ",
  SplitPhasing: "分割フェーズ",
  ProtectedRightTurns: "保護右折",
  ProtectedLeftTurns: "保護左折",
  Options: "オプション",
  ExclusivePedestrianPhase: "歩行者専用フェーズ",
  LaneDirectionTool: "車線方向ツール（実験的）",
  
  Add: "フェーズを追加",
  Back: "戻る",
  ManualControl: "手動制御",
  CustomPhase: "カスタムフェーズ",
  CustomPhaseEditor: "カスタムフェーズを編集",
  SelectFunction: "機能を選択",
  SelectFunctionDescription: "交通ネットワークを設定する機能を選択してください。",
  EditIntersectionPhases: "交差点フェーズを編集",
  IntersectionMonitor: "交差点モニター",
  DashboardComingSoon: "近日公開...",
  
  Close: "閉じる",
  Open: "開く",
  Reset: "リセット",
  Save: "保存",
  PleaseSave: "別の交差点を選択する前に変更を保存してください。",
  PleaseSelectJunction: "交差点を選択してください",
  GiveWayToOncomingVehicles: "対向車に道を譲る",
  CustomPedestrianDurationMultiplier: "歩行者フェーズ時間",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "赤信号での右左折を許可",
  CanaryBuildWarning: "注意：バグを含む可能性のあるカナリービルドを使用しています。このビルドはテスト専用です。通常のゲームプレイには使用しないでください。",
  LdtMigrationNotice: "Lane Direction Toolはkrzychu124のTrafficモッドに置き換えられました。Trafficモッドをインストールして設定を自動転送してください。",
  LdtRetirementNotice: "Lane Direction Toolはkrzychu124のTrafficモッドに置き換えられました。LDTをご利用いただきありがとうございました。",
  
  PrioritiseTrack: "車両を優先",
  PrioritisePublicCar: "公共交通を優先",
  PrioritisePedestrian: "歩行者を優先",
  PrioritiseBicycle: "自転車を優先",
  
  PrioritiseTrackTooltip: "このフェーズ中、通常の車両レーン（車、トラック）を優先します",
  PrioritisePublicCarTooltip: "このフェーズ中、公共交通レーン（バス、路面電車）を優先します",
  PrioritisePedestrianTooltip: "このフェーズ中、横断歩道を優先します",
  PrioritiseBicycleTooltip: "このフェーズ中、自転車レーンを優先します",
  
  Adjustments: "調整",
  MinimumDuration: "最小時間",
  MaximumDuration: "最大時間",
  TargetDurationMultiplier: "目標時間",
  LaneOccupiedMultiplier: "車線占有率",
  IntervalExponent: "間隔指数",
  
  MinimumDurationTooltip: "最小青信号時間。交通量が少なくても、信号は少なくともこの時間は青のままです。",
  MaximumDurationTooltip: "最大青信号時間。この時間が経過すると、まだ交通が待っていても信号が切り替わります。",
  TargetDurationMultiplierTooltip: "青フェーズの長さに影響します。1x = 通常、2x = 混雑時は2倍、0.5x = 短縮。",
  LaneOccupiedMultiplierTooltip: "満杯のレーンが優先度をどれだけ上げるかを制御します。高い = 渋滞がより早く解消されます。",
  IntervalExponentTooltip: "公平性の設定。高い = 長く待ったフェーズがより優先されます。",
  
  Statistics: "統計",
  Timer: "タイマー",
  Priority: "優先度",
  LastRun: "前回の実行",
  CarFlow: "車両フロー",
  LanesOccupied: "占有レーン",
  WeightedWaiting: "加重待ち時間",
  
  TimerTooltip: "現在のタイマー / 目標時間",
  PriorityTooltip: "このフェーズの現在の優先度値",
  LastRunTooltip: "このフェーズが最後に実行されてからのターン数",
  CarFlowTooltip: "このフェーズの現在の車両フロー",
  LanesOccupiedTooltip: "占有レーン数（車両、公共交通、軌道、歩行者）",
  WeightedWaitingTooltip: "このフェーズでの車両の加重待ち時間",
  
  EndPhasePrematurely: "今すぐフェーズを終了",
  PhaseEndRequested: "フェーズ終了リクエスト済み",
  SelectAll: "すべて選択",
  DeselectAll: "選択解除",
  CopyPhases: "フェーズをコピー",
  PastePhases: "フェーズを貼り付け",
  DeleteSelectedPhases: "選択したものを削除",
  ClearClipboard: "クリップボードをクリア",
  
  SelectAllTooltip: "コピーまたは削除するすべてのフェーズを選択",
  CopyPhasesTooltip: "選択したフェーズをクリップボードにコピー",
  PastePhasesTooltip: "クリップボードからフェーズを貼り付け",
  DeleteSelectedPhasesTooltip: "選択したフェーズを完全に削除",
  ClearClipboardTooltip: "誤った貼り付けを防ぐためにクリップボードをクリア",

  GreenWave: "グリーンウェーブ",
  GreenWaveButton: "グリーンウェーブ",
  SyncGroup: "同期グループ",
  NoSyncGroup: "グループなし",
  CreateNewGroup: "新しいグループを作成",
  CycleOffset: "サイクルオフセット",
  UseSyncedCycle: "同期を有効化",
  TotalCycleDuration: "合計サイクル時間",
  BaseCycleDuration: "基本サイクル",
  IntersectionsInGroup: "交差点",
  NewGroupName: "新しいグループ",
  DeleteGroup: "グループを削除",
  RenameGroup: "名前を変更",
  OpenGreenWavePanel: "グリーンウェーブを開く",
  GreenWavePanelActive: "グリーンウェーブ有効",
  
  PhaseMode: "フェーズモード",
  LegacyMode: "標準（優先度）",
  LegacyModeHint: "交通需要に基づく次のフェーズ",
  LegacyModeTooltip: "フェーズは優先度に基づいて切り替わります - 待機中の車両と歩行者が次のフェーズを決定します。デフォルトのゲーム動作。",
  SequentialMode: "順次（順序）",
  SequentialModeHint: "フェーズ 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "フェーズは順番に実行されます: 1 → 2 → 3 → 4 → 1... 固定された予測可能な順序。グリーンウェーブに必要。",
  GreenWaveForcesSequential: "グリーンウェーブには順次モードが必要です",
  
  SyncSettings: "同期設定",
  SyncPhase: "同期フェーズ",
  SyncPhaseTooltip: "同期するフェーズを選択。右左折レーンに便利。",
  OffsetCalculator: "オフセット計算機",
  Distance: "距離",
  Speed: "速度",
  RecommendedOffset: "推奨",
  Apply: "適用",
  OwnCycle: "自身サイクル",
  GroupBase: "グループベース",
  AutoFactor: "自動係数",
  AutoFactorTooltip: "独自サイクルとグループベースの比率。異なるサイクル長は自動的にスケーリングされます。",
  Intersections: "交差点",
  NoGroupsYet: "まだグループが作成されていません",
  Information: "情報",
  
  GreenWaveTooltip: "グリーンウェーブ効果のために複数の交差点を同期",
  GreenWaveTooltipActive: "道路沿いの複数の交差点を同期して、グリーンウェーブ中に車両が停止せずに通過できるようにします。",
  GreenWaveTooltipDisabled: "グリーンウェーブは、この交差点で「カスタムフェーズ」が有効になっている場合にのみ使用できます。最初に「カスタムフェーズ」を選択してください。",
  SyncGroupTooltip: "この交差点の同期グループを選択",
  CycleOffsetTooltip: "グループタイマーからの秒単位のオフセット。異なるオフセットがグリーンウェーブを作成します。",
  UseSyncedCycleTooltip: "選択したグループとの同期を有効にします",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "交差点",
  GWP_TabGroups: "グループ",
  GWP_TabDashboard: "ダッシュボード",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "同期有効",
  GWP_NotSynced: "未同期",

  // Green Wave Panel - Labels
  GWP_NodeId: "ノード ID (交差点)",
  GWP_Group: "グループ",
  GWP_Offset: "オフセット",
  GWP_AssignSyncGroup: "同期グループを割り当て",
  GWP_NoGroupSelected: "グループ未選択",
  GWP_NoGroup: "グループなし",
  GWP_NewGroup: "+ 新規グループ",
  GWP_Rename: "名前変更",
  GWP_EnableSync: "同期を有効にする",
  GWP_CycleOffset: "サイクルオフセット",
  GWP_Tempo: "速度",
  GWP_Recommended: "推奨：",
  GWP_GameTime: "ゲーム",
  GWP_RealTime: "実時間",
  GWP_PhaseHint: "フェーズ #1 はグリーンウェーブの主方向にしてください！",
  GWP_AutoSave: "変更は自動保存されます",
  GWP_SelectIntersection: "交差点を選択してください。",
  GWP_SearchGroups: "グループを検索...",
  GWP_NoMatches: "一致なし",
  GWP_RemoveFromGroup: "グループから削除",
  GWP_DeleteGroup: "グループを削除",
  GWP_NoIntersections: "交差点",
  GWP_GroupsHint: "交差点のないグループは削除できます。「交差点」タブで交差点を追加してください。",
  GWP_SelectGroupHint: "「交差点」タブでグループを選択して詳細を表示。",
  GWP_AddIntersectionsHint: "このグループにはまだ交差点がありません。「交差点」タブで交差点を追加！",
  GWP_RemovedFromGroup: "グループから削除しました",
  GWP_AddedToGroup: "追加しました：",
  GWP_SyncEnabled: "同期を有効にしました！",
  GWP_SyncDisabled: "同期を無効にしました",
  GWP_NewGroupCreated: "新規グループを作成しました！",
  GWP_GroupRenamed: "グループ名を変更しました：",
  GWP_GroupDeleted: "グループを削除しました",
  GWP_IntersectionRemoved: "交差点をグループから削除しました",
  GWP_OffsetSet: "オフセットを設定しました：",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "この交差点とグループの同期を有効にします。",
  GWP_TT_SyncPhase: "同期フェーズ",
  GWP_TT_CycleOffset: "グループ基本サイクルからの時間オフセット（秒）。",
  GWP_TT_Distance: "距離",
  GWP_TT_Speed: "速度",
  GWP_TT_OwnCycle: "自身サイクル",
  GWP_TT_GroupBase: "グループの基本サイクル（ゲーム時間）。",
  GWP_TT_Intersections: "交差点",
  GWP_MoveUp: "上へ移動",
  GWP_MoveDown: "下へ移動",
  GWP_ManageGroups: "同期グループを管理",
  GWP_CreateNewGroup: "+ 新規グループ作成",
  GWP_DB_Intersection: "交差点",
  GWP_DB_Reference: "基準",
  GWP_DB_Phases: "フェーズ",
  GWP_DB_Green: "緑",
  GWP_DB_SyncOn: "同期",
  GWP_DB_SyncOff: "OFF",
  GWP_DB_SyncWaiting: "同期中 - 待機",
  GWP_DB_GreenWaveActive: "グリーンウェーブ有効!",
  GWP_DB_ReadyToSwitch: "切替準備完了",
  GWP_DB_Offset: "オフセット",
  GWP_DB_Cycle: "サイクル",
  GWP_DB_Roads: "道路",
  GWP_DB_Lanes: "レーン",
  GWP_DB_Pedestrians: "歩行者",
  GWP_DB_OffsetDelta: "オフセット",
  GWP_DB_BaseCycle: "基本サイクル",
  GWP_DB_GreenWaveLabel: "グリーンウェーブ",
  GWP_DB_SyncActiveLabel: "同期有効",
  GWP_DB_ReorderHint: "矢印キーで順序を調整。最初の交差点が基準（オフセット0）。",
  GWP_DB_PhaseProgressTooltip: "左: 最小時間。点滅: 切替準備完了。",
  GWP_DB_MinDurationTooltip: "50%で最小時間に到達。いつでも切替可能。",
  GWP_DB_PhaseXofY: "フェーズ {0}/{1}",

  // V147: Traffic Summary
  TrafficSummary: "交通概要",
  VehiclesPerHour: "Ø スループット",
  VehiclesPerMinute: "車両/分",
  Approaches: "進入路",
  IncomingLanes: "進入レーン",
  IncomingLanesTooltip: "交差点に入る物理的なレーン。",
  OccupiedLanes: "占有レーン",
  OccupiedLanesTooltip: "待機車両のある占有レーン数。",
  OccupiedPedestrianLanes: "歩行者レーン占有",
  TrafficFlowLow: "交通量少",
  TrafficFlowMedium: "交通量中",
  TrafficFlowHigh: "交通量多",
  WaitingVehicles: "待機車両",
  WaitingVehiclesTooltip: "待機中の車両数（平均）。",
  PeakHour: "ピーク(24h)",
  PeakHourTooltip: "過去24時間で最も交通量が多かった時間。",
  MaxVPH: "最大V/h(24h)",
  MaxVPHTooltip: "過去24時間の最大車両/時。",
  VPH_InfoEstimate: "レーン数と占有率に基づく推定。",
  VPH_InfoRealData: "実際の車両カウントの移動平均。",
  ChartDisabledTooltip: "「カスタムフェーズ」を有効にしてデータを収集",
  ChartCollectingTooltip: "データ収集中...約30分後に最初の値",
  ChartActiveTooltip: "24時間交通履歴",
  CustomPhaseRequiredTooltip: "この交差点で「カスタムフェーズ」を有効にする必要があります。",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "フェーズを削除？",
};
