export default {
  TrafficSignal: "신호등",
  ModDefault: "기본값",
  Vanilla: "바닐라",
  SplitPhasing: "분할 페이즈",
  ProtectedRightTurns: "보호 우회전",
  ProtectedLeftTurns: "보호 좌회전",
  Options: "옵션",
  ExclusivePedestrianPhase: "보행자 전용 페이즈",
  LaneDirectionTool: "차선 방향 도구 (실험적)",
  
  Add: "페이즈 추가",
  Back: "뒤로",
  ManualControl: "수동 제어",
  CustomPhase: "사용자 정의 페이즈",
  CustomPhaseEditor: "사용자 정의 페이즈 편집",
  SelectFunction: "기능 선택",
  SelectFunctionDescription: "교통 네트워크를 구성할 기능을 선택하세요.",
  EditIntersectionPhases: "교차로 페이즈 편집",
  IntersectionMonitor: "교차로 모니터",
  DashboardComingSoon: "곧 출시...",
  
  Close: "닫기",
  Open: "열기",
  Reset: "초기화",
  Save: "저장",
  PleaseSave: "다른 교차로를 선택하기 전에 변경 사항을 저장하세요.",
  PleaseSelectJunction: "교차로를 선택하세요",
  GiveWayToOncomingVehicles: "대향 차량에 양보",
  CustomPedestrianDurationMultiplier: "보행자 페이즈 시간",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "적색 신호 회전 허용",
  CanaryBuildWarning: "주의: 버그가 포함될 수 있는 카나리 빌드를 사용 중입니다. 이 빌드는 테스트 전용입니다. 일반 게임플레이에는 사용하지 마세요.",
  LdtMigrationNotice: "Lane Direction Tool은 krzychu124의 Traffic 모드로 대체되었습니다. Traffic 모드를 설치하여 설정을 자동으로 이전하세요.",
  LdtRetirementNotice: "Lane Direction Tool은 krzychu124의 Traffic 모드로 대체되었습니다. LDT를 사용해 주셔서 감사합니다.",
  
  PrioritiseTrack: "차량 우선",
  PrioritisePublicCar: "대중교통 우선",
  PrioritisePedestrian: "보행자 우선",
  PrioritiseBicycle: "자전거 우선",
  
  PrioritiseTrackTooltip: "이 페이즈 동안 일반 차량 차선(자동차, 트럭)에 우선권을 부여합니다",
  PrioritisePublicCarTooltip: "이 페이즈 동안 대중교통 차선(버스, 트램)에 우선권을 부여합니다",
  PrioritisePedestrianTooltip: "이 페이즈 동안 횡단보도에 우선권을 부여합니다",
  PrioritiseBicycleTooltip: "이 페이즈 동안 자전거 차선에 우선권을 부여합니다",
  
  Adjustments: "조정",
  MinimumDuration: "최소 시간",
  MaximumDuration: "최대 시간",
  TargetDurationMultiplier: "목표 시간",
  LaneOccupiedMultiplier: "차선 점유율",
  IntervalExponent: "간격 지수",
  
  MinimumDurationTooltip: "최소 녹색 신호 시간. 교통량이 적어도 신호는 최소 이 시간 동안 녹색을 유지합니다.",
  MaximumDurationTooltip: "최대 녹색 신호 시간. 이 시간이 지나면 대기 중인 교통이 있어도 신호가 바뀝니다.",
  TargetDurationMultiplierTooltip: "녹색 페이즈 길이에 영향을 줍니다. 1x = 보통, 2x = 혼잡 시 2배, 0.5x = 짧음.",
  LaneOccupiedMultiplierTooltip: "가득 찬 차선이 우선순위를 얼마나 높이는지 제어합니다. 높음 = 정체가 더 빨리 해소됩니다.",
  IntervalExponentTooltip: "공정성 설정. 높음 = 오래 기다린 페이즈가 더 높은 우선순위를 받습니다.",
  
  Statistics: "통계",
  Timer: "타이머",
  Priority: "우선순위",
  LastRun: "마지막 실행",
  CarFlow: "차량 흐름",
  LanesOccupied: "점유 차선",
  WeightedWaiting: "가중 대기 시간",
  
  TimerTooltip: "현재 타이머 / 목표 시간",
  PriorityTooltip: "이 페이즈의 현재 우선순위 값",
  LastRunTooltip: "이 페이즈가 마지막으로 실행된 이후 턴 수",
  CarFlowTooltip: "이 페이즈의 현재 차량 흐름",
  LanesOccupiedTooltip: "점유된 차선 수 (차량, 대중교통, 철도, 보행자)",
  WeightedWaitingTooltip: "이 페이즈에서 차량의 가중 대기 시간",
  
  EndPhasePrematurely: "지금 페이즈 종료",
  PhaseEndRequested: "페이즈 종료 요청됨",
  SelectAll: "모두 선택",
  DeselectAll: "선택 해제",
  CopyPhases: "페이즈 복사",
  PastePhases: "페이즈 붙여넣기",
  DeleteSelectedPhases: "선택 항목 삭제",
  ClearClipboard: "클립보드 지우기",
  
  SelectAllTooltip: "복사 또는 삭제할 모든 페이즈 선택",
  CopyPhasesTooltip: "선택한 페이즈를 클립보드에 복사",
  PastePhasesTooltip: "클립보드에서 페이즈 붙여넣기",
  DeleteSelectedPhasesTooltip: "선택한 페이즈를 영구적으로 삭제",
  ClearClipboardTooltip: "실수로 붙여넣는 것을 방지하기 위해 클립보드 지우기",

  GreenWave: "녹색파",
  GreenWaveButton: "녹색파",
  SyncGroup: "동기화 그룹",
  NoSyncGroup: "그룹 없음",
  CreateNewGroup: "새 그룹 만들기",
  CycleOffset: "사이클 오프셋",
  UseSyncedCycle: "동기화 활성화",
  TotalCycleDuration: "총 사이클 시간",
  BaseCycleDuration: "기본 사이클",
  IntersectionsInGroup: "교차로",
  NewGroupName: "새 그룹",
  DeleteGroup: "그룹 삭제",
  RenameGroup: "이름 바꾸기",
  OpenGreenWavePanel: "녹색파 열기",
  GreenWavePanelActive: "녹색파 활성",
  
  PhaseMode: "페이즈 모드",
  LegacyMode: "표준 (우선순위)",
  LegacyModeHint: "교통 수요에 따른 다음 페이즈",
  LegacyModeTooltip: "페이즈는 우선순위에 따라 전환됩니다 - 대기 중인 차량과 보행자가 다음 페이즈를 결정합니다. 기본 게임 동작.",
  SequentialMode: "순차 (순서)",
  SequentialModeHint: "페이즈 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "페이즈가 순서대로 실행됩니다: 1 → 2 → 3 → 4 → 1... 고정된 예측 가능한 순서. 녹색파에 필요.",
  GreenWaveForcesSequential: "녹색파는 순차 모드가 필요합니다",
  
  SyncSettings: "동기화 설정",
  SyncPhase: "동기화 페이즈",
  SyncPhaseTooltip: "동기화할 페이즈를 선택합니다. 회전 차선에 유용합니다.",
  OffsetCalculator: "오프셋 계산기",
  Distance: "거리",
  Speed: "속도",
  RecommendedOffset: "권장",
  Apply: "적용",
  OwnCycle: "자체 사이클",
  GroupBase: "그룹 기준",
  AutoFactor: "자동 계수",
  AutoFactorTooltip: "자체 사이클과 그룹 기준 간의 비율. 다른 사이클 길이는 자동으로 조정됩니다.",
  Intersections: "교차로",
  NoGroupsYet: "아직 생성된 그룹이 없습니다",
  Information: "정보",
  
  GreenWaveTooltip: "녹색파 효과를 위해 여러 교차로를 동기화",
  GreenWaveTooltipActive: "도로를 따라 여러 교차로를 동기화하여 녹색파 동안 차량이 멈추지 않고 통과할 수 있도록 합니다.",
  GreenWaveTooltipDisabled: "녹색파는 이 교차로에서 '사용자 정의 페이즈'가 활성화된 경우에만 사용할 수 있습니다. 먼저 '사용자 정의 페이즈'를 선택하세요.",
  SyncGroupTooltip: "이 교차로의 동기화 그룹 선택",
  CycleOffsetTooltip: "그룹 타이머에서 초 단위 오프셋. 다른 오프셋이 녹색파를 만듭니다.",
  UseSyncedCycleTooltip: "선택한 그룹과의 동기화를 활성화합니다",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "교차로",
  GWP_TabGroups: "그룹",
  GWP_TabDashboard: "대시보드",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "동기화 활성",
  GWP_NotSynced: "동기화 안됨",

  // Green Wave Panel - Labels
  GWP_NodeId: "노드 ID (교차로)",
  GWP_Group: "그룹",
  GWP_Offset: "오프셋",
  GWP_AssignSyncGroup: "동기화 그룹 지정",
  GWP_NoGroupSelected: "그룹 미선택",
  GWP_NoGroup: "그룹 없음",
  GWP_NewGroup: "+ 새 그룹",
  GWP_Rename: "이름 변경",
  GWP_EnableSync: "동기화 활성화",
  GWP_CycleOffset: "사이클 오프셋",
  GWP_Tempo: "속도",
  GWP_Recommended: "권장:",
  GWP_GameTime: "게임",
  GWP_RealTime: "실시간",
  GWP_PhaseHint: "페이즈 #1은 녹색 파동의 주요 방향이어야 합니다!",
  GWP_AutoSave: "변경사항은 자동 저장됩니다",
  GWP_SelectIntersection: "교차로를 선택하세요.",
  GWP_SearchGroups: "그룹 검색...",
  GWP_NoMatches: "일치 항목 없음",
  GWP_RemoveFromGroup: "그룹에서 제거",
  GWP_DeleteGroup: "그룹 삭제",
  GWP_NoIntersections: "교차로",
  GWP_GroupsHint: "교차로가 없는 그룹은 삭제할 수 있습니다. '교차로' 탭에서 교차로를 추가하세요.",
  GWP_SelectGroupHint: "'교차로' 탭에서 그룹을 선택하여 세부 정보를 확인하세요.",
  GWP_AddIntersectionsHint: "이 그룹에는 아직 교차로가 없습니다. '교차로' 탭에서 교차로를 추가하세요!",
  GWP_RemovedFromGroup: "그룹에서 제거됨",
  GWP_AddedToGroup: "추가됨:",
  GWP_SyncEnabled: "동기화 활성화됨!",
  GWP_SyncDisabled: "동기화 비활성화됨",
  GWP_NewGroupCreated: "새 그룹이 생성됨!",
  GWP_GroupRenamed: "그룹 이름 변경됨:",
  GWP_GroupDeleted: "그룹 삭제됨",
  GWP_IntersectionRemoved: "교차로가 그룹에서 제거됨",
  GWP_OffsetSet: "오프셋 설정됨:",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "이 교차로와 그룹의 동기화를 활성화합니다.",
  GWP_TT_SyncPhase: "동기화 페이즈",
  GWP_TT_CycleOffset: "그룹 기본 사이클에서의 시간 오프셋(초).",
  GWP_TT_Distance: "거리",
  GWP_TT_Speed: "속도",
  GWP_TT_OwnCycle: "자체 사이클",
  GWP_TT_GroupBase: "그룹의 기본 사이클(게임 시간).",
  GWP_TT_Intersections: "교차로",
  GWP_MoveUp: "위로 이동",
  GWP_MoveDown: "아래로 이동",
  GWP_ManageGroups: "동기화 그룹 관리",
  GWP_CreateNewGroup: "+ 새 그룹 만들기",
  GWP_DB_Intersection: "교차로",
  GWP_DB_Reference: "기준",
  GWP_DB_Phases: "페이즈",
  GWP_DB_Green: "녹색",
  GWP_DB_SyncOn: "동기화",
  GWP_DB_SyncOff: "OFF",
  GWP_DB_SyncWaiting: "동기화 중 - 대기",
  GWP_DB_GreenWaveActive: "녹색 파동 활성화!",
  GWP_DB_ReadyToSwitch: "전환 준비 완료",
  GWP_DB_Offset: "오프셋",
  GWP_DB_Cycle: "사이클",
  GWP_DB_Roads: "도로",
  GWP_DB_Lanes: "차선",
  GWP_DB_Pedestrians: "보행자",
  GWP_DB_OffsetDelta: "오프셋",
  GWP_DB_BaseCycle: "기본 사이클",
  GWP_DB_GreenWaveLabel: "녹색 파동",
  GWP_DB_SyncActiveLabel: "동기화 활성",
  GWP_DB_ReorderHint: "화살표 키로 순서 조정. 첫 번째 교차로가 기준 (오프셋 0).",
  GWP_DB_PhaseProgressTooltip: "왼쪽: 최소 시간. 깜빡임: 전환 준비 완료.",
  GWP_DB_MinDurationTooltip: "50%에서 최소 시간 도달. 언제든 전환 가능.",
  GWP_DB_PhaseXofY: "페이즈 {0}/{1}",

  // V147: Traffic Summary
  TrafficSummary: "교통 개요",
  VehiclesPerHour: "Ø 처리량",
  VehiclesPerMinute: "차량/분",
  Approaches: "진입로",
  IncomingLanes: "진입 차선",
  IncomingLanesTooltip: "교차로로 진입하는 물리적 차선.",
  OccupiedLanes: "점유 차선",
  OccupiedLanesTooltip: "대기 차량이 있는 점유 차선 수.",
  OccupiedPedestrianLanes: "보행자 차선 점유",
  TrafficFlowLow: "교통량 적음",
  TrafficFlowMedium: "교통량 보통",
  TrafficFlowHigh: "교통량 많음",
  WaitingVehicles: "대기 차량",
  WaitingVehiclesTooltip: "대기 중인 차량 수 (평균).",
  PeakHour: "피크 (24h)",
  PeakHourTooltip: "지난 24시간 중 가장 교통량이 많았던 시간.",
  MaxVPH: "최대 V/h (24h)",
  MaxVPHTooltip: "지난 24시간 최대 차량/시간.",
  VPH_InfoEstimate: "차선 수와 점유율 기반 추정.",
  VPH_InfoRealData: "실제 차량 수의 이동 평균.",
  ChartDisabledTooltip: "'사용자 정의 페이즈'를 활성화하여 데이터 수집",
  ChartCollectingTooltip: "데이터 수집 중... 약 30분 후 첫 값",
  ChartActiveTooltip: "24시간 교통 기록",
  CustomPhaseRequiredTooltip: "이 교차로에서 '사용자 정의 페이즈'를 활성화해야 합니다.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "페이즈 삭제?",
};
