export default {
  TrafficSignal: "Verkeerslicht",
  ModDefault: "Standaard",
  Vanilla: "Vanilla",
  SplitPhasing: "Gesplitste fase",
  ProtectedRightTurns: "Beschermde rechtsaf",
  ProtectedLeftTurns: "Beschermde linksaf",
  Options: "Opties",
  ExclusivePedestrianPhase: "Exclusieve voetgangersfase",
  LaneDirectionTool: "Rijstrookrichting Tool (Experimenteel)",
  
  Add: "Fase toevoegen",
  Back: "Terug",
  ManualControl: "Handmatige bediening",
  CustomPhase: "Aangepaste fase",
  CustomPhaseEditor: "Aangepaste fasen bewerken",
  SelectFunction: "Selecteer functie",
  SelectFunctionDescription: "Kies een functie om je verkeersnetwerk te configureren.",
  EditIntersectionPhases: "Kruispuntfasen bewerken",
  IntersectionMonitor: "Kruispuntmonitor",
  DashboardComingSoon: "Binnenkort beschikbaar...",
  
  Close: "Sluiten",
  Open: "Openen",
  Reset: "Resetten",
  Save: "Opslaan",
  PleaseSave: "Sla wijzigingen op voordat je een ander kruispunt selecteert.",
  PleaseSelectJunction: "Selecteer een kruispunt",
  GiveWayToOncomingVehicles: "Voorrang geven aan tegemoetkomend verkeer",
  CustomPedestrianDurationMultiplier: "Duur voetgangersfase",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Afslaan bij rood toestaan",
  CanaryBuildWarning: "Let op: je gebruikt een canary-versie die bugs kan bevatten. Deze versie is alleen voor testen. NIET gebruiken voor normaal spelen.",
  LdtMigrationNotice: "Lane Direction Tool is vervangen door de Traffic mod van krzychu124. Installeer de Traffic mod om je instellingen automatisch over te zetten.",
  LdtRetirementNotice: "Lane Direction Tool is vervangen door de Traffic mod van krzychu124. Bedankt voor het gebruik van LDT.",
  
  PrioritiseTrack: "Voertuigen prioriteren",
  PrioritisePublicCar: "Openbaar vervoer prioriteren",
  PrioritisePedestrian: "Voetgangers prioriteren",
  PrioritiseBicycle: "Fietsers prioriteren",
  
  PrioritiseTrackTooltip: "Geeft prioriteit aan normale voertuigrijstroken (auto's, vrachtwagens) tijdens deze fase",
  PrioritisePublicCarTooltip: "Geeft prioriteit aan OV-rijstroken (bussen, trams) tijdens deze fase",
  PrioritisePedestrianTooltip: "Geeft prioriteit aan voetgangersoversteekplaatsen tijdens deze fase",
  PrioritiseBicycleTooltip: "Geeft prioriteit aan fietspaden tijdens deze fase",
  
  Adjustments: "Aanpassingen",
  MinimumDuration: "Min. duur",
  MaximumDuration: "Max. duur",
  TargetDurationMultiplier: "Doelduur",
  LaneOccupiedMultiplier: "Rijstrookbezetting",
  IntervalExponent: "Interval-exponent",
  
  MinimumDurationTooltip: "Minimale groentijd. Het licht blijft minstens zo lang groen, ook bij weinig verkeer.",
  MaximumDurationTooltip: "Maximale groentijd. Na deze tijd schakelt het licht, ook als er nog verkeer wacht.",
  TargetDurationMultiplierTooltip: "Beïnvloedt de lengte van de groenfase. 1x = Normaal, 2x = Dubbele lengte bij drukte, 0.5x = Korter.",
  LaneOccupiedMultiplierTooltip: "Bepaalt hoeveel volle rijstroken de prioriteit verhogen. Hoger = Files lossen sneller op.",
  IntervalExponentTooltip: "Eerlijkheidsinstelling. Hoger = Fasen die langer wachtten krijgen meer prioriteit.",
  
  Statistics: "Statistieken",
  Timer: "Timer",
  Priority: "Prioriteit",
  LastRun: "Laatste cyclus",
  CarFlow: "Voertuigstroom",
  LanesOccupied: "Bezette rijstroken",
  WeightedWaiting: "Gewogen wachttijd",
  
  TimerTooltip: "Huidige timer / Doelduur",
  PriorityTooltip: "Huidige prioriteitswaarde van deze fase",
  LastRunTooltip: "Aantal beurten sinds deze fase laatst liep",
  CarFlowTooltip: "Huidige voertuigstroom door deze fase",
  LanesOccupiedTooltip: "Aantal bezette rijstroken (voertuigen, OV, rails, voetgangers)",
  WeightedWaitingTooltip: "Gewogen wachttijd van voertuigen bij deze fase",
  
  EndPhasePrematurely: "Fase nu beëindigen",
  PhaseEndRequested: "Fase-einde aangevraagd",
  SelectAll: "Alles selecteren",
  DeselectAll: "Selectie opheffen",
  CopyPhases: "Fasen kopiëren",
  PastePhases: "Fasen plakken",
  DeleteSelectedPhases: "Geselecteerde verwijderen",
  ClearClipboard: "Klembord wissen",
  
  SelectAllTooltip: "Alle fasen selecteren om te kopiëren of verwijderen",
  CopyPhasesTooltip: "Geselecteerde fasen naar klembord kopiëren",
  PastePhasesTooltip: "Fasen van klembord plakken",
  DeleteSelectedPhasesTooltip: "Geselecteerde fasen permanent verwijderen",
  ClearClipboardTooltip: "Klembord wissen om per ongeluk plakken te voorkomen",

  GreenWave: "Groene Golf",
  GreenWaveButton: "Groene Golf",
  SyncGroup: "Synchronisatiegroep",
  NoSyncGroup: "Geen Groep",
  CreateNewGroup: "Nieuwe Groep Maken",
  CycleOffset: "Cyclus-Offset",
  UseSyncedCycle: "Synchronisatie Activeren",
  TotalCycleDuration: "Totale Cyclusduur",
  BaseCycleDuration: "Basiscyclus",
  IntersectionsInGroup: "Kruispunten",
  NewGroupName: "Nieuwe Groep",
  DeleteGroup: "Groep Verwijderen",
  RenameGroup: "Hernoemen",
  OpenGreenWavePanel: "Groene Golf Openen",
  GreenWavePanelActive: "Groene Golf Actief",
  
  PhaseMode: "Fasemodus",
  LegacyMode: "Standaard (Prioriteit)",
  LegacyModeHint: "Volgende fase op basis van verkeersvraag",
  LegacyModeTooltip: "Fasen wisselen op basis van prioriteit - wachtende voertuigen en voetgangers bepalen de volgende fase. Standaard spelgedrag.",
  SequentialMode: "Sequentieel (Volgorde)",
  SequentialModeHint: "Fasen 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Fasen lopen op volgorde: 1 → 2 → 3 → 4 → 1... Vaste, voorspelbare volgorde. Vereist voor Groene Golf.",
  GreenWaveForcesSequential: "Groene Golf vereist sequentiële modus",
  
  SyncSettings: "Sync-instellingen",
  SyncPhase: "Sync-fase",
  SyncPhaseTooltip: "Selecteer welke fase te synchroniseren. Handig voor afslagstroken.",
  OffsetCalculator: "Offset Calculator",
  Distance: "Afstand",
  Speed: "Snelheid",
  RecommendedOffset: "Aanbevolen",
  Apply: "Toepassen",
  OwnCycle: "Eigen Cyclus",
  GroupBase: "Groepsbasis",
  AutoFactor: "Auto-Factor",
  AutoFactorTooltip: "Verhouding tussen eigen cyclus en groepsbasis. Verschillende cycluslengtes worden automatisch geschaald.",
  Intersections: "Kruispunten",
  NoGroupsYet: "Nog geen groepen aangemaakt",
  Information: "Informatie",
  
  GreenWaveTooltip: "Synchroniseer meerdere kruispunten voor een groene golf effect",
  GreenWaveTooltipActive: "Synchroniseer meerdere kruispunten langs een weg zodat voertuigen kunnen doorrijden zonder te stoppen tijdens een groene golf.",
  GreenWaveTooltipDisabled: "Groene Golf is alleen beschikbaar wanneer 'Aangepaste Fasen' is ingeschakeld voor dit kruispunt. Selecteer eerst 'Aangepaste Fasen'.",
  SyncGroupTooltip: "Selecteer een synchronisatiegroep voor dit kruispunt",
  CycleOffsetTooltip: "Tijdverschuiving in seconden ten opzichte van de groepstimer. Verschillende offsets creëren de groene golf.",
  UseSyncedCycleTooltip: "Activeert synchronisatie met de geselecteerde groep",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Kruispunt",
  GWP_TabGroups: "Groepen",
  GWP_TabDashboard: "Dashboard",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Synchronisatie actief",
  GWP_NotSynced: "Niet gesynchroniseerd",

  // Green Wave Panel - Labels
  GWP_NodeId: "Knooppunt ID (Kruispunt)",
  GWP_Group: "Groep",
  GWP_Offset: "Offset",
  GWP_AssignSyncGroup: "Syncgroep Toewijzen",
  GWP_NoGroupSelected: "Geen groep geselecteerd",
  GWP_NoGroup: "Geen Groep",
  GWP_NewGroup: "+ Nieuwe Groep",
  GWP_Rename: "Hernoemen",
  GWP_EnableSync: "Sync Inschakelen",
  GWP_CycleOffset: "Cyclus Offset",
  GWP_Tempo: "Snelheid",
  GWP_Recommended: "Aanbevolen:",
  GWP_GameTime: "Spel",
  GWP_RealTime: "Echt",
  GWP_PhaseHint: "Fase #1 moet de hoofdrichting zijn voor de Groene Golf!",
  GWP_AutoSave: "Wijzigingen worden automatisch opgeslagen",
  GWP_SelectIntersection: "Selecteer een kruispunt.",
  GWP_SearchGroups: "Groepen zoeken...",
  GWP_NoMatches: "Geen overeenkomsten voor",
  GWP_RemoveFromGroup: "Uit Groep Verwijderen",
  GWP_DeleteGroup: "Groep Verwijderen",
  GWP_NoIntersections: "Kruispunten",
  GWP_GroupsHint: "Groepen zonder kruispunten kunnen worden verwijderd. Voeg kruispunten toe in het tabblad 'Kruispunt'.",
  GWP_SelectGroupHint: "Selecteer een groep in het tabblad 'Kruispunt' om details te zien.",
  GWP_AddIntersectionsHint: "Deze groep heeft nog geen kruispunten. Ga naar het tabblad 'Kruispunt' en voeg kruispunten toe!",
  GWP_RemovedFromGroup: "Verwijderd uit groep",
  GWP_AddedToGroup: "Toegevoegd aan",
  GWP_SyncEnabled: "Synchronisatie ingeschakeld!",
  GWP_SyncDisabled: "Synchronisatie uitgeschakeld",
  GWP_NewGroupCreated: "Nieuwe groep aangemaakt!",
  GWP_GroupRenamed: "Groep hernoemd naar",
  GWP_GroupDeleted: "Groep verwijderd",
  GWP_IntersectionRemoved: "Kruispunt verwijderd uit groep",
  GWP_OffsetSet: "Offset ingesteld op",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Schakelt synchronisatie van dit kruispunt met de groep in.",
  GWP_TT_SyncPhase: "Sync-fase",
  GWP_TT_CycleOffset: "Tijdoffset in seconden vanaf de basiscyclus van de groep.",
  GWP_TT_Distance: "Afstand",
  GWP_TT_Speed: "Snelheid",
  GWP_TT_OwnCycle: "Eigen Cyclus",
  GWP_TT_GroupBase: "Basiscyclus van de groep (speltijd).",
  GWP_TT_Intersections: "Kruispunten",
  GWP_MoveUp: "Omhoog",
  GWP_MoveDown: "Omlaag",
  GWP_ManageGroups: "Syncgroepen Beheren",
  GWP_CreateNewGroup: "+ Nieuwe Groep Maken",
  GWP_DB_Intersection: "Kruispunt",
  GWP_DB_Reference: "REFERENTIE",
  GWP_DB_Phases: "Fasen",
  GWP_DB_Green: "GROEN",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "UIT",
  GWP_DB_SyncWaiting: "Sync actief - wachtend",
  GWP_DB_GreenWaveActive: "Groene Golf actief!",
  GWP_DB_ReadyToSwitch: "Klaar om te wisselen",
  GWP_DB_Offset: "OFFSET",
  GWP_DB_Cycle: "CYCLUS",
  GWP_DB_Roads: "WEGEN",
  GWP_DB_Lanes: "STROKEN",
  GWP_DB_Pedestrians: "VOETG.",
  GWP_DB_OffsetDelta: "Offset",
  GWP_DB_BaseCycle: "Basiscyclus",
  GWP_DB_GreenWaveLabel: "Groene Golf",
  GWP_DB_SyncActiveLabel: "Sync Actief",
  GWP_DB_ReorderHint: "Gebruik de pijltjestoetsen om de volgorde aan te passen. Het eerste kruispunt is de referentie (Offset 0).",
  GWP_DB_PhaseProgressTooltip: "Links: Minimale duur. Knipperend: Fase klaar om te wisselen.",
  GWP_DB_MinDurationTooltip: "Bij 50% is de minimale duur bereikt. De fase kan elk moment wisselen.",
  GWP_DB_PhaseXofY: "Fase {0} van {1}",

  // V147: Traffic Summary
  TrafficSummary: "Verkeersoverzicht",
  VehiclesPerHour: "Ø Doorvoer",
  VehiclesPerMinute: "Voertuigen/Min",
  Approaches: "Aanrijroutes",
  IncomingLanes: "Inkomende Rijstroken",
  IncomingLanesTooltip: "Fysieke rijstroken die de kruising ingaan.",
  OccupiedLanes: "Bezette Rijstroken",
  OccupiedLanesTooltip: "Aantal bezette rijstroken met wachtende voertuigen.",
  OccupiedPedestrianLanes: "Voetg. Rijstr. Bez.",
  TrafficFlowLow: "Weinig Verkeer",
  TrafficFlowMedium: "Matig Verkeer",
  TrafficFlowHigh: "Druk Verkeer",
  WaitingVehicles: "Wachtende Voertuigen",
  WaitingVehiclesTooltip: "Huidig aantal wachtende voertuigen (gemiddeld).",
  PeakHour: "Piek (24u)",
  PeakHourTooltip: "Tijdstip met het hoogste volume in de afgelopen 24 uur.",
  MaxVPH: "Max V/u (24u)",
  MaxVPHTooltip: "Hoogste voertuigen/uur in de afgelopen 24 uur.",
  VPH_InfoEstimate: "Schatting gebaseerd op rijstroken en bezetting.",
  VPH_InfoRealData: "Voortschrijdend gemiddelde van werkelijke telling.",
  ChartDisabledTooltip: "Activeer 'Aangepaste Fase' om gegevens te verzamelen",
  ChartCollectingTooltip: "Gegevens verzamelen... Eerste waarden over ~30 min",
  ChartActiveTooltip: "24-uurs verkeersgeschiedenis",
  CustomPhaseRequiredTooltip: "Vereist dat 'Aangepaste Fasen' is ingeschakeld voor dit kruispunt.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Fase verwijderen?",
};
