export default {
  TrafficSignal: "Verkeerslicht",
  ModDefault: "Standaard",
  Vanilla: "Vanilla",
  SplitPhasing: "Gesplitste fase",
  ProtectedRightTurns: "Beschermde rechtsaf",
  ProtectedLeftTurns: "Beschermde linksaf",
  Options: "Opties",
  ExclusivePedestrianPhase: "Exclusieve voetgangersfase",
  LaneDirectionTool: "Rijstrookrichting Tool (Experimenteel)",
  
  Add: "Fase toevoegen",
  Back: "Terug",
  ManualControl: "Handmatige bediening",
  CustomPhase: "Aangepaste fase",
  CustomPhaseEditor: "Aangepaste fasen bewerken",
  SelectFunction: "Selecteer functie",
  SelectFunctionDescription: "Kies een functie om je verkeersnetwerk te configureren.",
  EditIntersectionPhases: "Kruispuntfasen bewerken",
  IntersectionMonitor: "Kruispuntmonitor",
  DashboardComingSoon: "Binnenkort beschikbaar...",
  
  Close: "Sluiten",
  Open: "Openen",
  Reset: "Resetten",
  Save: "Opslaan",
  PleaseSave: "Sla wijzigingen op voordat je een ander kruispunt selecteert.",
  PleaseSelectJunction: "Selecteer een kruispunt",
  GiveWayToOncomingVehicles: "Voorrang geven aan tegemoetkomend verkeer",
  CustomPedestrianDurationMultiplier: "Duur voetgangersfase",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Afslaan bij rood toestaan",
  CanaryBuildWarning: "Let op: je gebruikt een canary-versie die bugs kan bevatten. Deze versie is alleen voor testen. NIET gebruiken voor normaal spelen.",
  LdtMigrationNotice: "Lane Direction Tool is vervangen door de Traffic mod van krzychu124. Installeer de Traffic mod om je instellingen automatisch over te zetten.",
  LdtRetirementNotice: "Lane Direction Tool is vervangen door de Traffic mod van krzychu124. Bedankt voor het gebruik van LDT.",
  
  PrioritiseTrack: "Voertuigen prioriteren",
  PrioritisePublicCar: "Openbaar vervoer prioriteren",
  PrioritisePedestrian: "Voetgangers prioriteren",
  PrioritiseBicycle: "Fietsers prioriteren",
  
  PrioritiseTrackTooltip: "Geeft prioriteit aan normale voertuigrijstroken (auto's, vrachtwagens) tijdens deze fase",
  PrioritisePublicCarTooltip: "Geeft prioriteit aan OV-rijstroken (bussen, trams) tijdens deze fase",
  PrioritisePedestrianTooltip: "Geeft prioriteit aan voetgangersoversteekplaatsen tijdens deze fase",
  PrioritiseBicycleTooltip: "Geeft prioriteit aan fietspaden tijdens deze fase",
  
  Adjustments: "Aanpassingen",
  MinimumDuration: "Min. duur",
  MaximumDuration: "Max. duur",
  TargetDurationMultiplier: "Doelduur",
  LaneOccupiedMultiplier: "Rijstrookbezetting",
  IntervalExponent: "Interval-exponent",
  
  MinimumDurationTooltip: "Minimale groentijd. Het licht blijft minstens zo lang groen, ook bij weinig verkeer.",
  MaximumDurationTooltip: "Maximale groentijd. Na deze tijd schakelt het licht, ook als er nog verkeer wacht.",
  TargetDurationMultiplierTooltip: "Beïnvloedt de lengte van de groenfase. 1x = Normaal, 2x = Dubbele lengte bij drukte, 0.5x = Korter.",
  LaneOccupiedMultiplierTooltip: "Bepaalt hoeveel volle rijstroken de prioriteit verhogen. Hoger = Files lossen sneller op.",
  IntervalExponentTooltip: "Eerlijkheidsinstelling. Hoger = Fasen die langer wachtten krijgen meer prioriteit.",
  
  Statistics: "Statistieken",
  Timer: "Timer",
  Priority: "Prioriteit",
  LastRun: "Laatste cyclus",
  CarFlow: "Voertuigstroom",
  LanesOccupied: "Bezette rijstroken",
  WeightedWaiting: "Gewogen wachttijd",
  
  TimerTooltip: "Huidige timer / Doelduur",
  PriorityTooltip: "Huidige prioriteitswaarde van deze fase",
  LastRunTooltip: "Aantal beurten sinds deze fase laatst liep",
  CarFlowTooltip: "Huidige voertuigstroom door deze fase",
  LanesOccupiedTooltip: "Aantal bezette rijstroken (voertuigen, OV, rails, voetgangers)",
  WeightedWaitingTooltip: "Gewogen wachttijd van voertuigen bij deze fase",
  
  EndPhasePrematurely: "Fase nu beëindigen",
  PhaseEndRequested: "Fase-einde aangevraagd",
  SelectAll: "Alles selecteren",
  DeselectAll: "Selectie opheffen",
  CopyPhases: "Fasen kopiëren",
  PastePhases: "Fasen plakken",
  DeleteSelectedPhases: "Geselecteerde verwijderen",
  ClearClipboard: "Klembord wissen",
  
  SelectAllTooltip: "Alle fasen selecteren om te kopiëren of verwijderen",
  CopyPhasesTooltip: "Geselecteerde fasen naar klembord kopiëren",
  PastePhasesTooltip: "Fasen van klembord plakken",
  DeleteSelectedPhasesTooltip: "Geselecteerde fasen permanent verwijderen",
  ClearClipboardTooltip: "Klembord wissen om per ongeluk plakken te voorkomen",

  GreenWave: "Groene Golf",
  GreenWaveButton: "Groene Golf",
  SyncGroup: "Synchronisatiegroep",
  NoSyncGroup: "Geen Groep",
  CreateNewGroup: "Nieuwe Groep Maken",
  CycleOffset: "Cyclus-Offset",
  UseSyncedCycle: "Synchronisatie Activeren",
  TotalCycleDuration: "Totale Cyclusduur",
  BaseCycleDuration: "Basiscyclus",
  IntersectionsInGroup: "Kruispunten",
  NewGroupName: "Nieuwe Groep",
  DeleteGroup: "Groep Verwijderen",
  RenameGroup: "Hernoemen",
  OpenGreenWavePanel: "Groene Golf Openen",
  GreenWavePanelActive: "Groene Golf Actief",
  
  PhaseMode: "Fasemodus",
  LegacyMode: "Standaard (Prioriteit)",
  LegacyModeHint: "Volgende fase op basis van verkeersvraag",
  LegacyModeTooltip: "Fasen wisselen op basis van prioriteit - wachtende voertuigen en voetgangers bepalen de volgende fase. Standaard spelgedrag.",
  SequentialMode: "Sequentieel (Volgorde)",
  SequentialModeHint: "Fasen 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Fasen lopen op volgorde: 1 → 2 → 3 → 4 → 1... Vaste, voorspelbare volgorde. Vereist voor Groene Golf.",
  GreenWaveForcesSequential: "Groene Golf vereist sequentiële modus",
  
  SyncSettings: "Synchronisatie-instellingen",
  SyncPhase: "Synchronisatiefase",
  SyncPhaseTooltip: "Selecteer welke fase gesynchroniseerd moet worden. Handig voor afslagstroken.",
  OffsetCalculator: "Offset-Calculator",
  Distance: "Afstand",
  Speed: "Snelheid",
  RecommendedOffset: "Aanbevolen",
  Apply: "Toepassen",
  OwnCycle: "Eigen Cyclus",
  GroupBase: "Groepsbasis",
  AutoFactor: "Auto-Factor",
  AutoFactorTooltip: "Verhouding tussen eigen cyclus en groepsbasis. Verschillende cycluslengtes worden automatisch geschaald.",
  Intersections: "Kruispunten",
  NoGroupsYet: "Nog geen groepen aangemaakt",
  Information: "Informatie",
  
  GreenWaveTooltip: "Synchroniseer meerdere kruispunten voor een groene golf effect",
  GreenWaveTooltipActive: "Synchroniseer meerdere kruispunten langs een weg zodat voertuigen kunnen doorrijden zonder te stoppen tijdens een groene golf.",
  GreenWaveTooltipDisabled: "Groene Golf is alleen beschikbaar wanneer 'Aangepaste Fasen' is ingeschakeld voor dit kruispunt. Selecteer eerst 'Aangepaste Fasen'.",
  SyncGroupTooltip: "Selecteer een synchronisatiegroep voor dit kruispunt",
  CycleOffsetTooltip: "Tijdverschuiving in seconden ten opzichte van de groepstimer. Verschillende offsets creëren de groene golf.",
  UseSyncedCycleTooltip: "Activeert synchronisatie met de geselecteerde groep",
};
