export default {
  TrafficSignal: "Sygnalizacja świetlna",
  ModDefault: "Domyślne",
  Vanilla: "Vanilla",
  SplitPhasing: "Faza podzielona",
  ProtectedRightTurns: "Chronione skręty w prawo",
  ProtectedLeftTurns: "Chronione skręty w lewo",
  Options: "Opcje",
  ExclusivePedestrianPhase: "Wyłączna faza dla pieszych",
  LaneDirectionTool: "Narzędzie kierunku pasa (Eksperymentalne)",
  
  Add: "Dodaj fazę",
  Back: "Wstecz",
  ManualControl: "Sterowanie ręczne",
  CustomPhase: "Faza niestandardowa",
  CustomPhaseEditor: "Edytuj fazy niestandardowe",
  SelectFunction: "Wybierz funkcję",
  SelectFunctionDescription: "Wybierz funkcję do konfiguracji sieci drogowej.",
  EditIntersectionPhases: "Edytuj fazy skrzyżowania",
  IntersectionMonitor: "Monitor skrzyżowania",
  DashboardComingSoon: "Wkrótce...",
  
  Close: "Zamknij",
  Open: "Otwórz",
  Reset: "Resetuj",
  Save: "Zapisz",
  PleaseSave: "Zapisz zmiany przed wybraniem innego skrzyżowania.",
  PleaseSelectJunction: "Wybierz skrzyżowanie",
  GiveWayToOncomingVehicles: "Ustąp pierwszeństwa pojazdom nadjeżdżającym",
  CustomPedestrianDurationMultiplier: "Czas fazy pieszych",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Zezwól na skręt na czerwonym",
  CanaryBuildWarning: "Uwaga: używasz wersji canary, która może zawierać błędy. Ta wersja jest tylko do testów. NIE używaj do normalnej gry.",
  LdtMigrationNotice: "Lane Direction Tool został zastąpiony przez mod Traffic od krzychu124. Zainstaluj mod Traffic, aby automatycznie przenieść ustawienia.",
  LdtRetirementNotice: "Lane Direction Tool został zastąpiony przez mod Traffic od krzychu124. Dziękujemy za korzystanie z LDT.",
  
  PrioritiseTrack: "Priorytet pojazdów",
  PrioritisePublicCar: "Priorytet transportu publicznego",
  PrioritisePedestrian: "Priorytet pieszych",
  PrioritiseBicycle: "Priorytet rowerzystów",
  
  PrioritiseTrackTooltip: "Daje priorytet pasom dla zwykłych pojazdów (samochody, ciężarówki) podczas tej fazy",
  PrioritisePublicCarTooltip: "Daje priorytet pasom transportu publicznego (autobusy, tramwaje) podczas tej fazy",
  PrioritisePedestrianTooltip: "Daje priorytet przejściom dla pieszych podczas tej fazy",
  PrioritiseBicycleTooltip: "Daje priorytet ścieżkom rowerowym podczas tej fazy",
  
  Adjustments: "Dostosowania",
  MinimumDuration: "Min. czas",
  MaximumDuration: "Max. czas",
  TargetDurationMultiplier: "Docelowy czas",
  LaneOccupiedMultiplier: "Zajętość pasów",
  IntervalExponent: "Wykładnik interwału",
  
  MinimumDurationTooltip: "Minimalny czas zielonego. Światło pozostaje zielone co najmniej tak długo, nawet przy małym ruchu.",
  MaximumDurationTooltip: "Maksymalny czas zielonego. Po tym czasie światło się zmienia, nawet jeśli ruch nadal czeka.",
  TargetDurationMultiplierTooltip: "Wpływa na długość fazy zielonej. 1x = Normalnie, 2x = Podwójna długość przy ruchu, 0.5x = Krócej.",
  LaneOccupiedMultiplierTooltip: "Kontroluje jak bardzo pełne pasy zwiększają priorytet. Wyżej = Korki rozładowują się szybciej.",
  IntervalExponentTooltip: "Ustawienie sprawiedliwości. Wyżej = Fazy które czekały dłużej mają większy priorytet.",
  
  Statistics: "Statystyki",
  Timer: "Timer",
  Priority: "Priorytet",
  LastRun: "Ostatni cykl",
  CarFlow: "Przepływ pojazdów",
  LanesOccupied: "Zajęte pasy",
  WeightedWaiting: "Ważone czekanie",
  
  TimerTooltip: "Aktualny timer / Docelowy czas",
  PriorityTooltip: "Aktualna wartość priorytetu tej fazy",
  LastRunTooltip: "Liczba tur od ostatniego uruchomienia tej fazy",
  CarFlowTooltip: "Aktualny przepływ pojazdów przez tę fazę",
  LanesOccupiedTooltip: "Liczba zajętych pasów (pojazdy, transport, tory, piesi)",
  WeightedWaitingTooltip: "Ważony czas oczekiwania pojazdów na tej fazie",
  
  EndPhasePrematurely: "Zakończ fazę teraz",
  PhaseEndRequested: "Żądanie zakończenia fazy",
  SelectAll: "Zaznacz wszystko",
  DeselectAll: "Odznacz wszystko",
  CopyPhases: "Kopiuj fazy",
  PastePhases: "Wklej fazy",
  DeleteSelectedPhases: "Usuń zaznaczone",
  ClearClipboard: "Wyczyść schowek",
  
  SelectAllTooltip: "Zaznacz wszystkie fazy do kopiowania lub usunięcia",
  CopyPhasesTooltip: "Kopiuj zaznaczone fazy do schowka",
  PastePhasesTooltip: "Wklej fazy ze schowka",
  DeleteSelectedPhasesTooltip: "Trwale usuń zaznaczone fazy",
  ClearClipboardTooltip: "Wyczyść schowek, aby uniknąć przypadkowego wklejenia",

  GreenWave: "Zielona Fala",
  GreenWaveButton: "Zielona Fala",
  SyncGroup: "Grupa Synchronizacji",
  NoSyncGroup: "Brak Grupy",
  CreateNewGroup: "Utwórz Nową Grupę",
  CycleOffset: "Przesunięcie Cyklu",
  UseSyncedCycle: "Włącz Synchronizację",
  TotalCycleDuration: "Całkowity Czas Cyklu",
  BaseCycleDuration: "Cykl Bazowy",
  IntersectionsInGroup: "Skrzyżowania",
  NewGroupName: "Nowa Grupa",
  DeleteGroup: "Usuń Grupę",
  RenameGroup: "Zmień nazwę",
  OpenGreenWavePanel: "Otwórz Zieloną Falę",
  GreenWavePanelActive: "Zielona Fala Aktywna",
  
  PhaseMode: "Tryb Fazy",
  LegacyMode: "Standardowy (Priorytet)",
  LegacyModeHint: "Następna faza na podstawie zapotrzebowania",
  LegacyModeTooltip: "Fazy przełączają się według priorytetu - oczekujące pojazdy i piesi określają następną fazę. Domyślne zachowanie gry.",
  SequentialMode: "Sekwencyjny (Kolejność)",
  SequentialModeHint: "Fazy 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Fazy uruchamiają się w kolejności: 1 → 2 → 3 → 4 → 1... Stała, przewidywalna sekwencja. Wymagane dla Zielonej Fali.",
  GreenWaveForcesSequential: "Zielona Fala wymaga trybu sekwencyjnego",
  
  SyncSettings: "Ustaw. Synchr.",
  SyncPhase: "Faza Synchr.",
  SyncPhaseTooltip: "Wybierz fazę do synchronizacji. Przydatne dla pasów skrętu.",
  OffsetCalculator: "Kalkulator Przesunięcia",
  Distance: "Odległość",
  Speed: "Prędkość",
  RecommendedOffset: "Zalecane",
  Apply: "Zastosuj",
  OwnCycle: "Własny Cykl",
  GroupBase: "Baza Grupy",
  AutoFactor: "Auto-Faktor",
  AutoFactorTooltip: "Stosunek między własnym cyklem a bazą grupy. Różne długości cykli są automatycznie skalowane.",
  Intersections: "Skrzyżowania",
  NoGroupsYet: "Nie utworzono jeszcze żadnych grup",
  Information: "Informacje",
  
  GreenWaveTooltip: "Synchronizuj wiele skrzyżowań dla efektu zielonej fali",
  GreenWaveTooltipActive: "Synchronizuj wiele skrzyżowań wzdłuż drogi, aby pojazdy mogły przejeżdżać bez zatrzymywania podczas zielonej fali.",
  GreenWaveTooltipDisabled: "Zielona Fala jest dostępna tylko gdy 'Fazy Niestandardowe' są włączone dla tego skrzyżowania. Najpierw wybierz 'Fazy Niestandardowe'.",
  SyncGroupTooltip: "Wybierz grupę synchronizacji dla tego skrzyżowania",
  CycleOffsetTooltip: "Przesunięcie czasowe w sekundach od timera grupy. Różne przesunięcia tworzą zieloną falę.",
  UseSyncedCycleTooltip: "Włącza synchronizację z wybraną grupą",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Skrzyżowanie",
  GWP_TabGroups: "Grupy",
  GWP_TabDashboard: "Panel",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Synchronizacja aktywna",
  GWP_NotSynced: "Niesynchronizowane",

  // Green Wave Panel - Labels
  GWP_NodeId: "ID węzła (Skrzyżowanie)",
  GWP_Group: "Grupa",
  GWP_Offset: "Przesunięcie",
  GWP_AssignSyncGroup: "Przypisz Grupę Synchr.",
  GWP_NoGroupSelected: "Nie wybrano grupy",
  GWP_NoGroup: "Brak Grupy",
  GWP_NewGroup: "+ Nowa Grupa",
  GWP_Rename: "Zmień nazwę",
  GWP_EnableSync: "Włącz Synchr.",
  GWP_CycleOffset: "Przesunięcie Cyklu",
  GWP_Tempo: "Prędkość",
  GWP_Recommended: "Zalecane:",
  GWP_GameTime: "Gra",
  GWP_RealTime: "Rzecz.",
  GWP_PhaseHint: "Faza #1 powinna być głównym kierunkiem Zielonej Fali!",
  GWP_AutoSave: "Zmiany są zapisywane automatycznie",
  GWP_SelectIntersection: "Proszę wybrać skrzyżowanie.",
  GWP_SearchGroups: "Szukaj grup...",
  GWP_NoMatches: "Brak wyników dla",
  GWP_RemoveFromGroup: "Usuń z Grupy",
  GWP_DeleteGroup: "Usuń Grupę",
  GWP_NoIntersections: "Skrzyżowania",
  GWP_GroupsHint: "Grupy bez skrzyżowań można usunąć. Dodaj skrzyżowania w zakładce 'Skrzyżowanie'.",
  GWP_SelectGroupHint: "Wybierz grupę w zakładce 'Skrzyżowanie', aby zobaczyć szczegóły.",
  GWP_AddIntersectionsHint: "Ta grupa nie ma jeszcze skrzyżowań. Przejdź do zakładki 'Skrzyżowanie' i dodaj skrzyżowania!",
  GWP_RemovedFromGroup: "Usunięto z grupy",
  GWP_AddedToGroup: "Dodano do",
  GWP_SyncEnabled: "Synchronizacja włączona!",
  GWP_SyncDisabled: "Synchronizacja wyłączona",
  GWP_NewGroupCreated: "Nowa grupa utworzona!",
  GWP_GroupRenamed: "Grupa przemianowana na",
  GWP_GroupDeleted: "Grupa usunięta",
  GWP_IntersectionRemoved: "Skrzyżowanie usunięte z grupy",
  GWP_OffsetSet: "Przesunięcie ustawione na",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Włącza synchronizację tego skrzyżowania z grupą.",
  GWP_TT_SyncPhase: "Faza Synchr.",
  GWP_TT_CycleOffset: "Przesunięcie czasowe w sekundach od cyklu bazowego grupy.",
  GWP_TT_Distance: "Odległość",
  GWP_TT_Speed: "Prędkość",
  GWP_TT_OwnCycle: "Własny Cykl",
  GWP_TT_GroupBase: "Cykl bazowy grupy (czas gry).",
  GWP_TT_Intersections: "Skrzyżowania",
  GWP_MoveUp: "W górę",
  GWP_MoveDown: "W dół",
  GWP_ManageGroups: "Zarządzaj Grupami Synchr.",
  GWP_CreateNewGroup: "+ Utwórz Nową Grupę",
  GWP_DB_Intersection: "Skrzyżowanie",
  GWP_DB_Reference: "ODNIESIENIE",
  GWP_DB_Phases: "Fazy",
  GWP_DB_Green: "ZIELONY",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "WYŁ",
  GWP_DB_SyncWaiting: "Sync aktywny - oczekiwanie",
  GWP_DB_GreenWaveActive: "Zielona Fala aktywna!",
  GWP_DB_ReadyToSwitch: "Gotowy do zmiany",
  GWP_DB_Offset: "PRZESUNIĘCIE",
  GWP_DB_Cycle: "CYKL",
  GWP_DB_Roads: "DROGI",
  GWP_DB_Lanes: "PASY",
  GWP_DB_Pedestrians: "PIESI",
  GWP_DB_OffsetDelta: "Przesunięcie",
  GWP_DB_BaseCycle: "Cykl Bazowy",
  GWP_DB_GreenWaveLabel: "Zielona Fala",
  GWP_DB_SyncActiveLabel: "Sync Aktywny",
  GWP_DB_ReorderHint: "Użyj strzałek aby dostosować kolejność. Pierwsze skrzyżowanie jest odniesieniem (Przesunięcie 0).",
  GWP_DB_PhaseProgressTooltip: "Lewo: Minimalny czas. Miganie: Faza gotowa do zmiany.",
  GWP_DB_MinDurationTooltip: "Przy 50% osiągnięto minimalny czas. Faza może się zmienić w każdej chwili.",
  GWP_DB_PhaseXofY: "Faza {0} z {1}",

  // V147: Traffic Summary
  TrafficSummary: "Przegląd Ruchu",
  VehiclesPerHour: "Ø Przepływ",
  VehiclesPerMinute: "Pojazdy/Min",
  Approaches: "Dojazdy",
  IncomingLanes: "Pasy Wjazdowe",
  IncomingLanesTooltip: "Fizyczne pasy wjazdowe do skrzyżowania.",
  OccupiedLanes: "Zajęte Pasy",
  OccupiedLanesTooltip: "Liczba zajętych pasów z oczekującymi pojazdami.",
  OccupiedPedestrianLanes: "Pasy Pieszych Zaj.",
  TrafficFlowLow: "Mały Ruch",
  TrafficFlowMedium: "Umiarkowany Ruch",
  TrafficFlowHigh: "Duży Ruch",
  WaitingVehicles: "Oczekujące Pojazdy",
  WaitingVehiclesTooltip: "Aktualna liczba oczekujących pojazdów (średnia).",
  PeakHour: "Szczyt (24h)",
  PeakHourTooltip: "Godzina z największym natężeniem w ciągu ostatnich 24 godzin.",
  MaxVPH: "Maks P/h (24h)",
  MaxVPHTooltip: "Największa liczba pojazdów/godzinę w ciągu ostatnich 24 godzin.",
  VPH_InfoEstimate: "Oszacowanie na podstawie pasów i zajętości.",
  VPH_InfoRealData: "Średnia krocząca rzeczywistej liczby pojazdów.",
  ChartDisabledTooltip: "Włącz 'Własną Fazę' aby zbierać dane",
  ChartCollectingTooltip: "Zbieranie danych... Pierwsze wartości za ~30 min",
  ChartActiveTooltip: "24-godzinna historia ruchu",
  CustomPhaseRequiredTooltip: "Wymaga włączenia 'Własnych Faz' dla tego skrzyżowania.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Usunąć fazę?",
};
