export default {
  TrafficSignal: "Sygnalizacja świetlna",
  ModDefault: "Domyślne",
  Vanilla: "Vanilla",
  SplitPhasing: "Faza podzielona",
  ProtectedRightTurns: "Chronione skręty w prawo",
  ProtectedLeftTurns: "Chronione skręty w lewo",
  Options: "Opcje",
  ExclusivePedestrianPhase: "Wyłączna faza dla pieszych",
  LaneDirectionTool: "Narzędzie kierunku pasa (Eksperymentalne)",
  
  Add: "Dodaj fazę",
  Back: "Wstecz",
  ManualControl: "Sterowanie ręczne",
  CustomPhase: "Faza niestandardowa",
  CustomPhaseEditor: "Edytuj fazy niestandardowe",
  SelectFunction: "Wybierz funkcję",
  SelectFunctionDescription: "Wybierz funkcję do konfiguracji sieci drogowej.",
  EditIntersectionPhases: "Edytuj fazy skrzyżowania",
  IntersectionMonitor: "Monitor skrzyżowania",
  DashboardComingSoon: "Wkrótce...",
  
  Close: "Zamknij",
  Open: "Otwórz",
  Reset: "Resetuj",
  Save: "Zapisz",
  PleaseSave: "Zapisz zmiany przed wybraniem innego skrzyżowania.",
  PleaseSelectJunction: "Wybierz skrzyżowanie",
  GiveWayToOncomingVehicles: "Ustąp pierwszeństwa pojazdom nadjeżdżającym",
  CustomPedestrianDurationMultiplier: "Czas fazy pieszych",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Zezwól na skręt na czerwonym",
  CanaryBuildWarning: "Uwaga: używasz wersji canary, która może zawierać błędy. Ta wersja jest tylko do testów. NIE używaj do normalnej gry.",
  LdtMigrationNotice: "Lane Direction Tool został zastąpiony przez mod Traffic od krzychu124. Zainstaluj mod Traffic, aby automatycznie przenieść ustawienia.",
  LdtRetirementNotice: "Lane Direction Tool został zastąpiony przez mod Traffic od krzychu124. Dziękujemy za korzystanie z LDT.",
  
  PrioritiseTrack: "Priorytet pojazdów",
  PrioritisePublicCar: "Priorytet transportu publicznego",
  PrioritisePedestrian: "Priorytet pieszych",
  PrioritiseBicycle: "Priorytet rowerzystów",
  
  PrioritiseTrackTooltip: "Daje priorytet pasom dla zwykłych pojazdów (samochody, ciężarówki) podczas tej fazy",
  PrioritisePublicCarTooltip: "Daje priorytet pasom transportu publicznego (autobusy, tramwaje) podczas tej fazy",
  PrioritisePedestrianTooltip: "Daje priorytet przejściom dla pieszych podczas tej fazy",
  PrioritiseBicycleTooltip: "Daje priorytet ścieżkom rowerowym podczas tej fazy",
  
  Adjustments: "Dostosowania",
  MinimumDuration: "Min. czas",
  MaximumDuration: "Max. czas",
  TargetDurationMultiplier: "Docelowy czas",
  LaneOccupiedMultiplier: "Zajętość pasów",
  IntervalExponent: "Wykładnik interwału",
  
  MinimumDurationTooltip: "Minimalny czas zielonego. Światło pozostaje zielone co najmniej tak długo, nawet przy małym ruchu.",
  MaximumDurationTooltip: "Maksymalny czas zielonego. Po tym czasie światło się zmienia, nawet jeśli ruch nadal czeka.",
  TargetDurationMultiplierTooltip: "Wpływa na długość fazy zielonej. 1x = Normalnie, 2x = Podwójna długość przy ruchu, 0.5x = Krócej.",
  LaneOccupiedMultiplierTooltip: "Kontroluje jak bardzo pełne pasy zwiększają priorytet. Wyżej = Korki rozładowują się szybciej.",
  IntervalExponentTooltip: "Ustawienie sprawiedliwości. Wyżej = Fazy które czekały dłużej mają większy priorytet.",
  
  Statistics: "Statystyki",
  Timer: "Timer",
  Priority: "Priorytet",
  LastRun: "Ostatni cykl",
  CarFlow: "Przepływ pojazdów",
  LanesOccupied: "Zajęte pasy",
  WeightedWaiting: "Ważone czekanie",
  
  TimerTooltip: "Aktualny timer / Docelowy czas",
  PriorityTooltip: "Aktualna wartość priorytetu tej fazy",
  LastRunTooltip: "Liczba tur od ostatniego uruchomienia tej fazy",
  CarFlowTooltip: "Aktualny przepływ pojazdów przez tę fazę",
  LanesOccupiedTooltip: "Liczba zajętych pasów (pojazdy, transport, tory, piesi)",
  WeightedWaitingTooltip: "Ważony czas oczekiwania pojazdów na tej fazie",
  
  EndPhasePrematurely: "Zakończ fazę teraz",
  PhaseEndRequested: "Żądanie zakończenia fazy",
  SelectAll: "Zaznacz wszystko",
  DeselectAll: "Odznacz wszystko",
  CopyPhases: "Kopiuj fazy",
  PastePhases: "Wklej fazy",
  DeleteSelectedPhases: "Usuń zaznaczone",
  ClearClipboard: "Wyczyść schowek",
  
  SelectAllTooltip: "Zaznacz wszystkie fazy do kopiowania lub usunięcia",
  CopyPhasesTooltip: "Kopiuj zaznaczone fazy do schowka",
  PastePhasesTooltip: "Wklej fazy ze schowka",
  DeleteSelectedPhasesTooltip: "Trwale usuń zaznaczone fazy",
  ClearClipboardTooltip: "Wyczyść schowek, aby uniknąć przypadkowego wklejenia",

  GreenWave: "Zielona Fala",
  GreenWaveButton: "Zielona Fala",
  SyncGroup: "Grupa Synchronizacji",
  NoSyncGroup: "Brak Grupy",
  CreateNewGroup: "Utwórz Nową Grupę",
  CycleOffset: "Przesunięcie Cyklu",
  UseSyncedCycle: "Włącz Synchronizację",
  TotalCycleDuration: "Całkowity Czas Cyklu",
  BaseCycleDuration: "Cykl Bazowy",
  IntersectionsInGroup: "Skrzyżowania",
  NewGroupName: "Nowa Grupa",
  DeleteGroup: "Usuń Grupę",
  RenameGroup: "Zmień nazwę",
  OpenGreenWavePanel: "Otwórz Zieloną Falę",
  GreenWavePanelActive: "Zielona Fala Aktywna",
  
  PhaseMode: "Tryb Fazy",
  LegacyMode: "Standardowy (Priorytet)",
  LegacyModeHint: "Następna faza na podstawie zapotrzebowania",
  LegacyModeTooltip: "Fazy przełączają się według priorytetu - oczekujące pojazdy i piesi określają następną fazę. Domyślne zachowanie gry.",
  SequentialMode: "Sekwencyjny (Kolejność)",
  SequentialModeHint: "Fazy 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Fazy uruchamiają się w kolejności: 1 → 2 → 3 → 4 → 1... Stała, przewidywalna sekwencja. Wymagane dla Zielonej Fali.",
  GreenWaveForcesSequential: "Zielona Fala wymaga trybu sekwencyjnego",
  
  SyncSettings: "Ustawienia Synchronizacji",
  SyncPhase: "Faza Synchronizacji",
  SyncPhaseTooltip: "Wybierz którą fazę synchronizować. Przydatne dla pasów skrętu.",
  OffsetCalculator: "Kalkulator Przesunięcia",
  Distance: "Odległość",
  Speed: "Prędkość",
  RecommendedOffset: "Zalecane",
  Apply: "Zastosuj",
  OwnCycle: "Własny Cykl",
  GroupBase: "Baza Grupy",
  AutoFactor: "Auto-Faktor",
  AutoFactorTooltip: "Stosunek między własnym cyklem a bazą grupy. Różne długości cykli są automatycznie skalowane.",
  Intersections: "Skrzyżowania",
  NoGroupsYet: "Nie utworzono jeszcze żadnych grup",
  Information: "Informacja",
  
  GreenWaveTooltip: "Synchronizuj wiele skrzyżowań dla efektu zielonej fali",
  GreenWaveTooltipActive: "Synchronizuj wiele skrzyżowań wzdłuż drogi, aby pojazdy mogły przejeżdżać bez zatrzymywania podczas zielonej fali.",
  GreenWaveTooltipDisabled: "Zielona Fala jest dostępna tylko gdy 'Fazy Niestandardowe' są włączone dla tego skrzyżowania. Najpierw wybierz 'Fazy Niestandardowe'.",
  SyncGroupTooltip: "Wybierz grupę synchronizacji dla tego skrzyżowania",
  CycleOffsetTooltip: "Przesunięcie czasowe w sekundach od timera grupy. Różne przesunięcia tworzą zieloną falę.",
  UseSyncedCycleTooltip: "Włącza synchronizację z wybraną grupą",
};
