export default {
  TrafficSignal: "Semáforo",
  ModDefault: "Padrão",
  Vanilla: "Vanilla",
  SplitPhasing: "Fase dividida",
  ProtectedRightTurns: "Conversões à direita protegidas",
  ProtectedLeftTurns: "Conversões à esquerda protegidas",
  Options: "Opções",
  ExclusivePedestrianPhase: "Fase exclusiva para pedestres",
  LaneDirectionTool: "Ferramenta de direção de faixa (Experimental)",
  
  Add: "Adicionar fase",
  Back: "Voltar",
  ManualControl: "Controle manual",
  CustomPhase: "Fase personalizada",
  CustomPhaseEditor: "Editar fases personalizadas",
  SelectFunction: "Selecionar função",
  SelectFunctionDescription: "Escolha uma função para configurar sua rede de tráfego.",
  EditIntersectionPhases: "Editar fases do cruzamento",
  IntersectionMonitor: "Monitor de cruzamento",
  DashboardComingSoon: "Em breve...",
  
  Close: "Fechar",
  Open: "Abrir",
  Reset: "Redefinir",
  Save: "Salvar",
  PleaseSave: "Salve as alterações antes de selecionar outro cruzamento.",
  PleaseSelectJunction: "Selecione um cruzamento",
  GiveWayToOncomingVehicles: "Dar passagem a veículos em sentido contrário",
  CustomPedestrianDurationMultiplier: "Duração da fase de pedestres",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Permitir conversão no vermelho",
  CanaryBuildWarning: "Atenção: você está usando uma versão canary que pode conter bugs. Esta versão é apenas para testes. NÃO use para jogo normal.",
  LdtMigrationNotice: "Lane Direction Tool foi substituído pelo mod Traffic de krzychu124. Instale o mod Traffic para transferir suas configurações automaticamente.",
  LdtRetirementNotice: "Lane Direction Tool foi substituído pelo mod Traffic de krzychu124. Obrigado por usar o LDT.",
  
  PrioritiseTrack: "Priorizar veículos",
  PrioritisePublicCar: "Priorizar transporte público",
  PrioritisePedestrian: "Priorizar pedestres",
  PrioritiseBicycle: "Priorizar ciclistas",
  
  PrioritiseTrackTooltip: "Dá prioridade às faixas de veículos normais (carros, caminhões) durante esta fase",
  PrioritisePublicCarTooltip: "Dá prioridade às faixas de transporte público (ônibus, bondes) durante esta fase",
  PrioritisePedestrianTooltip: "Dá prioridade às faixas de pedestres durante esta fase",
  PrioritiseBicycleTooltip: "Dá prioridade às ciclovias durante esta fase",
  
  Adjustments: "Ajustes",
  MinimumDuration: "Duração mín.",
  MaximumDuration: "Duração máx.",
  TargetDurationMultiplier: "Duração alvo",
  LaneOccupiedMultiplier: "Ocupação de faixas",
  IntervalExponent: "Expoente de intervalo",
  
  MinimumDurationTooltip: "Duração mínima do verde. O semáforo fica verde pelo menos este tempo, mesmo com pouco tráfego.",
  MaximumDurationTooltip: "Duração máxima do verde. Após este tempo, o semáforo muda mesmo se houver tráfego esperando.",
  TargetDurationMultiplierTooltip: "Afeta a duração da fase verde. 1x = Normal, 2x = Dobro da duração com tráfego, 0.5x = Mais curto.",
  LaneOccupiedMultiplierTooltip: "Controla quanto faixas cheias aumentam a prioridade. Maior = Congestionamentos resolvem mais rápido.",
  IntervalExponentTooltip: "Configuração de equidade. Maior = Fases que esperaram mais tempo têm mais prioridade.",
  
  Statistics: "Estatísticas",
  Timer: "Timer",
  Priority: "Prioridade",
  LastRun: "Último ciclo",
  CarFlow: "Fluxo de veículos",
  LanesOccupied: "Faixas ocupadas",
  WeightedWaiting: "Espera ponderada",
  
  TimerTooltip: "Timer atual / Duração alvo",
  PriorityTooltip: "Valor de prioridade atual desta fase",
  LastRunTooltip: "Número de turnos desde a última execução desta fase",
  CarFlowTooltip: "Fluxo atual de veículos nesta fase",
  LanesOccupiedTooltip: "Número de faixas ocupadas (veículos, transporte, trilhos, pedestres)",
  WeightedWaitingTooltip: "Tempo de espera ponderado dos veículos nesta fase",
  
  EndPhasePrematurely: "Terminar fase agora",
  PhaseEndRequested: "Fim de fase solicitado",
  SelectAll: "Selecionar tudo",
  DeselectAll: "Desmarcar tudo",
  CopyPhases: "Copiar fases",
  PastePhases: "Colar fases",
  DeleteSelectedPhases: "Excluir selecionadas",
  ClearClipboard: "Limpar área de transferência",
  
  SelectAllTooltip: "Selecionar todas as fases para copiar ou excluir",
  CopyPhasesTooltip: "Copiar fases selecionadas para a área de transferência",
  PastePhasesTooltip: "Colar fases da área de transferência",
  DeleteSelectedPhasesTooltip: "Excluir permanentemente as fases selecionadas",
  ClearClipboardTooltip: "Limpar área de transferência para evitar colagens acidentais",

  GreenWave: "Onda Verde",
  GreenWaveButton: "Onda Verde",
  SyncGroup: "Grupo de Sincronização",
  NoSyncGroup: "Sem Grupo",
  CreateNewGroup: "Criar Novo Grupo",
  CycleOffset: "Deslocamento do Ciclo",
  UseSyncedCycle: "Ativar Sincronização",
  TotalCycleDuration: "Duração Total do Ciclo",
  BaseCycleDuration: "Ciclo Base",
  IntersectionsInGroup: "Cruzamentos",
  NewGroupName: "Novo Grupo",
  DeleteGroup: "Excluir Grupo",
  RenameGroup: "Renomear",
  OpenGreenWavePanel: "Abrir Onda Verde",
  GreenWavePanelActive: "Onda Verde Ativa",
  
  PhaseMode: "Modo de Fase",
  LegacyMode: "Padrão (Prioridade)",
  LegacyModeHint: "Próxima fase baseada na demanda de tráfego",
  LegacyModeTooltip: "As fases mudam com base na prioridade - veículos e pedestres esperando determinam a próxima fase. Comportamento padrão do jogo.",
  SequentialMode: "Sequencial (Ordem)",
  SequentialModeHint: "Fases 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "As fases rodam em ordem: 1 → 2 → 3 → 4 → 1... Sequência fixa e previsível. Necessário para Onda Verde.",
  GreenWaveForcesSequential: "Onda Verde requer modo sequencial",
  
  SyncSettings: "Configurações de Sincronização",
  SyncPhase: "Fase de Sincronização",
  SyncPhaseTooltip: "Selecione qual fase sincronizar. Útil para faixas de conversão.",
  OffsetCalculator: "Calculadora de Deslocamento",
  Distance: "Distância",
  Speed: "Velocidade",
  RecommendedOffset: "Recomendado",
  Apply: "Aplicar",
  OwnCycle: "Ciclo Próprio",
  GroupBase: "Base do Grupo",
  AutoFactor: "Fator Automático",
  AutoFactorTooltip: "Proporção entre o ciclo próprio e a base do grupo. Diferentes durações de ciclo são escaladas automaticamente.",
  Intersections: "Cruzamentos",
  NoGroupsYet: "Nenhum grupo criado ainda",
  Information: "Informação",
  
  GreenWaveTooltip: "Sincronize múltiplos cruzamentos para um efeito de onda verde",
  GreenWaveTooltipActive: "Sincronize múltiplos cruzamentos ao longo de uma via para que veículos possam passar sem parar durante uma onda verde.",
  GreenWaveTooltipDisabled: "Onda Verde só está disponível quando 'Fases Personalizadas' está habilitado para este cruzamento. Selecione 'Fases Personalizadas' primeiro.",
  SyncGroupTooltip: "Selecione um grupo de sincronização para este cruzamento",
  CycleOffsetTooltip: "Deslocamento em segundos do timer do grupo. Diferentes deslocamentos criam a onda verde.",
  UseSyncedCycleTooltip: "Ativa a sincronização com o grupo selecionado",
};
