export default {
  TrafficSignal: "Semáforo",
  ModDefault: "Padrão",
  Vanilla: "Vanilla",
  SplitPhasing: "Fase dividida",
  ProtectedRightTurns: "Conversões à direita protegidas",
  ProtectedLeftTurns: "Conversões à esquerda protegidas",
  Options: "Opções",
  ExclusivePedestrianPhase: "Fase exclusiva para pedestres",
  LaneDirectionTool: "Ferramenta de direção de faixa (Experimental)",
  
  Add: "Adicionar fase",
  Back: "Voltar",
  ManualControl: "Controle manual",
  CustomPhase: "Fase personalizada",
  CustomPhaseEditor: "Editar fases personalizadas",
  SelectFunction: "Selecionar função",
  SelectFunctionDescription: "Escolha uma função para configurar sua rede de tráfego.",
  EditIntersectionPhases: "Editar fases do cruzamento",
  IntersectionMonitor: "Monitor de cruzamento",
  DashboardComingSoon: "Em breve...",
  
  Close: "Fechar",
  Open: "Abrir",
  Reset: "Redefinir",
  Save: "Salvar",
  PleaseSave: "Salve as alterações antes de selecionar outro cruzamento.",
  PleaseSelectJunction: "Selecione um cruzamento",
  GiveWayToOncomingVehicles: "Dar passagem a veículos em sentido contrário",
  CustomPedestrianDurationMultiplier: "Duração da fase de pedestres",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Permitir conversão no vermelho",
  CanaryBuildWarning: "Atenção: você está usando uma versão canary que pode conter bugs. Esta versão é apenas para testes. NÃO use para jogo normal.",
  LdtMigrationNotice: "Lane Direction Tool foi substituído pelo mod Traffic de krzychu124. Instale o mod Traffic para transferir suas configurações automaticamente.",
  LdtRetirementNotice: "Lane Direction Tool foi substituído pelo mod Traffic de krzychu124. Obrigado por usar o LDT.",
  
  PrioritiseTrack: "Priorizar veículos",
  PrioritisePublicCar: "Priorizar transporte público",
  PrioritisePedestrian: "Priorizar pedestres",
  PrioritiseBicycle: "Priorizar ciclistas",
  
  PrioritiseTrackTooltip: "Dá prioridade às faixas de veículos normais (carros, caminhões) durante esta fase",
  PrioritisePublicCarTooltip: "Dá prioridade às faixas de transporte público (ônibus, bondes) durante esta fase",
  PrioritisePedestrianTooltip: "Dá prioridade às faixas de pedestres durante esta fase",
  PrioritiseBicycleTooltip: "Dá prioridade às ciclovias durante esta fase",
  
  Adjustments: "Ajustes",
  MinimumDuration: "Duração mín.",
  MaximumDuration: "Duração máx.",
  TargetDurationMultiplier: "Duração alvo",
  LaneOccupiedMultiplier: "Ocupação de faixas",
  IntervalExponent: "Expoente de intervalo",
  
  MinimumDurationTooltip: "Duração mínima do verde. O semáforo fica verde pelo menos este tempo, mesmo com pouco tráfego.",
  MaximumDurationTooltip: "Duração máxima do verde. Após este tempo, o semáforo muda mesmo se houver tráfego esperando.",
  TargetDurationMultiplierTooltip: "Afeta a duração da fase verde. 1x = Normal, 2x = Dobro da duração com tráfego, 0.5x = Mais curto.",
  LaneOccupiedMultiplierTooltip: "Controla quanto faixas cheias aumentam a prioridade. Maior = Congestionamentos resolvem mais rápido.",
  IntervalExponentTooltip: "Configuração de equidade. Maior = Fases que esperaram mais tempo têm mais prioridade.",
  
  Statistics: "Estatísticas",
  Timer: "Timer",
  Priority: "Prioridade",
  LastRun: "Último ciclo",
  CarFlow: "Fluxo de veículos",
  LanesOccupied: "Faixas ocupadas",
  WeightedWaiting: "Espera ponderada",
  
  TimerTooltip: "Timer atual / Duração alvo",
  PriorityTooltip: "Valor de prioridade atual desta fase",
  LastRunTooltip: "Número de turnos desde a última execução desta fase",
  CarFlowTooltip: "Fluxo atual de veículos nesta fase",
  LanesOccupiedTooltip: "Número de faixas ocupadas (veículos, transporte, trilhos, pedestres)",
  WeightedWaitingTooltip: "Tempo de espera ponderado dos veículos nesta fase",
  
  EndPhasePrematurely: "Terminar fase agora",
  PhaseEndRequested: "Fim de fase solicitado",
  SelectAll: "Selecionar tudo",
  DeselectAll: "Desmarcar tudo",
  CopyPhases: "Copiar fases",
  PastePhases: "Colar fases",
  DeleteSelectedPhases: "Excluir selecionadas",
  ClearClipboard: "Limpar área de transferência",
  
  SelectAllTooltip: "Selecionar todas as fases para copiar ou excluir",
  CopyPhasesTooltip: "Copiar fases selecionadas para a área de transferência",
  PastePhasesTooltip: "Colar fases da área de transferência",
  DeleteSelectedPhasesTooltip: "Excluir permanentemente as fases selecionadas",
  ClearClipboardTooltip: "Limpar área de transferência para evitar colagens acidentais",

  GreenWave: "Onda Verde",
  GreenWaveButton: "Onda Verde",
  SyncGroup: "Grupo de Sincronização",
  NoSyncGroup: "Sem Grupo",
  CreateNewGroup: "Criar Novo Grupo",
  CycleOffset: "Deslocamento do Ciclo",
  UseSyncedCycle: "Ativar Sincronização",
  TotalCycleDuration: "Duração Total do Ciclo",
  BaseCycleDuration: "Ciclo Base",
  IntersectionsInGroup: "Cruzamentos",
  NewGroupName: "Novo Grupo",
  DeleteGroup: "Excluir Grupo",
  RenameGroup: "Renomear",
  OpenGreenWavePanel: "Abrir Onda Verde",
  GreenWavePanelActive: "Onda Verde Ativa",
  
  PhaseMode: "Modo de Fase",
  LegacyMode: "Padrão (Prioridade)",
  LegacyModeHint: "Próxima fase baseada na demanda de tráfego",
  LegacyModeTooltip: "As fases mudam com base na prioridade - veículos e pedestres esperando determinam a próxima fase. Comportamento padrão do jogo.",
  SequentialMode: "Sequencial (Ordem)",
  SequentialModeHint: "Fases 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "As fases rodam em ordem: 1 → 2 → 3 → 4 → 1... Sequência fixa e previsível. Necessário para Onda Verde.",
  GreenWaveForcesSequential: "Onda Verde requer modo sequencial",
  
  SyncSettings: "Config. de Sincr.",
  SyncPhase: "Fase de Sincr.",
  SyncPhaseTooltip: "Selecione qual fase sincronizar. Útil para faixas de conversão.",
  OffsetCalculator: "Calculadora de Offset",
  Distance: "Distância",
  Speed: "Velocidade",
  RecommendedOffset: "Recomendado",
  Apply: "Aplicar",
  OwnCycle: "Ciclo Próprio",
  GroupBase: "Base do Grupo",
  AutoFactor: "Fator Automático",
  AutoFactorTooltip: "Proporção entre o ciclo próprio e a base do grupo. Diferentes durações de ciclo são escaladas automaticamente.",
  Intersections: "Cruzamentos",
  NoGroupsYet: "Nenhum grupo criado ainda",
  Information: "Informações",
  
  GreenWaveTooltip: "Sincronize múltiplos cruzamentos para um efeito de onda verde",
  GreenWaveTooltipActive: "Sincronize múltiplos cruzamentos ao longo de uma via para que veículos possam passar sem parar durante uma onda verde.",
  GreenWaveTooltipDisabled: "Onda Verde só está disponível quando 'Fases Personalizadas' está habilitado para este cruzamento. Selecione 'Fases Personalizadas' primeiro.",
  SyncGroupTooltip: "Selecione um grupo de sincronização para este cruzamento",
  CycleOffsetTooltip: "Deslocamento em segundos do timer do grupo. Diferentes deslocamentos criam a onda verde.",
  UseSyncedCycleTooltip: "Ativa a sincronização com o grupo selecionado",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Cruzamento",
  GWP_TabGroups: "Grupos",
  GWP_TabDashboard: "Painel",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Sincronização ativa",
  GWP_NotSynced: "Não sincronizado",

  // Green Wave Panel - Labels
  GWP_NodeId: "ID do Nó (Cruzamento)",
  GWP_Group: "Grupo",
  GWP_Offset: "Offset",
  GWP_AssignSyncGroup: "Atribuir Grupo de Sinc.",
  GWP_NoGroupSelected: "Nenhum grupo selecionado",
  GWP_NoGroup: "Sem Grupo",
  GWP_NewGroup: "+ Novo Grupo",
  GWP_Rename: "Renomear",
  GWP_EnableSync: "Ativar Sincr.",
  GWP_CycleOffset: "Offset de Ciclo",
  GWP_Tempo: "Velocidade",
  GWP_Recommended: "Recomendado:",
  GWP_GameTime: "Jogo",
  GWP_RealTime: "Real",
  GWP_PhaseHint: "A Fase #1 deve ser a direção principal da Onda Verde!",
  GWP_AutoSave: "As alterações são salvas automaticamente",
  GWP_SelectIntersection: "Por favor, selecione um cruzamento.",
  GWP_SearchGroups: "Pesquisar grupos...",
  GWP_NoMatches: "Sem correspondências para",
  GWP_RemoveFromGroup: "Remover do Grupo",
  GWP_DeleteGroup: "Excluir Grupo",
  GWP_NoIntersections: "Cruzamentos",
  GWP_GroupsHint: "Grupos sem cruzamentos podem ser excluídos. Adicione cruzamentos na aba 'Cruzamento'.",
  GWP_SelectGroupHint: "Selecione um grupo na aba 'Cruzamento' para ver detalhes.",
  GWP_AddIntersectionsHint: "Este grupo ainda não tem cruzamentos. Vá para a aba 'Cruzamento' e adicione cruzamentos!",
  GWP_RemovedFromGroup: "Removido do grupo",
  GWP_AddedToGroup: "Adicionado a",
  GWP_SyncEnabled: "Sincronização ativada!",
  GWP_SyncDisabled: "Sincronização desativada",
  GWP_NewGroupCreated: "Novo grupo criado!",
  GWP_GroupRenamed: "Grupo renomeado para",
  GWP_GroupDeleted: "Grupo excluído",
  GWP_IntersectionRemoved: "Cruzamento removido do grupo",
  GWP_OffsetSet: "Offset definido para",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Ativa a sincronização deste cruzamento com o grupo.",
  GWP_TT_SyncPhase: "Fase de Sincr.",
  GWP_TT_CycleOffset: "Offset de tempo em segundos a partir do ciclo base do grupo.",
  GWP_TT_Distance: "Distância",
  GWP_TT_Speed: "Velocidade",
  GWP_TT_OwnCycle: "Ciclo Próprio",
  GWP_TT_GroupBase: "Ciclo base do grupo (tempo de jogo).",
  GWP_TT_Intersections: "Cruzamentos",
  GWP_MoveUp: "Mover acima",
  GWP_MoveDown: "Mover abaixo",
  GWP_ManageGroups: "Gerenciar Grupos de Sinc.",
  GWP_CreateNewGroup: "+ Criar Novo Grupo",
  GWP_DB_Intersection: "Cruzamento",
  GWP_DB_Reference: "REFERÊNCIA",
  GWP_DB_Phases: "Fases",
  GWP_DB_Green: "VERDE",
  GWP_DB_SyncOn: "SYNC",
  GWP_DB_SyncOff: "OFF",
  GWP_DB_SyncWaiting: "Sync ativo - aguardando",
  GWP_DB_GreenWaveActive: "Onda Verde ativa!",
  GWP_DB_ReadyToSwitch: "Pronto para mudar",
  GWP_DB_Offset: "OFFSET",
  GWP_DB_Cycle: "CICLO",
  GWP_DB_Roads: "VIAS",
  GWP_DB_Lanes: "FAIXAS",
  GWP_DB_Pedestrians: "PED.",
  GWP_DB_OffsetDelta: "Offset",
  GWP_DB_BaseCycle: "Ciclo Base",
  GWP_DB_GreenWaveLabel: "Onda Verde",
  GWP_DB_SyncActiveLabel: "Sync Ativo",
  GWP_DB_ReorderHint: "Use as setas para ajustar a ordem. O primeiro cruzamento é a referência (Offset 0).",
  GWP_DB_PhaseProgressTooltip: "Esquerda: Duração mínima. Piscando: Fase pronta para mudar.",
  GWP_DB_MinDurationTooltip: "Em 50% a duração mínima é atingida. A fase pode mudar a qualquer momento.",
  GWP_DB_PhaseXofY: "Fase {0} de {1}",

  // V147: Traffic Summary
  TrafficSummary: "Resumo do Tráfego",
  VehiclesPerHour: "Ø Fluxo",
  VehiclesPerMinute: "Veículos/Min",
  Approaches: "Acessos",
  IncomingLanes: "Faixas de Entrada",
  IncomingLanesTooltip: "Faixas físicas que entram no cruzamento.",
  OccupiedLanes: "Faixas Ocupadas",
  OccupiedLanesTooltip: "Número de faixas ocupadas com veículos esperando.",
  OccupiedPedestrianLanes: "Faixas Ped. Ocup.",
  TrafficFlowLow: "Tráfego Leve",
  TrafficFlowMedium: "Tráfego Moderado",
  TrafficFlowHigh: "Tráfego Intenso",
  WaitingVehicles: "Veículos Esperando",
  WaitingVehiclesTooltip: "Número atual de veículos esperando (média).",
  PeakHour: "Pico (24h)",
  PeakHourTooltip: "Hora com maior volume nas últimas 24 horas.",
  MaxVPH: "Máx V/h (24h)",
  MaxVPHTooltip: "Maior veículos/hora nas últimas 24 horas.",
  VPH_InfoEstimate: "Estimativa baseada em faixas e ocupação.",
  VPH_InfoRealData: "Média móvel da contagem real de veículos.",
  ChartDisabledTooltip: "Ative 'Fase Personalizada' para coletar dados",
  ChartCollectingTooltip: "Coletando dados... Primeiros valores em ~30 min",
  ChartActiveTooltip: "Histórico de tráfego de 24 horas",
  CustomPhaseRequiredTooltip: "Requer que 'Fases Personalizadas' esteja ativado para este cruzamento.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Excluir fase?",
};
