export default {
  TrafficSignal: "Светофор",
  ModDefault: "По умолчанию",
  Vanilla: "Ванильный",
  SplitPhasing: "Разделённая фаза",
  ProtectedRightTurns: "Защищённые правые повороты",
  ProtectedLeftTurns: "Защищённые левые повороты",
  Options: "Опции",
  ExclusivePedestrianPhase: "Эксклюзивная пешеходная фаза",
  LaneDirectionTool: "Инструмент направления полосы (Экспериментальный)",
  
  Add: "Добавить фазу",
  Back: "Назад",
  ManualControl: "Ручное управление",
  CustomPhase: "Настраиваемая фаза",
  CustomPhaseEditor: "Редактировать фазы",
  SelectFunction: "Выбрать функцию",
  SelectFunctionDescription: "Выберите функцию для настройки дорожной сети.",
  EditIntersectionPhases: "Редактировать фазы перекрёстка",
  IntersectionMonitor: "Монитор перекрёстка",
  DashboardComingSoon: "Скоро...",
  
  Close: "Закрыть",
  Open: "Открыть",
  Reset: "Сбросить",
  Save: "Сохранить",
  PleaseSave: "Сохраните изменения перед выбором другого перекрёстка.",
  PleaseSelectJunction: "Выберите перекрёсток",
  GiveWayToOncomingVehicles: "Уступить дорогу встречным автомобилям",
  CustomPedestrianDurationMultiplier: "Длительность пешеходной фазы",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Разрешить поворот на красный",
  CanaryBuildWarning: "Внимание: вы используете canary-версию, которая может содержать ошибки. Эта версия только для тестирования. НЕ используйте для обычной игры.",
  LdtMigrationNotice: "Lane Direction Tool заменён модом Traffic от krzychu124. Установите мод Traffic для автоматического переноса настроек.",
  LdtRetirementNotice: "Lane Direction Tool заменён модом Traffic от krzychu124. Спасибо за использование LDT.",
  
  PrioritiseTrack: "Приоритет транспорта",
  PrioritisePublicCar: "Приоритет общ. транспорта",
  PrioritisePedestrian: "Приоритет пешеходов",
  PrioritiseBicycle: "Приоритет велосипедистов",
  
  PrioritiseTrackTooltip: "Даёт приоритет полосам обычного транспорта (машины, грузовики) во время этой фазы",
  PrioritisePublicCarTooltip: "Даёт приоритет полосам общественного транспорта (автобусы, трамваи) во время этой фазы",
  PrioritisePedestrianTooltip: "Даёт приоритет пешеходным переходам во время этой фазы",
  PrioritiseBicycleTooltip: "Даёт приоритет велосипедным дорожкам во время этой фазы",
  
  Adjustments: "Настройки",
  MinimumDuration: "Мин. длительность",
  MaximumDuration: "Макс. длительность",
  TargetDurationMultiplier: "Целевая длительность",
  LaneOccupiedMultiplier: "Занятость полос",
  IntervalExponent: "Экспонента интервала",
  
  MinimumDurationTooltip: "Минимальная длительность зелёного. Светофор остаётся зелёным минимум это время, даже при малом трафике.",
  MaximumDurationTooltip: "Максимальная длительность зелёного. После этого времени светофор переключается, даже если есть ожидающий трафик.",
  TargetDurationMultiplierTooltip: "Влияет на длительность зелёной фазы. 1x = Обычная, 2x = Удвоенная при загрузке, 0.5x = Короче.",
  LaneOccupiedMultiplierTooltip: "Контролирует насколько заполненные полосы увеличивают приоритет. Выше = Пробки рассасываются быстрее.",
  IntervalExponentTooltip: "Настройка справедливости. Выше = Фазы, которые ждали дольше, получают больший приоритет.",
  
  Statistics: "Статистика",
  Timer: "Таймер",
  Priority: "Приоритет",
  LastRun: "Последний цикл",
  CarFlow: "Поток машин",
  LanesOccupied: "Занятые полосы",
  WeightedWaiting: "Взвешенное ожидание",
  
  TimerTooltip: "Текущий таймер / Целевая длительность",
  PriorityTooltip: "Текущее значение приоритета этой фазы",
  LastRunTooltip: "Количество ходов с последнего запуска этой фазы",
  CarFlowTooltip: "Текущий поток транспорта через эту фазу",
  LanesOccupiedTooltip: "Количество занятых полос (транспорт, общ. транспорт, рельсы, пешеходы)",
  WeightedWaitingTooltip: "Взвешенное время ожидания транспорта на этой фазе",
  
  EndPhasePrematurely: "Завершить фазу сейчас",
  PhaseEndRequested: "Запрошено завершение фазы",
  SelectAll: "Выбрать всё",
  DeselectAll: "Снять выбор",
  CopyPhases: "Копировать фазы",
  PastePhases: "Вставить фазы",
  DeleteSelectedPhases: "Удалить выбранные",
  ClearClipboard: "Очистить буфер",
  
  SelectAllTooltip: "Выбрать все фазы для копирования или удаления",
  CopyPhasesTooltip: "Копировать выбранные фазы в буфер обмена",
  PastePhasesTooltip: "Вставить фазы из буфера обмена",
  DeleteSelectedPhasesTooltip: "Окончательно удалить выбранные фазы",
  ClearClipboardTooltip: "Очистить буфер обмена для предотвращения случайной вставки",

  GreenWave: "Зелёная Волна",
  GreenWaveButton: "Зелёная Волна",
  SyncGroup: "Группа Синхронизации",
  NoSyncGroup: "Нет Группы",
  CreateNewGroup: "Создать Новую Группу",
  CycleOffset: "Смещение Цикла",
  UseSyncedCycle: "Включить Синхронизацию",
  TotalCycleDuration: "Общая Длительность Цикла",
  BaseCycleDuration: "Базовый Цикл",
  IntersectionsInGroup: "Перекрёстки",
  NewGroupName: "Новая Группа",
  DeleteGroup: "Удалить Группу",
  RenameGroup: "Переименовать",
  OpenGreenWavePanel: "Открыть Зелёную Волну",
  GreenWavePanelActive: "Зелёная Волна Активна",
  
  PhaseMode: "Режим Фазы",
  LegacyMode: "Стандартный (Приоритет)",
  LegacyModeHint: "Следующая фаза по запросу трафика",
  LegacyModeTooltip: "Фазы переключаются по приоритету - ожидающие транспорт и пешеходы определяют следующую фазу. Стандартное поведение игры.",
  SequentialMode: "Последовательный (Порядок)",
  SequentialModeHint: "Фазы 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Фазы идут по порядку: 1 → 2 → 3 → 4 → 1... Фиксированная, предсказуемая последовательность. Требуется для Зелёной Волны.",
  GreenWaveForcesSequential: "Зелёная Волна требует последовательный режим",
  
  SyncSettings: "Настройки синхр.",
  SyncPhase: "Фаза синхр.",
  SyncPhaseTooltip: "Выберите фазу для синхронизации. Полезно для поворотных полос.",
  OffsetCalculator: "Калькулятор смещения",
  Distance: "Расстояние",
  Speed: "Скорость",
  RecommendedOffset: "Рекомендуемое",
  Apply: "Применить",
  OwnCycle: "Свой цикл",
  GroupBase: "База Группы",
  AutoFactor: "Авто-Фактор",
  AutoFactorTooltip: "Соотношение между собственным циклом и базой группы. Разные длительности циклов масштабируются автоматически.",
  Intersections: "Перекрёстки",
  NoGroupsYet: "Группы ещё не созданы",
  Information: "Информация",
  
  GreenWaveTooltip: "Синхронизируйте несколько перекрёстков для эффекта зелёной волны",
  GreenWaveTooltipActive: "Синхронизируйте несколько перекрёстков вдоль дороги, чтобы транспорт мог проезжать без остановок во время зелёной волны.",
  GreenWaveTooltipDisabled: "Зелёная Волна доступна только когда 'Настраиваемые Фазы' включены для этого перекрёстка. Сначала выберите 'Настраиваемые Фазы'.",
  SyncGroupTooltip: "Выберите группу синхронизации для этого перекрёстка",
  CycleOffsetTooltip: "Временное смещение в секундах от таймера группы. Разные смещения создают зелёную волну.",
  UseSyncedCycleTooltip: "Включает синхронизацию с выбранной группой",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "Перекрёсток",
  GWP_TabGroups: "Группы",
  GWP_TabDashboard: "Панель",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "Синхронизация активна",
  GWP_NotSynced: "Не синхронизирован",

  // Green Wave Panel - Labels
  GWP_NodeId: "ID узла (Перекрёсток)",
  GWP_Group: "Группа",
  GWP_Offset: "Смещение",
  GWP_AssignSyncGroup: "Назначить группу синхр.",
  GWP_NoGroupSelected: "Группа не выбрана",
  GWP_NoGroup: "Без группы",
  GWP_NewGroup: "+ Новая группа",
  GWP_Rename: "Переименовать",
  GWP_EnableSync: "Включить синхр.",
  GWP_CycleOffset: "Смещение цикла",
  GWP_Tempo: "Скорость",
  GWP_Recommended: "Рекомендуется:",
  GWP_GameTime: "Игровое",
  GWP_RealTime: "Реальное",
  GWP_PhaseHint: "Фаза #1 должна быть основным направлением Зелёной Волны!",
  GWP_AutoSave: "Изменения сохраняются автоматически",
  GWP_SelectIntersection: "Выберите перекрёсток.",
  GWP_SearchGroups: "Поиск групп...",
  GWP_NoMatches: "Нет совпадений",
  GWP_RemoveFromGroup: "Удалить из группы",
  GWP_DeleteGroup: "Удалить группу",
  GWP_NoIntersections: "Перекрёстки",
  GWP_GroupsHint: "Группы без перекрёстков можно удалить. Добавьте перекрёстки на вкладке «Перекрёсток».",
  GWP_SelectGroupHint: "Выберите группу на вкладке «Перекрёсток» для просмотра деталей.",
  GWP_AddIntersectionsHint: "В этой группе пока нет перекрёстков. Перейдите на вкладку «Перекрёсток» и добавьте!",
  GWP_RemovedFromGroup: "Удалён из группы",
  GWP_AddedToGroup: "Добавлен в",
  GWP_SyncEnabled: "Синхронизация включена!",
  GWP_SyncDisabled: "Синхронизация отключена",
  GWP_NewGroupCreated: "Новая группа создана!",
  GWP_GroupRenamed: "Группа переименована в",
  GWP_GroupDeleted: "Группа удалена",
  GWP_IntersectionRemoved: "Перекрёсток удалён из группы",
  GWP_OffsetSet: "Смещение установлено:",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "Включает синхронизацию этого перекрёстка с группой.",
  GWP_TT_SyncPhase: "Фаза синхр.",
  GWP_TT_CycleOffset: "Временное смещение в секундах от базового цикла группы.",
  GWP_TT_Distance: "Расстояние",
  GWP_TT_Speed: "Скорость",
  GWP_TT_OwnCycle: "Свой цикл",
  GWP_TT_GroupBase: "Базовый цикл группы (игровое время).",
  GWP_TT_Intersections: "Перекрёстки",
  GWP_MoveUp: "Вверх",
  GWP_MoveDown: "Вниз",
  GWP_ManageGroups: "Управление группами синхр.",
  GWP_CreateNewGroup: "+ Создать группу",
  GWP_DB_Intersection: "Перекрёсток",
  GWP_DB_Reference: "ЭТАЛОН",
  GWP_DB_Phases: "Фазы",
  GWP_DB_Green: "ЗЕЛЁНЫЙ",
  GWP_DB_SyncOn: "СИНХР",
  GWP_DB_SyncOff: "ВЫКЛ",
  GWP_DB_SyncWaiting: "Синхр. активна - ожидание",
  GWP_DB_GreenWaveActive: "Зелёная Волна активна!",
  GWP_DB_ReadyToSwitch: "Готов к переключению",
  GWP_DB_Offset: "СМЕЩЕНИЕ",
  GWP_DB_Cycle: "ЦИКЛ",
  GWP_DB_Roads: "ДОРОГИ",
  GWP_DB_Lanes: "ПОЛОСЫ",
  GWP_DB_Pedestrians: "ПЕШ.",
  GWP_DB_OffsetDelta: "Смещение",
  GWP_DB_BaseCycle: "Базовый Цикл",
  GWP_DB_GreenWaveLabel: "Зелёная Волна",
  GWP_DB_SyncActiveLabel: "Синхр. Активна",
  GWP_DB_ReorderHint: "Используйте стрелки для изменения порядка. Первый перекрёсток - эталон (Смещение 0).",
  GWP_DB_PhaseProgressTooltip: "Слева: Минимальное время. Мигание: Фаза готова к переключению.",
  GWP_DB_MinDurationTooltip: "При 50% достигнуто минимальное время. Фаза может переключиться в любой момент.",
  GWP_DB_PhaseXofY: "Фаза {0} из {1}",

  // V147: Traffic Summary
  TrafficSummary: "Обзор трафика",
  VehiclesPerHour: "Ø Поток",
  VehiclesPerMinute: "Транспорт/Мин",
  Approaches: "Подъезды",
  IncomingLanes: "Входящие полосы",
  IncomingLanesTooltip: "Физические полосы, входящие в перекрёсток.",
  OccupiedLanes: "Занятые полосы",
  OccupiedLanesTooltip: "Количество занятых полос с ожидающим транспортом.",
  OccupiedPedestrianLanes: "Пешех. полосы зан.",
  TrafficFlowLow: "Слабый трафик",
  TrafficFlowMedium: "Умеренный трафик",
  TrafficFlowHigh: "Интенсивный трафик",
  WaitingVehicles: "Ожидающий транспорт",
  WaitingVehiclesTooltip: "Текущее количество ожидающего транспорта (среднее).",
  PeakHour: "Пик (24ч)",
  PeakHourTooltip: "Время с наибольшим объёмом за последние 24 часа.",
  MaxVPH: "Макс Т/ч (24ч)",
  MaxVPHTooltip: "Наибольшее транспорт/час за последние 24 часа.",
  VPH_InfoEstimate: "Оценка на основе полос и занятости.",
  VPH_InfoRealData: "Скользящее среднее реального подсчёта транспорта.",
  ChartDisabledTooltip: "Включите 'Своя фаза' для сбора данных",
  ChartCollectingTooltip: "Сбор данных... Первые значения через ~30 мин",
  ChartActiveTooltip: "24-часовая история трафика",
  CustomPhaseRequiredTooltip: "Требуется включение 'Своя фаза' для этого перекрёстка.",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "Удалить фазу?",
};
