export default {
  TrafficSignal: "Светофор",
  ModDefault: "По умолчанию",
  Vanilla: "Ванильный",
  SplitPhasing: "Разделённая фаза",
  ProtectedRightTurns: "Защищённые правые повороты",
  ProtectedLeftTurns: "Защищённые левые повороты",
  Options: "Опции",
  ExclusivePedestrianPhase: "Эксклюзивная пешеходная фаза",
  LaneDirectionTool: "Инструмент направления полосы (Экспериментальный)",
  
  Add: "Добавить фазу",
  Back: "Назад",
  ManualControl: "Ручное управление",
  CustomPhase: "Настраиваемая фаза",
  CustomPhaseEditor: "Редактировать фазы",
  SelectFunction: "Выбрать функцию",
  SelectFunctionDescription: "Выберите функцию для настройки дорожной сети.",
  EditIntersectionPhases: "Редактировать фазы перекрёстка",
  IntersectionMonitor: "Монитор перекрёстка",
  DashboardComingSoon: "Скоро...",
  
  Close: "Закрыть",
  Open: "Открыть",
  Reset: "Сбросить",
  Save: "Сохранить",
  PleaseSave: "Сохраните изменения перед выбором другого перекрёстка.",
  PleaseSelectJunction: "Выберите перекрёсток",
  GiveWayToOncomingVehicles: "Уступить дорогу встречным автомобилям",
  CustomPedestrianDurationMultiplier: "Длительность пешеходной фазы",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "Разрешить поворот на красный",
  CanaryBuildWarning: "Внимание: вы используете canary-версию, которая может содержать ошибки. Эта версия только для тестирования. НЕ используйте для обычной игры.",
  LdtMigrationNotice: "Lane Direction Tool заменён модом Traffic от krzychu124. Установите мод Traffic для автоматического переноса настроек.",
  LdtRetirementNotice: "Lane Direction Tool заменён модом Traffic от krzychu124. Спасибо за использование LDT.",
  
  PrioritiseTrack: "Приоритет транспорта",
  PrioritisePublicCar: "Приоритет общ. транспорта",
  PrioritisePedestrian: "Приоритет пешеходов",
  PrioritiseBicycle: "Приоритет велосипедистов",
  
  PrioritiseTrackTooltip: "Даёт приоритет полосам обычного транспорта (машины, грузовики) во время этой фазы",
  PrioritisePublicCarTooltip: "Даёт приоритет полосам общественного транспорта (автобусы, трамваи) во время этой фазы",
  PrioritisePedestrianTooltip: "Даёт приоритет пешеходным переходам во время этой фазы",
  PrioritiseBicycleTooltip: "Даёт приоритет велосипедным дорожкам во время этой фазы",
  
  Adjustments: "Настройки",
  MinimumDuration: "Мин. длительность",
  MaximumDuration: "Макс. длительность",
  TargetDurationMultiplier: "Целевая длительность",
  LaneOccupiedMultiplier: "Занятость полос",
  IntervalExponent: "Экспонента интервала",
  
  MinimumDurationTooltip: "Минимальная длительность зелёного. Светофор остаётся зелёным минимум это время, даже при малом трафике.",
  MaximumDurationTooltip: "Максимальная длительность зелёного. После этого времени светофор переключается, даже если есть ожидающий трафик.",
  TargetDurationMultiplierTooltip: "Влияет на длительность зелёной фазы. 1x = Обычная, 2x = Удвоенная при загрузке, 0.5x = Короче.",
  LaneOccupiedMultiplierTooltip: "Контролирует насколько заполненные полосы увеличивают приоритет. Выше = Пробки рассасываются быстрее.",
  IntervalExponentTooltip: "Настройка справедливости. Выше = Фазы, которые ждали дольше, получают больший приоритет.",
  
  Statistics: "Статистика",
  Timer: "Таймер",
  Priority: "Приоритет",
  LastRun: "Последний цикл",
  CarFlow: "Поток машин",
  LanesOccupied: "Занятые полосы",
  WeightedWaiting: "Взвешенное ожидание",
  
  TimerTooltip: "Текущий таймер / Целевая длительность",
  PriorityTooltip: "Текущее значение приоритета этой фазы",
  LastRunTooltip: "Количество ходов с последнего запуска этой фазы",
  CarFlowTooltip: "Текущий поток транспорта через эту фазу",
  LanesOccupiedTooltip: "Количество занятых полос (транспорт, общ. транспорт, рельсы, пешеходы)",
  WeightedWaitingTooltip: "Взвешенное время ожидания транспорта на этой фазе",
  
  EndPhasePrematurely: "Завершить фазу сейчас",
  PhaseEndRequested: "Запрошено завершение фазы",
  SelectAll: "Выбрать всё",
  DeselectAll: "Снять выбор",
  CopyPhases: "Копировать фазы",
  PastePhases: "Вставить фазы",
  DeleteSelectedPhases: "Удалить выбранные",
  ClearClipboard: "Очистить буфер",
  
  SelectAllTooltip: "Выбрать все фазы для копирования или удаления",
  CopyPhasesTooltip: "Копировать выбранные фазы в буфер обмена",
  PastePhasesTooltip: "Вставить фазы из буфера обмена",
  DeleteSelectedPhasesTooltip: "Окончательно удалить выбранные фазы",
  ClearClipboardTooltip: "Очистить буфер обмена для предотвращения случайной вставки",

  GreenWave: "Зелёная Волна",
  GreenWaveButton: "Зелёная Волна",
  SyncGroup: "Группа Синхронизации",
  NoSyncGroup: "Нет Группы",
  CreateNewGroup: "Создать Новую Группу",
  CycleOffset: "Смещение Цикла",
  UseSyncedCycle: "Включить Синхронизацию",
  TotalCycleDuration: "Общая Длительность Цикла",
  BaseCycleDuration: "Базовый Цикл",
  IntersectionsInGroup: "Перекрёстки",
  NewGroupName: "Новая Группа",
  DeleteGroup: "Удалить Группу",
  RenameGroup: "Переименовать",
  OpenGreenWavePanel: "Открыть Зелёную Волну",
  GreenWavePanelActive: "Зелёная Волна Активна",
  
  PhaseMode: "Режим Фазы",
  LegacyMode: "Стандартный (Приоритет)",
  LegacyModeHint: "Следующая фаза по запросу трафика",
  LegacyModeTooltip: "Фазы переключаются по приоритету - ожидающие транспорт и пешеходы определяют следующую фазу. Стандартное поведение игры.",
  SequentialMode: "Последовательный (Порядок)",
  SequentialModeHint: "Фазы 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "Фазы идут по порядку: 1 → 2 → 3 → 4 → 1... Фиксированная, предсказуемая последовательность. Требуется для Зелёной Волны.",
  GreenWaveForcesSequential: "Зелёная Волна требует последовательный режим",
  
  SyncSettings: "Настройки Синхронизации",
  SyncPhase: "Фаза Синхронизации",
  SyncPhaseTooltip: "Выберите какую фазу синхронизировать. Полезно для полос поворота.",
  OffsetCalculator: "Калькулятор Смещения",
  Distance: "Расстояние",
  Speed: "Скорость",
  RecommendedOffset: "Рекомендуемое",
  Apply: "Применить",
  OwnCycle: "Собственный Цикл",
  GroupBase: "База Группы",
  AutoFactor: "Авто-Фактор",
  AutoFactorTooltip: "Соотношение между собственным циклом и базой группы. Разные длительности циклов масштабируются автоматически.",
  Intersections: "Перекрёстки",
  NoGroupsYet: "Группы ещё не созданы",
  Information: "Информация",
  
  GreenWaveTooltip: "Синхронизируйте несколько перекрёстков для эффекта зелёной волны",
  GreenWaveTooltipActive: "Синхронизируйте несколько перекрёстков вдоль дороги, чтобы транспорт мог проезжать без остановок во время зелёной волны.",
  GreenWaveTooltipDisabled: "Зелёная Волна доступна только когда 'Настраиваемые Фазы' включены для этого перекрёстка. Сначала выберите 'Настраиваемые Фазы'.",
  SyncGroupTooltip: "Выберите группу синхронизации для этого перекрёстка",
  CycleOffsetTooltip: "Временное смещение в секундах от таймера группы. Разные смещения создают зелёную волну.",
  UseSyncedCycleTooltip: "Включает синхронизацию с выбранной группой",
};
