export default {
  TrafficSignal: "交通信号灯",
  ModDefault: "默认",
  Vanilla: "原版",
  SplitPhasing: "分离相位",
  ProtectedRightTurns: "受保护右转",
  ProtectedLeftTurns: "受保护左转",
  Options: "选项",
  ExclusivePedestrianPhase: "专用行人相位",
  LaneDirectionTool: "车道方向工具（实验性）",
  
  Add: "添加相位",
  Back: "返回",
  ManualControl: "手动控制",
  CustomPhase: "自定义相位",
  CustomPhaseEditor: "编辑自定义相位",
  SelectFunction: "选择功能",
  SelectFunctionDescription: "选择一个功能来配置您的交通网络。",
  EditIntersectionPhases: "编辑路口相位",
  IntersectionMonitor: "路口监视器",
  DashboardComingSoon: "即将推出...",
  
  Close: "关闭",
  Open: "打开",
  Reset: "重置",
  Save: "保存",
  PleaseSave: "选择其他路口前请保存更改。",
  PleaseSelectJunction: "请选择一个路口",
  GiveWayToOncomingVehicles: "让行对向车辆",
  CustomPedestrianDurationMultiplier: "行人相位时长",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "允许红灯转弯",
  CanaryBuildWarning: "注意：您正在使用可能包含错误的金丝雀版本。此版本仅供测试。请勿用于正常游戏。",
  LdtMigrationNotice: "Lane Direction Tool已被krzychu124的Traffic模组取代。请安装Traffic模组以自动转移您的设置。",
  LdtRetirementNotice: "Lane Direction Tool已被krzychu124的Traffic模组取代。感谢您使用LDT。",
  
  PrioritiseTrack: "优先车辆",
  PrioritisePublicCar: "优先公共交通",
  PrioritisePedestrian: "优先行人",
  PrioritiseBicycle: "优先自行车",
  
  PrioritiseTrackTooltip: "在此相位期间优先普通车辆车道（汽车、卡车）",
  PrioritisePublicCarTooltip: "在此相位期间优先公共交通车道（公交车、有轨电车）",
  PrioritisePedestrianTooltip: "在此相位期间优先人行横道",
  PrioritiseBicycleTooltip: "在此相位期间优先自行车道",
  
  Adjustments: "调整",
  MinimumDuration: "最小时长",
  MaximumDuration: "最大时长",
  TargetDurationMultiplier: "目标时长",
  LaneOccupiedMultiplier: "车道占用率",
  IntervalExponent: "间隔指数",
  
  MinimumDurationTooltip: "最小绿灯时长。即使交通量很少，信号灯也会保持绿灯至少这么长时间。",
  MaximumDurationTooltip: "最大绿灯时长。超过此时间后，即使仍有车辆等待，信号灯也会切换。",
  TargetDurationMultiplierTooltip: "影响绿灯相位长度。1x = 正常，2x = 繁忙时加倍，0.5x = 缩短。",
  LaneOccupiedMultiplierTooltip: "控制满载车道增加多少优先级。较高 = 拥堵解决更快。",
  IntervalExponentTooltip: "公平性设置。较高 = 等待时间较长的相位获得更高优先级。",
  
  Statistics: "统计",
  Timer: "计时器",
  Priority: "优先级",
  LastRun: "上次运行",
  CarFlow: "车流量",
  LanesOccupied: "占用车道",
  WeightedWaiting: "加权等待时间",
  
  TimerTooltip: "当前计时器 / 目标时长",
  PriorityTooltip: "此相位的当前优先级值",
  LastRunTooltip: "此相位上次运行以来的回合数",
  CarFlowTooltip: "此相位的当前车流量",
  LanesOccupiedTooltip: "占用车道数（车辆、公交、轨道、行人）",
  WeightedWaitingTooltip: "此相位车辆的加权等待时间",
  
  EndPhasePrematurely: "立即结束相位",
  PhaseEndRequested: "已请求结束相位",
  SelectAll: "全选",
  DeselectAll: "取消全选",
  CopyPhases: "复制相位",
  PastePhases: "粘贴相位",
  DeleteSelectedPhases: "删除选中项",
  ClearClipboard: "清空剪贴板",
  
  SelectAllTooltip: "选择所有相位以复制或删除",
  CopyPhasesTooltip: "将选中的相位复制到剪贴板",
  PastePhasesTooltip: "从剪贴板粘贴相位",
  DeleteSelectedPhasesTooltip: "永久删除选中的相位",
  ClearClipboardTooltip: "清空剪贴板以防止意外粘贴",

  GreenWave: "绿波",
  GreenWaveButton: "绿波",
  SyncGroup: "同步组",
  NoSyncGroup: "无组",
  CreateNewGroup: "创建新组",
  CycleOffset: "周期偏移",
  UseSyncedCycle: "启用同步",
  TotalCycleDuration: "总周期时长",
  BaseCycleDuration: "基础周期",
  IntersectionsInGroup: "路口",
  NewGroupName: "新组",
  DeleteGroup: "删除组",
  RenameGroup: "重命名",
  OpenGreenWavePanel: "打开绿波",
  GreenWavePanelActive: "绿波已激活",
  
  PhaseMode: "相位模式",
  LegacyMode: "标准（优先级）",
  LegacyModeHint: "根据交通需求决定下一相位",
  LegacyModeTooltip: "相位根据优先级切换 - 等待的车辆和行人决定下一相位。默认游戏行为。",
  SequentialMode: "顺序（按序）",
  SequentialModeHint: "相位 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "相位按顺序运行：1 → 2 → 3 → 4 → 1... 固定、可预测的顺序。绿波必需。",
  GreenWaveForcesSequential: "绿波需要顺序模式",
  
  SyncSettings: "同步设置",
  SyncPhase: "同步相位",
  SyncPhaseTooltip: "选择要同步的相位。适用于转弯车道。",
  OffsetCalculator: "偏移计算器",
  Distance: "距离",
  Speed: "速度",
  RecommendedOffset: "推荐",
  Apply: "应用",
  OwnCycle: "自身周期",
  GroupBase: "组基准",
  AutoFactor: "自动系数",
  AutoFactorTooltip: "自身周期与组基准之间的比率。不同的周期长度会自动缩放。",
  Intersections: "路口",
  NoGroupsYet: "尚未创建任何组",
  Information: "信息",
  
  GreenWaveTooltip: "同步多个路口以实现绿波效果",
  GreenWaveTooltipActive: "沿道路同步多个路口，使车辆在绿波期间无需停车即可通过。",
  GreenWaveTooltipDisabled: "绿波仅在此路口启用「自定义相位」时可用。请先选择「自定义相位」。",
  SyncGroupTooltip: "选择此路口的同步组",
  CycleOffsetTooltip: "相对于组计时器的秒数偏移。不同的偏移创建绿波。",
  UseSyncedCycleTooltip: "启用与所选组的同步",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "路口",
  GWP_TabGroups: "组",
  GWP_TabDashboard: "仪表板",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "同步已激活",
  GWP_NotSynced: "未同步",

  // Green Wave Panel - Labels
  GWP_NodeId: "节点 ID (路口)",
  GWP_Group: "组",
  GWP_Offset: "偏移",
  GWP_AssignSyncGroup: "分配同步组",
  GWP_NoGroupSelected: "未选择组",
  GWP_NoGroup: "无组",
  GWP_NewGroup: "+ 新建组",
  GWP_Rename: "重命名",
  GWP_EnableSync: "启用同步",
  GWP_CycleOffset: "周期偏移",
  GWP_Tempo: "速度",
  GWP_Recommended: "推荐：",
  GWP_GameTime: "游戏",
  GWP_RealTime: "真实",
  GWP_PhaseHint: "相位 #1 应该是绿波的主方向！",
  GWP_AutoSave: "更改会自动保存",
  GWP_SelectIntersection: "请选择一个路口。",
  GWP_SearchGroups: "搜索组...",
  GWP_NoMatches: "没有匹配",
  GWP_RemoveFromGroup: "从组中移除",
  GWP_DeleteGroup: "删除组",
  GWP_NoIntersections: "路口",
  GWP_GroupsHint: "没有路口的组可以删除。在「路口」选项卡中添加路口。",
  GWP_SelectGroupHint: "在「路口」选项卡中选择一个组以查看详情。",
  GWP_AddIntersectionsHint: "此组还没有路口。前往「路口」选项卡添加路口！",
  GWP_RemovedFromGroup: "已从组中移除",
  GWP_AddedToGroup: "已添加到",
  GWP_SyncEnabled: "同步已启用！",
  GWP_SyncDisabled: "同步已禁用",
  GWP_NewGroupCreated: "新组已创建！",
  GWP_GroupRenamed: "组已重命名为",
  GWP_GroupDeleted: "组已删除",
  GWP_IntersectionRemoved: "路口已从组中移除",
  GWP_OffsetSet: "偏移已设置为",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "启用此路口与组的同步。",
  GWP_TT_SyncPhase: "同步相位",
  GWP_TT_CycleOffset: "与组基础周期的时间偏移（秒）。",
  GWP_TT_Distance: "距离",
  GWP_TT_Speed: "速度",
  GWP_TT_OwnCycle: "自身周期",
  GWP_TT_GroupBase: "组的基础周期（游戏时间）。",
  GWP_TT_Intersections: "路口",
  GWP_MoveUp: "上移",
  GWP_MoveDown: "下移",
  GWP_ManageGroups: "管理同步组",
  GWP_CreateNewGroup: "+ 创建新组",
  GWP_DB_Intersection: "路口",
  GWP_DB_Reference: "参考",
  GWP_DB_Phases: "相位",
  GWP_DB_Green: "绿灯",
  GWP_DB_SyncOn: "同步",
  GWP_DB_SyncOff: "关闭",
  GWP_DB_SyncWaiting: "同步中 - 等待",
  GWP_DB_GreenWaveActive: "绿波激活!",
  GWP_DB_ReadyToSwitch: "准备切换",
  GWP_DB_Offset: "偏移",
  GWP_DB_Cycle: "周期",
  GWP_DB_Roads: "道路",
  GWP_DB_Lanes: "车道",
  GWP_DB_Pedestrians: "行人",
  GWP_DB_OffsetDelta: "偏移",
  GWP_DB_BaseCycle: "基础周期",
  GWP_DB_GreenWaveLabel: "绿波",
  GWP_DB_SyncActiveLabel: "同步激活",
  GWP_DB_ReorderHint: "使用箭头键调整顺序。第一个路口是参考（偏移0）。",
  GWP_DB_PhaseProgressTooltip: "左侧：最小时间。闪烁：相位准备切换。",
  GWP_DB_MinDurationTooltip: "50%时达到最小时间。相位可随时切换。",
  GWP_DB_PhaseXofY: "相位 {0}/{1}",

  // V147: Traffic Summary
  TrafficSummary: "交通概览",
  VehiclesPerHour: "Ø 吞吐量",
  VehiclesPerMinute: "车辆/分钟",
  Approaches: "进入口",
  IncomingLanes: "进入车道",
  IncomingLanesTooltip: "进入路口的物理车道。",
  OccupiedLanes: "占用车道",
  OccupiedLanesTooltip: "有等待车辆的占用车道数量。",
  OccupiedPedestrianLanes: "行人道占用",
  TrafficFlowLow: "交通流量低",
  TrafficFlowMedium: "交通流量中",
  TrafficFlowHigh: "交通流量高",
  WaitingVehicles: "等待车辆",
  WaitingVehiclesTooltip: "当前等待车辆数量（平均值）。",
  PeakHour: "高峰(24h)",
  PeakHourTooltip: "过去24小时内交通量最大的时间。",
  MaxVPH: "最大车/时(24h)",
  MaxVPHTooltip: "过去24小时内最大车辆/小时。",
  VPH_InfoEstimate: "基于车道数和占用率的估算。",
  VPH_InfoRealData: "实际车辆计数的移动平均值。",
  ChartDisabledTooltip: "启用「自定义相位」以收集数据",
  ChartCollectingTooltip: "正在收集数据...约30分钟后显示首个值",
  ChartActiveTooltip: "24小时交通历史",
  CustomPhaseRequiredTooltip: "需要为此路口启用「自定义相位」。",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "删除相位？",
};
