export default {
  TrafficSignal: "交通信号灯",
  ModDefault: "默认",
  Vanilla: "原版",
  SplitPhasing: "分离相位",
  ProtectedRightTurns: "受保护右转",
  ProtectedLeftTurns: "受保护左转",
  Options: "选项",
  ExclusivePedestrianPhase: "专用行人相位",
  LaneDirectionTool: "车道方向工具（实验性）",
  
  Add: "添加相位",
  Back: "返回",
  ManualControl: "手动控制",
  CustomPhase: "自定义相位",
  CustomPhaseEditor: "编辑自定义相位",
  SelectFunction: "选择功能",
  SelectFunctionDescription: "选择一个功能来配置您的交通网络。",
  EditIntersectionPhases: "编辑路口相位",
  IntersectionMonitor: "路口监视器",
  DashboardComingSoon: "即将推出...",
  
  Close: "关闭",
  Open: "打开",
  Reset: "重置",
  Save: "保存",
  PleaseSave: "选择其他路口前请保存更改。",
  PleaseSelectJunction: "请选择一个路口",
  GiveWayToOncomingVehicles: "让行对向车辆",
  CustomPedestrianDurationMultiplier: "行人相位时长",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "允许红灯转弯",
  CanaryBuildWarning: "注意：您正在使用可能包含错误的金丝雀版本。此版本仅供测试。请勿用于正常游戏。",
  LdtMigrationNotice: "Lane Direction Tool已被krzychu124的Traffic模组取代。请安装Traffic模组以自动转移您的设置。",
  LdtRetirementNotice: "Lane Direction Tool已被krzychu124的Traffic模组取代。感谢您使用LDT。",
  
  PrioritiseTrack: "优先车辆",
  PrioritisePublicCar: "优先公共交通",
  PrioritisePedestrian: "优先行人",
  PrioritiseBicycle: "优先自行车",
  
  PrioritiseTrackTooltip: "在此相位期间优先普通车辆车道（汽车、卡车）",
  PrioritisePublicCarTooltip: "在此相位期间优先公共交通车道（公交车、有轨电车）",
  PrioritisePedestrianTooltip: "在此相位期间优先人行横道",
  PrioritiseBicycleTooltip: "在此相位期间优先自行车道",
  
  Adjustments: "调整",
  MinimumDuration: "最小时长",
  MaximumDuration: "最大时长",
  TargetDurationMultiplier: "目标时长",
  LaneOccupiedMultiplier: "车道占用率",
  IntervalExponent: "间隔指数",
  
  MinimumDurationTooltip: "最小绿灯时长。即使交通量很少，信号灯也会保持绿灯至少这么长时间。",
  MaximumDurationTooltip: "最大绿灯时长。超过此时间后，即使仍有车辆等待，信号灯也会切换。",
  TargetDurationMultiplierTooltip: "影响绿灯相位长度。1x = 正常，2x = 繁忙时加倍，0.5x = 缩短。",
  LaneOccupiedMultiplierTooltip: "控制满载车道增加多少优先级。较高 = 拥堵解决更快。",
  IntervalExponentTooltip: "公平性设置。较高 = 等待时间较长的相位获得更高优先级。",
  
  Statistics: "统计",
  Timer: "计时器",
  Priority: "优先级",
  LastRun: "上次运行",
  CarFlow: "车流量",
  LanesOccupied: "占用车道",
  WeightedWaiting: "加权等待时间",
  
  TimerTooltip: "当前计时器 / 目标时长",
  PriorityTooltip: "此相位的当前优先级值",
  LastRunTooltip: "此相位上次运行以来的回合数",
  CarFlowTooltip: "此相位的当前车流量",
  LanesOccupiedTooltip: "占用车道数（车辆、公交、轨道、行人）",
  WeightedWaitingTooltip: "此相位车辆的加权等待时间",
  
  EndPhasePrematurely: "立即结束相位",
  PhaseEndRequested: "已请求结束相位",
  SelectAll: "全选",
  DeselectAll: "取消全选",
  CopyPhases: "复制相位",
  PastePhases: "粘贴相位",
  DeleteSelectedPhases: "删除选中项",
  ClearClipboard: "清空剪贴板",
  
  SelectAllTooltip: "选择所有相位以复制或删除",
  CopyPhasesTooltip: "将选中的相位复制到剪贴板",
  PastePhasesTooltip: "从剪贴板粘贴相位",
  DeleteSelectedPhasesTooltip: "永久删除选中的相位",
  ClearClipboardTooltip: "清空剪贴板以防止意外粘贴",

  GreenWave: "绿波",
  GreenWaveButton: "绿波",
  SyncGroup: "同步组",
  NoSyncGroup: "无组",
  CreateNewGroup: "创建新组",
  CycleOffset: "周期偏移",
  UseSyncedCycle: "启用同步",
  TotalCycleDuration: "总周期时长",
  BaseCycleDuration: "基础周期",
  IntersectionsInGroup: "路口",
  NewGroupName: "新组",
  DeleteGroup: "删除组",
  RenameGroup: "重命名",
  OpenGreenWavePanel: "打开绿波",
  GreenWavePanelActive: "绿波已激活",
  
  PhaseMode: "相位模式",
  LegacyMode: "标准（优先级）",
  LegacyModeHint: "根据交通需求决定下一相位",
  LegacyModeTooltip: "相位根据优先级切换 - 等待的车辆和行人决定下一相位。默认游戏行为。",
  SequentialMode: "顺序（按序）",
  SequentialModeHint: "相位 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "相位按顺序运行：1 → 2 → 3 → 4 → 1... 固定、可预测的顺序。绿波必需。",
  GreenWaveForcesSequential: "绿波需要顺序模式",
  
  SyncSettings: "同步设置",
  SyncPhase: "同步相位",
  SyncPhaseTooltip: "选择要同步的相位。对转弯车道很有用。",
  OffsetCalculator: "偏移计算器",
  Distance: "距离",
  Speed: "速度",
  RecommendedOffset: "推荐",
  Apply: "应用",
  OwnCycle: "自身周期",
  GroupBase: "组基准",
  AutoFactor: "自动系数",
  AutoFactorTooltip: "自身周期与组基准之间的比率。不同的周期长度会自动缩放。",
  Intersections: "路口",
  NoGroupsYet: "尚未创建任何组",
  Information: "信息",
  
  GreenWaveTooltip: "同步多个路口以实现绿波效果",
  GreenWaveTooltipActive: "沿道路同步多个路口，使车辆在绿波期间无需停车即可通过。",
  GreenWaveTooltipDisabled: "绿波仅在此路口启用「自定义相位」时可用。请先选择「自定义相位」。",
  SyncGroupTooltip: "选择此路口的同步组",
  CycleOffsetTooltip: "相对于组计时器的秒数偏移。不同的偏移创建绿波。",
  UseSyncedCycleTooltip: "启用与所选组的同步",
};
