export default {
  TrafficSignal: "交通信号灯",
  ModDefault: "默认",
  Vanilla: "原版",
  SplitPhasing: "分离相位",
  ProtectedRightTurns: "受保护右转",
  ProtectedLeftTurns: "受保护左转",
  Options: "选项",
  ExclusivePedestrianPhase: "专用行人相位",
  LaneDirectionTool: "车道方向工具（实验性）",
  
  Add: "添加相位",
  Back: "返回",
  ManualControl: "手动控制",
  CustomPhase: "自定义相位",
  CustomPhaseEditor: "编辑自定义相位",
  SelectFunction: "选择功能",
  SelectFunctionDescription: "选择一个功能来配置您的交通网络。",
  EditIntersectionPhases: "编辑路口相位",
  IntersectionMonitor: "路口监视器",
  DashboardComingSoon: "即将推出...",
  
  Close: "关闭",
  Open: "打开",
  Reset: "重置",
  Save: "保存",
  PleaseSave: "选择其他路口前请保存更改。",
  PleaseSelectJunction: "请选择一个路口",
  GiveWayToOncomingVehicles: "让行对向车辆",
  CustomPedestrianDurationMultiplier: "行人相位时长",
  CustomPedestrianDurationMultiplierSuffix: "x",
  AllowTurningOnRed: "允许红灯转弯",
  CanaryBuildWarning: "注意：您正在使用可能包含错误的金丝雀版本。此版本仅供测试。请勿用于正常游戏。",
  LdtMigrationNotice: "Lane Direction Tool已被krzychu124的Traffic模组取代。请安装Traffic模组以自动转移您的设置。",
  LdtRetirementNotice: "Lane Direction Tool已被krzychu124的Traffic模组取代。感谢您使用LDT。",
  
  PrioritiseTrack: "优先车辆",
  PrioritisePublicCar: "优先公共交通",
  PrioritisePedestrian: "优先行人",
  PrioritiseBicycle: "优先自行车",
  
  PrioritiseTrackTooltip: "在此相位期间优先普通车辆车道（汽车、卡车）",
  PrioritisePublicCarTooltip: "在此相位期间优先公共交通车道（公交车、有轨电车）",
  PrioritisePedestrianTooltip: "在此相位期间优先人行横道",
  PrioritiseBicycleTooltip: "在此相位期间优先自行车道",
  
  Adjustments: "调整",
  MinimumDuration: "最小时长",
  MaximumDuration: "最大时长",
  TargetDurationMultiplier: "目标时长",
  LaneOccupiedMultiplier: "车道占用率",
  IntervalExponent: "间隔指数",
  
  MinimumDurationTooltip: "最小绿灯时长。即使交通量很少，信号灯也会保持绿灯至少这么长时间。",
  MaximumDurationTooltip: "最大绿灯时长。超过此时间后，即使仍有车辆等待，信号灯也会切换。",
  TargetDurationMultiplierTooltip: "影响绿灯相位长度。1x = 正常，2x = 繁忙时加倍，0.5x = 缩短。",
  LaneOccupiedMultiplierTooltip: "控制满载车道增加多少优先级。较高 = 拥堵解决更快。",
  IntervalExponentTooltip: "公平性设置。较高 = 等待时间较长的相位获得更高优先级。",
  
  Statistics: "统计",
  Timer: "计时器",
  Priority: "优先级",
  LastRun: "上次运行",
  CarFlow: "车流量",
  LanesOccupied: "占用车道",
  WeightedWaiting: "加权等待时间",
  
  TimerTooltip: "当前计时器 / 目标时长",
  PriorityTooltip: "此相位的当前优先级值",
  LastRunTooltip: "此相位上次运行以来的回合数",
  CarFlowTooltip: "此相位的当前车流量",
  LanesOccupiedTooltip: "占用车道数（车辆、公交、轨道、行人）",
  WeightedWaitingTooltip: "此相位车辆的加权等待时间",
  
  EndPhasePrematurely: "立即结束相位",
  PhaseEndRequested: "已请求结束相位",
  SelectAll: "全选",
  DeselectAll: "取消全选",
  CopyPhases: "复制相位",
  PastePhases: "粘贴相位",
  DeleteSelectedPhases: "删除选中项",
  ClearClipboard: "清空剪贴板",
  
  SelectAllTooltip: "选择所有相位以复制或删除",
  CopyPhasesTooltip: "将选中的相位复制到剪贴板",
  PastePhasesTooltip: "从剪贴板粘贴相位",
  DeleteSelectedPhasesTooltip: "永久删除选中的相位",
  ClearClipboardTooltip: "清空剪贴板以防止意外粘贴",

  GreenWave: "绿波",
  GreenWaveButton: "绿波",
  SyncGroup: "同步组",
  NoSyncGroup: "无组",
  CreateNewGroup: "创建新组",
  CycleOffset: "周期偏移",
  UseSyncedCycle: "启用同步",
  TotalCycleDuration: "总周期时长",
  BaseCycleDuration: "基础周期",
  IntersectionsInGroup: "路口",
  NewGroupName: "新组",
  DeleteGroup: "删除组",
  RenameGroup: "重命名",
  OpenGreenWavePanel: "打开绿波",
  GreenWavePanelActive: "绿波已激活",
  
  PhaseMode: "相位模式",
  LegacyMode: "标准（优先级）",
  LegacyModeHint: "根据交通需求决定下一相位",
  LegacyModeTooltip: "相位根据优先级切换 - 等待的车辆和行人决定下一相位。默认游戏行为。",
  SequentialMode: "顺序（按序）",
  SequentialModeHint: "相位 1 → 2 → 3 → 4 → 1...",
  SequentialModeTooltip: "相位按顺序运行：1 → 2 → 3 → 4 → 1... 固定、可预测的顺序。绿波必需。",
  GreenWaveForcesSequential: "绿波需要顺序模式",
  
  SyncSettings: "同步設定",
  SyncPhase: "同步相位",
  SyncPhaseTooltip: "揀要同步嘅相位。適用於轉彎車道。",
  OffsetCalculator: "偏移計算器",
  Distance: "距離",
  Speed: "速度",
  RecommendedOffset: "推荐",
  Apply: "套用",
  OwnCycle: "自身週期",
  GroupBase: "组基准",
  AutoFactor: "自动系数",
  AutoFactorTooltip: "自身周期与组基准之间的比率。不同的周期长度会自动缩放。",
  Intersections: "路口",
  NoGroupsYet: "尚未创建任何组",
  Information: "資訊",
  
  GreenWaveTooltip: "同步多个路口以实现绿波效果",
  GreenWaveTooltipActive: "沿道路同步多个路口，使车辆在绿波期间无需停车即可通过。",
  GreenWaveTooltipDisabled: "绿波仅在此路口启用「自定义相位」时可用。请先选择「自定义相位」。",
  SyncGroupTooltip: "选择此路口的同步组",
  CycleOffsetTooltip: "相对于组计时器的秒数偏移。不同的偏移创建绿波。",
  UseSyncedCycleTooltip: "启用与所选组的同步",

  // Green Wave Panel - Tab Labels
  GWP_TabIntersection: "路口",
  GWP_TabGroups: "組",
  GWP_TabDashboard: "儀表板",

  // Green Wave Panel - Sync Status
  GWP_SyncActive: "同步已啟動",
  GWP_NotSynced: "未同步",

  // Green Wave Panel - Labels
  GWP_NodeId: "節點 ID (路口)",
  GWP_Group: "組",
  GWP_Offset: "偏移",
  GWP_AssignSyncGroup: "分配同步組",
  GWP_NoGroupSelected: "未揀組",
  GWP_NoGroup: "冇組",
  GWP_NewGroup: "+ 新建組",
  GWP_Rename: "改名",
  GWP_EnableSync: "啟用同步",
  GWP_CycleOffset: "週期偏移",
  GWP_Tempo: "速度",
  GWP_Recommended: "建議：",
  GWP_GameTime: "遊戲",
  GWP_RealTime: "真實",
  GWP_PhaseHint: "相位 #1 應該係綠波嘅主方向！",
  GWP_AutoSave: "更改會自動儲存",
  GWP_SelectIntersection: "請揀一個路口。",
  GWP_SearchGroups: "搜尋組...",
  GWP_NoMatches: "冇匹配",
  GWP_RemoveFromGroup: "從組中移除",
  GWP_DeleteGroup: "刪除組",
  GWP_NoIntersections: "路口",
  GWP_GroupsHint: "冇路口嘅組可以刪除。喺「路口」選項卡添加路口。",
  GWP_SelectGroupHint: "喺「路口」選項卡揀一個組嚟睇詳情。",
  GWP_AddIntersectionsHint: "呢個組仲未有路口。去「路口」選項卡添加路口！",
  GWP_RemovedFromGroup: "已從組中移除",
  GWP_AddedToGroup: "已添加到",
  GWP_SyncEnabled: "同步已啟用！",
  GWP_SyncDisabled: "同步已停用",
  GWP_NewGroupCreated: "新組已建立！",
  GWP_GroupRenamed: "組已改名為",
  GWP_GroupDeleted: "組已刪除",
  GWP_IntersectionRemoved: "路口已從組中移除",
  GWP_OffsetSet: "偏移已設定為",

  // Green Wave Panel - Tooltips
  GWP_TT_EnableSync: "啟用呢個路口同組嘅同步。",
  GWP_TT_SyncPhase: "同步相位",
  GWP_TT_CycleOffset: "同組基礎週期嘅時間偏移（秒）。",
  GWP_TT_Distance: "距離",
  GWP_TT_Speed: "速度",
  GWP_TT_OwnCycle: "自身週期",
  GWP_TT_GroupBase: "組嘅基礎週期（遊戲時間）。",
  GWP_TT_Intersections: "路口",
  GWP_MoveUp: "上移",
  GWP_MoveDown: "下移",
  GWP_ManageGroups: "管理同步組",
  GWP_CreateNewGroup: "+ 建立新組",
  GWP_DB_Intersection: "路口",
  GWP_DB_Reference: "參考",
  GWP_DB_Phases: "相位",
  GWP_DB_Green: "綠燈",
  GWP_DB_SyncOn: "同步",
  GWP_DB_SyncOff: "關閉",
  GWP_DB_SyncWaiting: "同步中 - 等待",
  GWP_DB_GreenWaveActive: "綠波啟動!",
  GWP_DB_ReadyToSwitch: "準備切換",
  GWP_DB_Offset: "偏移",
  GWP_DB_Cycle: "週期",
  GWP_DB_Roads: "道路",
  GWP_DB_Lanes: "車道",
  GWP_DB_Pedestrians: "行人",
  GWP_DB_OffsetDelta: "偏移",
  GWP_DB_BaseCycle: "基礎週期",
  GWP_DB_GreenWaveLabel: "綠波",
  GWP_DB_SyncActiveLabel: "同步啟動",
  GWP_DB_ReorderHint: "用箭頭鍵調整順序。第一個路口係參考（偏移0）。",
  GWP_DB_PhaseProgressTooltip: "左邊：最小時間。閃爍：相位準備切換。",
  GWP_DB_MinDurationTooltip: "50%時達到最小時間。相位可隨時切換。",
  GWP_DB_PhaseXofY: "相位 {0}/{1}",

  // V147: Traffic Summary
  TrafficSummary: "交通概覽",
  VehiclesPerHour: "Ø 吞吐量",
  VehiclesPerMinute: "車輛/分鐘",
  Approaches: "進入口",
  IncomingLanes: "進入車道",
  IncomingLanesTooltip: "進入路口嘅物理車道。",
  OccupiedLanes: "佔用車道",
  OccupiedLanesTooltip: "有等待車輛嘅佔用車道數量。",
  OccupiedPedestrianLanes: "行人道佔用",
  TrafficFlowLow: "交通流量低",
  TrafficFlowMedium: "交通流量中",
  TrafficFlowHigh: "交通流量高",
  WaitingVehicles: "等待車輛",
  WaitingVehiclesTooltip: "當前等待車輛數量（平均值）。",
  PeakHour: "高峰(24h)",
  PeakHourTooltip: "過去24小時內交通量最大嘅時間。",
  MaxVPH: "最大車/時(24h)",
  MaxVPHTooltip: "過去24小時內最大車輛/小時。",
  VPH_InfoEstimate: "基於車道數同佔用率嘅估算。",
  VPH_InfoRealData: "實際車輛計數嘅移動平均值。",
  ChartDisabledTooltip: "啟用「自定義相位」嚟收集數據",
  ChartCollectingTooltip: "正在收集數據...約30分鐘後顯示首個值",
  ChartActiveTooltip: "24小時交通歷史",
  CustomPhaseRequiredTooltip: "需要為此路口啟用「自定義相位」。",

  // V248: Delete Phase Confirmation
  DeletePhaseConfirmShort: "刪除相位？",
};
